### ISSUE TITLE
使用paddlepaddle1.8版本使用PaddleDetection的时候，提示yolov3_loss() got an unexpected keyword argument 'scale_x_y'

### ISSUE THREAD

**Issue by a2824256** [PaddlePaddle/PaddleDetection#1145]
运行教程
https://paddledetection.readthedocs.io/tutorials/INSTALL_cn.html#id4
执行测试是否安装成功的命令的时候
`python ppdet/modeling/tests/test_architectures.py`
提示
`TypeError: yolov3_loss() got an unexpected keyword argument 'scale_x_y'`
后来发现
PaddleDetection\ppdet\modeling\losses\yolo_loss.py这个文件第87行，
loss = fluid.layers.yolov3_loss这一句，yolov3_loss含有scale_x_y这个参数，
实际上paddle\fluid\layers\detection.py第925行，yolov3_loss这个函数不含有scale_x_y这个参数

**Comment by a2824256** [comment]
test_architectures.py 第437行, fluid.layers.yolo_box这个函数也不含有scale_x_y这个参数，但是代码test_architectures.py里却写上了

**Comment by qingqing01** [comment]
@a2824256  这个是由于PaddleDetection和paddle版本的对应问题导致的，参考 https://github.com/PaddlePaddle/Paddle/issues/25888#issuecomment-667779294

**Comment by heavengate** [comment]
感谢反馈，已修复，https://github.com/PaddlePaddle/PaddleDetection/pull/1147  可以pull一下最新代码~

**Comment by adrianosantospb** [comment]
First of all, congratulation for the great job!

So, I've got the same issure. I've done install process and test as well. I'm trying to use the Quick start example (https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/tutorials/QUICK_STARTED.md). When I've ran: python3 -u tools/train.py -c configs/yolov3_mobilenet_v1_fruit.yml --eval


Traceback (most recent call last):
  File "tools/train.py", line 368, in <module>
    main()
  File "tools/train.py", line 114, in main
    train_fetches = model.train(feed_vars)
  File "/media/adriano/CC64676064674BF0/Dados/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 159, in train
    return self.build(feed_vars, mode='train')
  File "/media/adriano/CC64676064674BF0/Dados/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 85, in build
    gt_score, targets)
  File "/media/adriano/CC64676064674BF0/Dados/PaddleDetection/ppdet/modeling/anchor_heads/yolo_head.py", line 401, in get_loss
    self.prefix_name)
  File "/media/adriano/CC64676064674BF0/Dados/PaddleDetection/ppdet/modeling/losses/yolo_loss.py", line 89, in __call__
    name=prefix_name + "yolo_loss" + str(i))
TypeError: yolov3_loss() got an unexpected keyword argument 'scale_x_y'

**Comment by heavengate** [comment]
> First of all, congratulation for the great job!
> 
> So, I've got the same issure. I've done install process and test as well. I'm trying to use the Quick start example (https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/tutorials/QUICK_STARTED.md). When I've ran: python3 -u tools/train.py -c configs/yolov3_mobilenet_v1_fruit.yml --eval
> 
> Traceback (most recent call last):
> File "tools/train.py", line 368, in 
> main()
> File "tools/train.py", line 114, in main
> train_fetches = model.train(feed_vars)
> File "/media/adriano/CC64676064674BF0/Dados/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 159, in train
> return self.build(feed_vars, mode='train')
> File "/media/adriano/CC64676064674BF0/Dados/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 85, in build
> gt_score, targets)
> File "/media/adriano/CC64676064674BF0/Dados/PaddleDetection/ppdet/modeling/anchor_heads/yolo_head.py", line 401, in get_loss
> self.prefix_name)
> File "/media/adriano/CC64676064674BF0/Dados/PaddleDetection/ppdet/modeling/losses/yolo_loss.py", line 89, in **call**
> name=prefix_name + "yolo_loss" + str(i))
> TypeError: yolov3_loss() got an unexpected keyword argument 'scale_x_y'

1. please pull the lastest version of brach `develop` or `release/0.4`
2. if you want to try PPYOLO, please install Paddle daily version here https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html#whl-dev 
or use Paddle 2.0.0a, and disable `Matrix NMS` in PPYOLO config
```
YOLOv3Head:
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  anchors: [[10, 13], [16, 30], [33, 23],
            [30, 61], [62, 45], [59, 119],
            [116, 90], [156, 198], [373, 326]]
  norm_decay: 0.
  coord_conv: true
  iou_aware: true
  iou_aware_factor: 0.4
  scale_x_y: 1.05
  spp: true
  yolo_loss: YOLOv3Loss
  nms:
    background_label: -1
    keep_top_k: 100
    nms_threshold: 0.45
    nms_top_k: 1000
    normalized: false
    score_threshold: 0.01
  drop_block: true
```
