### ISSUE TITLE
[黄埔学院] cascade mask rcnn 部署到c++端时报错

### ISSUE THREAD

**Issue by Tinagao222** [PaddlePaddle/PaddleDetection#1172]
使用CMake生成成功后，测试了yolov3模型，是可以成功得到output.jpg；但换成cascade_mask_rcnn_r50_fpn_1x模型后，报了如下错误。
错误出现在impl.h的第155行
// access functions
template <typename T>
inline T Node::as() const {
  if (!m_isValid)
    throw InvalidNode(m_invalidKey);
  return as_if<T, void>(*this)();
}

报错信息：
0x00007FF9FE0BA799 处(位于 main.exe 中)有未经处理的异常: Microsoft C++ 异常: YAML::InvalidNode，位于内存位置 0x00000091186FF600 处。

使用环境：VS2019；paddlepaddle-gpu1.8.3；paddledetection release/0.4； cuda10.0

**Comment by joey12300** [comment]
请检查模型目录下yaml文件里是否存在无效的key？

**Comment by Tinagao222** [comment]
use_python_inference: false
mode: fluid
draw_threshold: 0.5
metric: COCO
arch: RCNN
min_subgraph_size: 40
mask_resolution: 28
with_background: true
Preprocess:
- is_channel_first: false
  is_scale: true
  mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
  type: Normalize
- interp: 1
  max_size: 1333
  target_size: 800
  type: Resize
  use_cv2: true
- channel_first: true
  to_bgr: false
  type: Permute
- stride: 32
  type: PadStride
label_list:
- background
- bolt
- nut


上面是yaml文件的内容，请问怎么看出是否是无效的key？

**Comment by Tinagao222** [comment]
> 请检查模型目录下yaml文件里是否存在无效的key？

请问怎么看出是否是无效的key？

**Comment by Tinagao222** [comment]
> 请检查模型目录下yaml文件里是否存在无效的key？
> 
> 请问怎么看出是否是无效的key？

把yaml改成下面这样就可以了，谢谢啦

use_python_inference: false
mode: fluid
draw_threshold: 0.5
metric: COCO
arch: RCNN
min_subgraph_size: 40
mask_resolution: 28
with_background: true
Preprocess:
- image_shape:
  - 1333
  - 800
  interp: 1
  max_size: 1333
  target_size: 800
  type: Resize
  use_cv2: true
- is_channel_first: false
  is_scale: true
  mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
  type: Normalize
- channel_first: true
  to_bgr: false
  type: Permute
- stride: 32
  type: PadStride
label_list:
- background
- bolt
- nut

**Comment by jerrywgz** [comment]
应该是配置文件中缺少image shape导致的，https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/docs/advanced_tutorials/deploy/EXPORT_MODEL.md#%E8%AE%BE%E7%BD%AE%E5%AF%BC%E5%87%BA%E6%A8%A1%E5%9E%8B%E7%9A%84%E8%BE%93%E5%85%A5%E5%A4%A7%E5%B0%8F 可以先按照这里面的方式在导出模型的时候指定image shape，我们后续会再加强下

**Comment by jerrywgz** [comment]
``` yaml
use_python_inference: false
mode: fluid
draw_threshold: 0.5
metric: COCO
arch: RCNN
min_subgraph_size: 40
mask_resolution: 28
with_background: true
Preprocess:
- is_channel_first: false
  is_scale: true
  mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
  type: Normalize
- image_shape: [3, 1333, 1333]
  interp: 1
  max_size: 1333
  target_size: 800
  type: Resize
  use_cv2: true
- channel_first: true
  to_bgr: false
  type: Permute
- stride: 32
  type: PadStride
label_list:
- background
...
```
