### ISSUE TITLE
op `matrix_nms` 不支持PaddleLite问题

### ISSUE THREAD

**Issue by dklinzh** [PaddlePaddle/PaddleDetection#1310]
使用`paddle_lite_opt`转化用`ppyolo_r18vd`训练导出的模型
```
paddle_lite_opt --valid_targets=arm --optimize_out_type=naive_buffer --model_file=../__model__ --param_file=../__params__  --optimize_out=../opt --record_tailoring_info=true
```
 提示错误:
> WARNING: Logging before InitGoogleLogging() is written to STDERR
> E0828 10:50:40.061033 29392 opt_base.cc:445] Error: This model is not supported, because 1 ops are not supported on 'arm'. These unsupported ops are: 'matrix_nms'.

环境:
- PaddlePaddle 1.8.4.post107
- PaddleDetection release/0.4 9e38894
- paddlelite-2.6.1-cp37-cp37m-manylinux1_x86_64.whl
- Python 3.7.3

自定义的`yml`配置如下:
```
architecture: YOLOv3
use_gpu: true
max_iters: 100000
log_smooth_window: 20
log_iter: 20
snapshot_iter: 1000
metric: VOC
map_type: 11point # integral
pretrain_weights: https://paddlemodels.bj.bcebos.com/object_detection/ppyolo_r18vd.pdparams
weights: ../PaddleDetection_Output/model/ppyolo_r18vd_plate/T0/ppyolo_r18vd_plate/best_model
save_dir: ../PaddleDetection_Output/model/ppyolo_r18vd_plate/T0
num_classes: 1
use_fine_grained_loss: true
use_ema: true
ema_decay: 0.9998

YOLOv3:
  backbone: ResNet
  yolo_head: YOLOv3Head
  use_fine_grained_loss: true

ResNet:
  norm_type: sync_bn
  freeze_at: 0
  freeze_norm: false
  norm_decay: 0.
  depth: 18
  feature_maps: [4, 5]
  variant: d

YOLOv3Head:
  anchor_masks: [[3, 4, 5], [0, 1, 2]]
  anchors: [[10, 14], [23, 27], [37, 58],
            [81, 82], [135, 169], [344, 319]]
  norm_decay: 0.
  conv_block_num: 0
  scale_x_y: 1.05
  yolo_loss: YOLOv3Loss
  nms: MatrixNMS
  drop_block: true

YOLOv3Loss:
  batch_size: 8
  ignore_thresh: 0.7
  scale_x_y: 1.05
  label_smooth: false
  use_fine_grained_loss: true
  iou_loss: IouLoss

IouLoss:
  loss_weight: 2.5
  max_height: 608
  max_width: 608

MatrixNMS:
    background_label: -1
    keep_top_k: 100
    normalized: false
    score_threshold: 0.01
    post_threshold: 0.01

LearningRate:
  base_lr: 0.00025
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 60000
    - 80000
  - !LinearWarmup
    start_factor: 0.
    steps: 1600

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

_READER_: 'ppyolo_reader.yml'
TrainReader:
  inputs_def:
    fields: ['image', 'gt_bbox', 'gt_class', 'gt_score']
    num_max_boxes: 50
  dataset:
    !VOCDataSet
    dataset_dir: ../PaddleDetection_DataSet/plate_new
    anno_path: train.txt
    use_default_label: false
    with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
      with_mixup: True
    - !MixupImage
      alpha: 1.5
      beta: 1.5
    - !ColorDistort {}
    - !RandomExpand
      fill_value: [123.675, 116.28, 103.53]
    - !RandomCrop {}
    - !RandomFlipImage
      is_normalized: false
    - !NormalizeBox {}
    - !PadBox
      num_max_boxes: 50
    - !BboxXYXY2XYWH {}
  batch_transforms:
  - !RandomShape
    sizes: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608]
    random_inter: True
  - !NormalizeImage
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    is_scale: True
    is_channel_first: false
  - !Permute
    to_bgr: false
    channel_first: True
  # Gt2YoloTarget is only used when use_fine_grained_loss set as true,
  # this operator will be deleted automatically if use_fine_grained_loss
  # is set as false
  - !Gt2YoloTarget
    anchor_masks: [[3, 4, 5], [0, 1, 2]]
    anchors: [[10, 14], [23, 27], [37, 58],
              [81, 82], [135, 169], [344, 319]]
    downsample_ratios: [32, 16]
  batch_size: 8
  shuffle: true
  mixup_epoch: 500
  drop_last: true
  worker_num: 16
  bufsize: 8
  use_process: true

EvalReader:
  inputs_def:
    fields: ['image', 'im_size', 'im_id', 'gt_bbox', 'gt_class', 'is_difficult']
    num_max_boxes: 50
  dataset:
    !VOCDataSet
    dataset_dir: ../PaddleDetection_DataSet/plate_new
    anno_path: val.txt
    use_default_label: false
    with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
    - !ResizeImage
      target_size: 608
      interp: 2
    - !NormalizeImage
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_scale: True
      is_channel_first: false
    - !PadBox
      num_max_boxes: 50
    - !Permute
      to_bgr: false
      channel_first: True
  batch_size: 8
  drop_empty: false
  worker_num: 8
  bufsize: 4

TestReader:
  inputs_def:
    image_shape: [3, 608, 608]
    fields: ['image', 'im_size', 'im_id']
  dataset:
    !ImageFolder
    anno_path: ../PaddleDetection_DataSet/plate_new/label_list.txt
    use_default_label: false
    with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
    - !ResizeImage
      target_size: 608
      interp: 2
    - !NormalizeImage
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_scale: True
      is_channel_first: false
    - !Permute
      to_bgr: false
      channel_first: True
  batch_size: 1
```

**Comment by heavengate** [comment]
PaddleLite上支持Matrix NMS的需求我们正在排期，如果你需要部署到移动端，可以把配置文件改成下面这种形式，不使用matrix nms重新export，改完之后直接export就行，不用重新训练，精度可能会有小量的损失
```
YOLOv3Head:
  anchor_masks: [[3, 4, 5], [0, 1, 2]]
  anchors: [[10, 14], [23, 27], [37, 58],
            [81, 82], [135, 169], [344, 319]]
  norm_decay: 0.
  conv_block_num: 0
  iou_aware: true
  iou_aware_factor: 0.4
  scale_x_y: 1.05
  yolo_loss: YOLOv3Loss
  # nms: MatrixNMS
  nms:
    background_label: -1
    keep_top_k: 100
    nms_threshold: 0.45
    nms_top_k: 1000
    normalized: false
    score_threshold: 0.01
  drop_block: true
```

**Comment by dklinzh** [comment]
> PaddleLite上支持Matrix NMS的需求我们正在排期，如果你需要部署到移动端，可以把配置文件改成下面这种形式，不使用matrix nms重新export，改完之后直接export就行，不用重新训练，精度可能会有小量的损失
> 
> ```
> YOLOv3Head:
>   anchor_masks: [[3, 4, 5], [0, 1, 2]]
>   anchors: [[10, 14], [23, 27], [37, 58],
>             [81, 82], [135, 169], [344, 319]]
>   norm_decay: 0.
>   conv_block_num: 0
>   iou_aware: true
>   iou_aware_factor: 0.4
>   scale_x_y: 1.05
>   yolo_loss: YOLOv3Loss
>   # nms: MatrixNMS
>   nms:
>     background_label: -1
>     keep_top_k: 100
>     nms_threshold: 0.45
>     nms_top_k: 1000
>     normalized: false
>     score_threshold: 0.01
>   drop_block: true
> ```

根据你的方法重新opt, 会提示新的op不支持:

> E0828 15:51:38.253015  7534 opt_base.cc:445] Error: This model is not supported, because 2 ops are not supported on 'arm'. These unsupported ops are: 'clip, pow'.

**Comment by dklinzh** [comment]
按照上面的修改, 重新训练也出现了错误. @heavengate 能帮忙看看哪不对吗? 谢谢!

> Traceback (most recent call last):
>   File "tools/train.py", line 370, in <module>
>     main()
>   File "tools/train.py", line 116, in main
>     train_fetches = model.train(feed_vars)
>   File "/home/dklinzh/Documents/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 159, in train
>     return self.build(feed_vars, mode='train')
>   File "/home/dklinzh/Documents/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 85, in build
>     gt_score, targets)
>   File "/home/dklinzh/Documents/PaddleDetection/ppdet/modeling/anchor_heads/yolo_head.py", line 394, in get_loss
>     self.prefix_name)
>   File "/home/dklinzh/Documents/PaddleDetection/ppdet/modeling/losses/yolo_loss.py", line 69, in __call__
>     mask_anchors, self._ignore_thresh)
>   File "/home/dklinzh/Documents/PaddleDetection/ppdet/modeling/losses/yolo_loss.py", line 162, in _get_fine_grained_loss
>     loss_x = fluid.layers.abs(dx - tx) * tscale_tobj
>   File "/home/dklinzh/.local/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py", line 248, in __impl__
>     attrs={'axis': axis})
>   File "/home/dklinzh/.local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
>     attrs=kwargs.get("attrs", None))
>   File "/home/dklinzh/.local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1971, in __init__
>     self.desc.infer_shape(self.block.desc)
> paddle.fluid.core_avx.EnforceNotMet: 
> 
> --------------------------------------------
> C++ Call Stacks (More useful to developers):
> --------------------------------------------
> 0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
> 1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
> 2   paddle::operators::GetBroadcastDimsArrays(paddle::framework::DDim const&, paddle::framework::DDim const&, int*, int*, int*, int, int)
> 3   paddle::operators::ElementwiseOp::InferShape(paddle::framework::InferShapeContext*) const
> 4   paddle::framework::OpDesc::InferShape(paddle::framework::BlockDesc const&) const
> 
> ------------------------------------------
> Python Call Stacks (More useful to users):
> ------------------------------------------
>   File "/home/dklinzh/.local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
>     attrs=kwargs.get("attrs", None))
>   File "/home/dklinzh/.local/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py", line 248, in __impl__
>     attrs={'axis': axis})
>   File "/home/dklinzh/Documents/PaddleDetection/ppdet/modeling/losses/yolo_loss.py", line 162, in _get_fine_grained_loss
>     loss_x = fluid.layers.abs(dx - tx) * tscale_tobj
>   File "/home/dklinzh/Documents/PaddleDetection/ppdet/modeling/losses/yolo_loss.py", line 69, in __call__
>     mask_anchors, self._ignore_thresh)
>   File "/home/dklinzh/Documents/PaddleDetection/ppdet/modeling/anchor_heads/yolo_head.py", line 394, in get_loss
>     self.prefix_name)
>   File "/home/dklinzh/Documents/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 85, in build
>     gt_score, targets)
>   File "/home/dklinzh/Documents/PaddleDetection/ppdet/modeling/architectures/yolo.py", line 159, in train
>     return self.build(feed_vars, mode='train')
>   File "tools/train.py", line 116, in main
>     train_fetches = model.train(feed_vars)
>   File "tools/train.py", line 370, in <module>
>     main()
> 
> ----------------------
> Error Message Summary:
> ----------------------
> InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [-1, 4, -1, -1] and the shape of Y = [-1, 3, -1, -1]. Received [4] in X is not equal to [3] in Y at i:1.
>   [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] at (/paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:160)
>   [operator < elementwise_sub > error]

`ppyolo_r18vd_plate.yml` 配置如下:
```
architecture: YOLOv3
use_gpu: true
max_iters: 100000
log_smooth_window: 20
log_iter: 20
snapshot_iter: 1000
metric: VOC
map_type: 11point # integral
pretrain_weights: https://paddlemodels.bj.bcebos.com/object_detection/ppyolo_r18vd.pdparams
weights: ../PaddleDetection_Output/model/ppyolo_r18vd_plate/T1/ppyolo_r18vd_plate/best_model
save_dir: ../PaddleDetection_Output/model/ppyolo_r18vd_plate/T1
num_classes: 1
use_fine_grained_loss: true
use_ema: true
ema_decay: 0.9998

YOLOv3:
  backbone: ResNet
  yolo_head: YOLOv3Head
  use_fine_grained_loss: true

ResNet:
  norm_type: sync_bn
  freeze_at: 0
  freeze_norm: false
  norm_decay: 0.
  depth: 18
  feature_maps: [4, 5]
  variant: d

YOLOv3Head:
  anchor_masks: [[3, 4, 5], [0, 1, 2]]
  anchors: [[10, 14], [23, 27], [37, 58],
            [81, 82], [135, 169], [344, 319]]
  norm_decay: 0.
  conv_block_num: 0
  iou_aware: true
  iou_aware_factor: 0.4
  scale_x_y: 1.05
  yolo_loss: YOLOv3Loss
  # nms: MatrixNMS
  nms:
    background_label: -1
    keep_top_k: 100
    nms_threshold: 0.45
    nms_top_k: 1000
    normalized: false
    score_threshold: 0.01
  drop_block: true

YOLOv3Loss:
  batch_size: 8
  ignore_thresh: 0.7
  scale_x_y: 1.05
  label_smooth: false
  use_fine_grained_loss: true
  iou_loss: IouLoss

IouLoss:
  loss_weight: 2.5
  max_height: 608
  max_width: 608

MatrixNMS:
    background_label: -1
    keep_top_k: 100
    normalized: false
    score_threshold: 0.01
    post_threshold: 0.01

LearningRate:
  base_lr: 0.00025
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 60000
    - 80000
  - !LinearWarmup
    start_factor: 0.
    steps: 1600

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

_READER_: 'ppyolo_reader.yml'
TrainReader:
  inputs_def:
    fields: ['image', 'gt_bbox', 'gt_class', 'gt_score']
    num_max_boxes: 50
  dataset:
    !VOCDataSet
    dataset_dir: ../PaddleDetection_DataSet/plate_new
    anno_path: train.txt
    use_default_label: false
    with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
      with_mixup: True
    - !MixupImage
      alpha: 1.5
      beta: 1.5
    - !ColorDistort {}
    - !RandomExpand
      fill_value: [123.675, 116.28, 103.53]
    - !RandomCrop {}
    - !RandomFlipImage
      is_normalized: false
    - !NormalizeBox {}
    - !PadBox
      num_max_boxes: 50
    - !BboxXYXY2XYWH {}
  batch_transforms:
  - !RandomShape
    sizes: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608]
    random_inter: True
  - !NormalizeImage
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    is_scale: True
    is_channel_first: false
  - !Permute
    to_bgr: false
    channel_first: True
  # Gt2YoloTarget is only used when use_fine_grained_loss set as true,
  # this operator will be deleted automatically if use_fine_grained_loss
  # is set as false
  - !Gt2YoloTarget
    anchor_masks: [[3, 4, 5], [0, 1, 2]]
    anchors: [[10, 14], [23, 27], [37, 58],
              [81, 82], [135, 169], [344, 319]]
    downsample_ratios: [32, 16]
  batch_size: 8
  shuffle: true
  mixup_epoch: 500
  drop_last: true
  worker_num: 16
  bufsize: 8
  use_process: true

EvalReader:
  inputs_def:
    fields: ['image', 'im_size', 'im_id', 'gt_bbox', 'gt_class', 'is_difficult']
    num_max_boxes: 50
  dataset:
    !VOCDataSet
    dataset_dir: ../PaddleDetection_DataSet/plate_new
    anno_path: val.txt
    use_default_label: false
    with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
    - !ResizeImage
      target_size: 608
      interp: 2
    - !NormalizeImage
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_scale: True
      is_channel_first: false
    - !PadBox
      num_max_boxes: 50
    - !Permute
      to_bgr: false
      channel_first: True
  batch_size: 8
  drop_empty: false
  worker_num: 8
  bufsize: 4
  use_process: true

TestReader:
  inputs_def:
    image_shape: [3, 608, 608]
    fields: ['image', 'im_size', 'im_id']
  dataset:
    !ImageFolder
    anno_path: ../PaddleDetection_DataSet/plate_new/label_list.txt
    use_default_label: false
    with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
    - !ResizeImage
      target_size: 608
      interp: 2
    - !NormalizeImage
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_scale: True
      is_channel_first: false
    - !Permute
      to_bgr: false
      channel_first: True
  batch_size: 1
```
