### ISSUE TITLE
大规模实用目标检测模型的微调

### ISSUE THREAD

**Issue by JawerZ** [PaddlePaddle/PaddleDetection#1402]
小白提问，请问我现在的数据集只包含部分类别，是否可以用自定义数据集训练增强部分大规模实用目标检测模型中几个类别的检测效果同时保留对其他类别的检测，以及我用labelme进行标注的话标签是类别的ID还是类别名称？

**Comment by qingqing01** [comment]
1.  对于自己的数据集训练，可以更改类别数，然后选择使用 COCO/Object365/OpenImages的预训练模型作为初始化，即 YML中的`pretrain_weights`更换成大规模实用目标检测模型即可。

2.  labelme进行标注的话标签是类别名称，内部会自动转为id。

**Comment by JawerZ** [comment]
> 1. 对于自己的数据集训练，可以更改类别数，然后选择使用 COCO/Object365/OpenImages的预训练模型作为初始化，即 YML中的`pretrain_weights`更换成大规模实用目标检测模型即可。
> 2. labelme进行标注的话标签是类别名称，x2coco.py的工具会自动转为id。

我现在的数据集只有十几个类别，是否可以在Object365预训练过的模型上继续训练，使其依然拥有能够检测Object365数据集上其他类别的能力但是增强了我现有数据集类别检测能力这样的效果，如果可以的话需要做什么？

**Comment by qingqing01** [comment]
@JawerZ 你实际的使用场景是: Object365的365类+你数据的十几个类别 ？ 还是只有你数据的十几个类别？

如果是前者，你需要将数据和Object365的数据合并，类别数合并，重新finetune训练下。训练出来的模型，两个数据的类别数都包含，但问题是，你的数据是否够，以及你的类别是否和Object365有重复等。
如果是后者，直接用Object365的预训练做初始化，类别数改成你数据集的类别数， 最终的模型，不包含Object365的类别。

总之，需要先明确使用场景和目的。

**Comment by JawerZ** [comment]
> @JawerZ 你实际的使用场景是: Object365的365类+你数据的十几个类别 ？ 还是只有你数据的十几个类别？
> 
> 如果是前者，你需要将数据和Object365的数据合并，类别数合并，重新finetune训练下。训练出来的模型，两个数据的类别数都包含，但问题是，你的数据是否够，以及你的类别是否和Object365有重复等。
> 如果是后者，直接用Object365的预训练做初始化，类别数改成你数据集的类别数， 最终的模型，不包含Object365的类别。
> 
> 总之，需要先明确使用场景和目的。

我数据的十几个类别是包含在Object365的365类中的  目的是希望对我数据的那十几个类别检测的效果做增强  所以依然要跟Object365合并数据后再进行finetune吗

**Comment by JawerZ** [comment]
> @JawerZ 你实际的使用场景是: Object365的365类+你数据的十几个类别 ？ 还是只有你数据的十几个类别？
> 
> 如果是前者，你需要将数据和Object365的数据合并，类别数合并，重新finetune训练下。训练出来的模型，两个数据的类别数都包含，但问题是，你的数据是否够，以及你的类别是否和Object365有重复等。
> 如果是后者，直接用Object365的预训练做初始化，类别数改成你数据集的类别数， 最终的模型，不包含Object365的类别。
> 
> 总之，需要先明确使用场景和目的。

使用场景是 Object365的365个类别

**Comment by qingqing01** [comment]
@JawerZ  也可以不合并，直接加载预训练，先finetune看下效果如何。

**Comment by JawerZ** [comment]
> @JawerZ 也可以不合并，直接加载预训练，先finetune看下效果如何。

aistudio@jupyter-363593-818940:~/work/PaddleDetection-master$ python -u tools/train.py -c configs/rcnn_enhance/generic/cascade_rcnn_dcn_r101_vd_fpn_gen_server_side.yml -o  finetune_exclude_pretrained_params=['cls_score','bbox_pred'] --eval 
2020-09-15 16:49:48,535-WARNING: paddle.fluid.layers.matrix_nms OP not found, maybe a newer version of paddle is required.
2020-09-15 16:49:50,598-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000100] in Optimizer will not take effect, and it will only be applied to other Parameters!
Traceback (most recent call last):
  File "tools/train.py", line 370, in <module>
    main()
  File "tools/train.py", line 144, in main
    fetches = model.eval(feed_vars)
  File "/home/aistudio/work/PaddleDetection-master/ppdet/modeling/architectures/cascade_rcnn.py", line 332, in eval
    return self.build(feed_vars, 'test')
  File "/home/aistudio/work/PaddleDetection-master/ppdet/modeling/architectures/cascade_rcnn.py", line 83, in build
    self._input_check(required_fields, feed_vars)
  File "/home/aistudio/work/PaddleDetection-master/ppdet/modeling/architectures/cascade_rcnn.py", line 259, in _input_check
    "{} has no {} field".format(feed_vars, var)
AssertionError: OrderedDict([('image', name: "image"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 3
      dims: -1
      dims: -1
    }
    lod_level: 0
  }
}
persistable: false
need_check_feed: true
), ('im_info', name: "im_info"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 3
    }
    lod_level: 0
  }
}
persistable: false
need_check_feed: true
), ('im_id', name: "im_id"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: INT64
      dims: -1
      dims: 1
    }
    lod_level: 0
  }
}
persistable: false
need_check_feed: true
), ('gt_bbox', name: "gt_bbox"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: FP32
      dims: -1
      dims: 4
    }
    lod_level: 1
  }
}
persistable: false
need_check_feed: true
), ('gt_class', name: "gt_class"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: INT32
      dims: -1
      dims: 1
    }
    lod_level: 1
  }
}
persistable: false
need_check_feed: true
), ('is_difficult', name: "is_difficult"
type {
  type: LOD_TENSOR
  lod_tensor {
    tensor {
      data_type: INT32
      dims: -1
      dims: 1
    }
    lod_level: 1
  }
}
persistable: false
need_check_feed: true
)]) has no im_shape field

模型训练报错 请问在yml里要怎么设置呢

**Comment by qingqing01** [comment]
@JawerZ  请问你的PaddleDetection是那个分支？ 是0.4 还是 master？ git branch可以看下。

我测试release/0.4分支没问题。如果是master分支的话，可以更新下代码。

**Comment by yinggo** [comment]
@JawerZ 请问解决了吗？
@qingqing01 老师您好，master和release0.4都试了一遍，同样出现“has no im_shape field”的问题，不知道是什么原因……
使用的是cascade_rcnn_dcn_r50_vd_fpn_gen_server_side.yml跑VOC格式数据，参考 自定义数据集教程 修改参数如下：
```
TrainReader:
  inputs_def:
    fields: ['image', 'im_info', 'im_id', 'gt_bbox', 'gt_class', 'is_crowd']
  dataset:
    !VOCDataSet
    #image_dir: train2017
    anno_path: train_city.txt
    dataset_dir: dataset/voc
  sample_transforms:
  - !DecodeImage
    to_rgb: true
  - !RandomFlipImage
    prob: 0.5
  - !AutoAugmentImage
    autoaug_type: v1
  - !NormalizeImage
    is_channel_first: false
    is_scale: true
    mean: [0.485,0.456,0.406]
    std: [0.229, 0.224,0.225]
  - !ResizeImage
    target_size: [640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 960, 992, 1024]
    max_size: 1500
    interp: 1
    use_cv2: true
  - !Permute
    to_bgr: false
    channel_first: true
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
    use_padded_im_info: false
  batch_size: 2
  shuffle: true
  worker_num: 2
  use_process: false

EvalReader:
  inputs_def:
    #fields: ['image', 'im_info', 'im_id', 'im_shape']
    # for voc
    fields: ['image', 'im_info', 'im_id', 'gt_bbox', 'gt_class', 'is_difficult']
  dataset:
    !VOCDataSet
    #image_dir: val2017
    anno_path: val_city.txt
    dataset_dir: dataset/voc
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !NormalizeImage
    is_channel_first: false
    is_scale: true
    mean: [0.485,0.456,0.406]
    std: [0.229, 0.224,0.225]
  - !ResizeImage
    interp: 1
    max_size: 1500
    target_size: 1000
    use_cv2: true
  - !Permute
    channel_first: true
    to_bgr: false
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
    use_padded_im_info: true
  batch_size: 1
  shuffle: false
  drop_empty: false
  worker_num: 2

TestReader:
  inputs_def:
    # set image_shape if needed
    fields: ['image', 'im_info', 'im_id', 'im_shape']
  dataset:
    !ImageFolder
    use_default_label: true
    with_background: true
    anno_path: ./dataset/voc/label_list.txt
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !NormalizeImage
    is_channel_first: false
    is_scale: true
    mean: [0.485,0.456,0.406]
    std: [0.229, 0.224,0.225]
  - !ResizeImage
    interp: 1
    max_size: 1500
    target_size: 1000
    use_cv2: true
  - !Permute
    channel_first: true
    to_bgr: false
  batch_transforms:
  - !PadBatch
    pad_to_stride: 32
    use_padded_im_info: true
  batch_size: 1
  shuffle: false
```
