### ISSUE TITLE
SSD model coredump during saving model

### ISSUE THREAD

**Issue by peerajak** [PaddlePaddle/PaddleDetection#1476]
Hi I just use VOC on ssd, using standard config file  ssd_vgg16_300_voc.yml
After saving the model, it produce error in init.cc file as follow.

I trained VOC with YOLOv3, and it works fine without this following error
-------------------------------------------------------------------------------------------------------------------------------

2020-09-22 14:15:23,490-INFO: iter: 1000, lr: 0.001000, 'loss': '11.070778', time: 0.223, eta: 7:22:16
2020-09-22 14:15:23,511-INFO: Save model to output/ssd_vgg16_300_vocmy/1000.
W0922 14:15:28.514690  4997 init.cc:226] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0922 14:15:28.514734  4997 init.cc:228] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0922 14:15:28.514755  4997 init.cc:231] The detail failure signal is:

W0922 14:15:28.514765  4997 init.cc:234] *** Aborted at 1600758928 (unix time) try "date -d @1600758928" if you are using GNU date ***
W0922 14:15:28.518110  4997 init.cc:234] PC: @                0x0 (unknown)
W0922 14:15:28.519321  4997 init.cc:234] *** SIGSEGV (@0x0) received by PID 4796 (TID 0x7f2d0dfff700) from PID 0; stack trace: ***
W0922 14:15:28.520992  4997 init.cc:234]     @     0x7f2f93acff20 (unknown)
W0922 14:15:28.522526  4997 init.cc:234]     @                0x0 (unknown)
./train_esp32plate.sh: line 3:  4796 Segmentation fault      (core dumped) python -u tools/train.py -c configs/ssd/ssd_vgg16_300_vocmy.yml --use_vdl=True --vdl_log_dir=vdl_vocesp32plate_dir/scalar --eval

**Comment by qingqing01** [comment]
@peerajak 

你可以看下是否需要调小 这里的bufsize: https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.4/configs/ssd/ssd_vgg16_300_voc.yml#L96 

比如调小到4

**Comment by still-wait** [comment]
@peerajak Did this error happen after the training was completed?

**Comment by peerajak** [comment]
@still-wait Not complete. After getting the very first snapshort:1000th iter
architecture: SSD
use_gpu: true
max_iters: 120001
snapshot_iter: 1000

**Comment by peerajak** [comment]
I am guessing
during eval, 
batch_size 32

I am changing to 8

```

architecture: SSD
use_gpu: true
max_iters: 120001
snapshot_iter: 100
log_smooth_window: 20
log_iter: 20
metric: VOC
map_type: 11point
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/VGG16_caffe_pretrained.tar
save_dir: output
weights: output/ssd_vgg16_300_voc/model_final
# 20(label_class) + 1(background)
num_classes: 21

SSD:
  backbone: VGG
  multi_box_head: MultiBoxHead
  output_decoder:
    background_label: 0
    keep_top_k: 200
    nms_eta: 1.0
    nms_threshold: 0.45
    nms_top_k: 400
    score_threshold: 0.01

VGG:
  depth: 16
  with_extra_blocks: true
  normalizations: [20., -1, -1, -1, -1, -1]

MultiBoxHead:
  base_size: 300
  aspect_ratios: [[2.], [2., 3.], [2., 3.], [2., 3.], [2.], [2.]]
  min_ratio: 20
  max_ratio: 90
  min_sizes: [30.0, 60.0, 111.0, 162.0, 213.0, 264.0]
  max_sizes: [60.0, 111.0, 162.0, 213.0, 264.0, 315.0]
  steps: [8, 16, 32, 64, 100, 300]
  offset: 0.5
  flip: true
  min_max_aspect_ratios_order: true
  kernel_size: 3
  pad: 1

LearningRate:
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [80000, 100000]

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

TrainReader:
  inputs_def:
    image_shape: [3, 300, 300]
    fields: ['image', 'gt_bbox', 'gt_class']
  dataset:
    !VOCDataSet
    dataset_dir: dataset/voc
    anno_path: trainval.txt
    use_default_label: true
  sample_transforms:
  - !DecodeImage
    to_rgb: true
  - !RandomDistort
    brightness_lower: 0.875
    brightness_upper: 1.125
    is_order: true
  - !RandomExpand
    fill_value: [104, 117, 123]
  - !RandomCrop
    allow_no_crop: true
  - !NormalizeBox {}
  - !ResizeImage
    interp: 1
    target_size: 300
    use_cv2: false
  - !RandomFlipImage
    is_normalized: true
  - !Permute
    to_bgr: false
  - !NormalizeImage
    is_scale: false
    mean: [104, 117, 123]
    std: [1, 1, 1]
  batch_size: 8
  shuffle: true
  worker_num: 8
  bufsize: 4
  use_process: true

EvalReader:
  inputs_def:
    image_shape: [3, 300, 300]
    fields: ['image', 'gt_bbox', 'gt_class', 'im_shape', 'im_id', 'is_difficult']
  dataset:
    !VOCDataSet
    anno_path: test.txt
    dataset_dir: dataset/voc
    use_default_label: true
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !NormalizeBox {}
  - !ResizeImage
    interp: 1
    target_size: 300
    use_cv2: false
  - !Permute
    to_bgr: false
  - !NormalizeImage
    is_scale: false
    mean: [104, 117, 123]
    std: [1, 1, 1]
  batch_size: 8
  worker_num: 8
  bufsize: 4

TestReader:
  inputs_def:
    image_shape: [3,300,300]
    fields: ['image', 'im_id', 'im_shape']
  dataset:
    !ImageFolder
    anno_path: test.txt
    use_default_label: true
  sample_transforms:
  - !DecodeImage
    to_rgb: true
    with_mixup: false
  - !ResizeImage
    interp: 1
    max_size: 0
    target_size: 300
    use_cv2: false
  - !Permute
    to_bgr: false
  - !NormalizeImage
    is_scale: false
    mean: [104, 117, 123]
    std: [1, 1, 1]
  batch_size: 1
```
