### ISSUE TITLE
SSDLiteMultiBoxHead 疑问

### ISSUE THREAD

**Issue by qingyuemeng** [PaddlePaddle/PaddleDetection#1684]
请问SSDLiteMultiBoxHead中steps设置是什么含义呢？
```
SSDLiteMultiBoxHead:
  aspect_ratios: [[2.], [2., 3.], [2., 3.], [2., 3.], [2., 3.], [2., 3.]]
  base_size: 320
  steps: [16, 32, 64, 107, 160, 320]
  flip: true
  clip: true
  max_ratio: 95
  min_ratio: 20
  offset: 0.5
  conv_decay: 0.00004
```
