### ISSUE TITLE
ppyolo预测出错

### ISSUE THREAD

**Issue by ybxbupt** [PaddlePaddle/PaddleDetection#1786]
出错信息：

```
2020-11-30 15:54:21,448-INFO: Load categories from dataset/cocome\annotations/instance_test.json
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
2020-11-30 15:54:21,786-INFO: Infer iter 0
Traceback (most recent call last):
  File "H:/yuanbaoxi/test_code/paddlepaddle-PaddleDetection-master/PaddleDetection/QR_ppyolo_infer.py", line 280, in <module>
    main()
  File "H:/yuanbaoxi/test_code/paddlepaddle-PaddleDetection-master/PaddleDetection/QR_ppyolo_infer.py", line 194, in main
    bbox_results = bbox2out([res], clsid2catid, is_bbox_normalized)
  File "H:\yuanbaoxi\test_code\paddlepaddle-PaddleDetection-master\PaddleDetection\ppdet\utils\coco_eval.py", line 315, in bbox2out
    catid = (clsid2catid[int(clsid)])
KeyError: 1
W1130 15:54:18.086191 38532 device_context.cc:338] Please NOTE: device: 0, CUDA Capability: 61, Driver API Version: 11.0, Runtime API Version: 10.2
W1130 15:54:18.122315 38532 device_context.cc:346] device: 0, cuDNN Version: 7.6.
```

参数配置
```
    parser.add_argument("-c", "--config", default="configs/ppyolo/ppyolo_QR.yml",
                      help="configuration file to use")
    parser.add_argument("-o", "--opt", nargs='*', help="set configuration options")
    parser.add_argument(
        "--infer_dir",
        type=str,
        default=r".\dataset\cocome\test",
        help="Directory for images to perform inference on.")
```

使用的yml文件如下：
```
architecture: YOLOv3
use_gpu: true
max_iters: 1000
log_iter: 100
save_dir: output
snapshot_iter: 100
metric: COCO
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_vd_ssld_pretrained.tar
weights: output/ppyolo_QR/model_final
num_classes: 2
use_fine_grained_loss: true
use_ema: true
ema_decay: 0.9998

YOLOv3:
  backbone: ResNet
  yolo_head: YOLOv3Head
  use_fine_grained_loss: true

ResNet:
  norm_type: sync_bn
  freeze_at: 0
  freeze_norm: false
  norm_decay: 0.
  depth: 50
  feature_maps: [3, 4, 5]
  variant: d
  dcn_v2_stages: [5]

YOLOv3Head:
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  anchors: [[10, 13], [16, 30], [33, 23],
            [30, 61], [62, 45], [59, 119],
            [116, 90], [156, 198], [373, 326]]
  norm_decay: 0.
  coord_conv: true
  iou_aware: true
  iou_aware_factor: 0.4
  scale_x_y: 1.05
  spp: true
  yolo_loss: YOLOv3Loss
  nms: MatrixNMS
  drop_block: true

YOLOv3Loss:
  ignore_thresh: 0.7
  scale_x_y: 1.05
  label_smooth: false
  use_fine_grained_loss: true
  iou_loss: IouLoss
  iou_aware_loss: IouAwareLoss

IouLoss:
  loss_weight: 2.5
  max_height: 608
  max_width: 608

IouAwareLoss:
  loss_weight: 1.0
  max_height: 608
  max_width: 608

MatrixNMS:
    background_label: -1
    keep_top_k: 100
    normalized: false
    score_threshold: 0.01
    post_threshold: 0.01

LearningRate:
  base_lr: 0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 150000
    - 200000
  - !LinearWarmup
    start_factor: 0.
    steps: 4000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

TrainReader:
  inputs_def:
    fields: ['image', 'gt_bbox', 'gt_class', 'gt_score']
    num_max_boxes: 50
  dataset:
    !COCODataSet
      image_dir: train
      anno_path: annotations\instance_train.json
      dataset_dir: dataset\cocome
      with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
      with_mixup: True
    - !MixupImage
      alpha: 1.5
      beta: 1.5
    - !ColorDistort {}
    - !RandomExpand
      ratio: 2.0
      fill_value: [123.675, 116.28, 103.53]
    - !RandomCrop {}
    - !RandomFlipImage
      is_normalized: false
    - !NormalizeBox {}
    - !PadBox
      num_max_boxes: 50
    - !BboxXYXY2XYWH {}
  batch_transforms:
  - !RandomShape
    sizes: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608]
    random_inter: True
  - !NormalizeImage
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    is_scale: True
    is_channel_first: false
  - !Permute
    to_bgr: false
    channel_first: True
  # Gt2YoloTarget is only used when use_fine_grained_loss set as true,
  # this operator will be deleted automatically if use_fine_grained_loss
  # is set as false
  - !Gt2YoloTarget
    anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
    anchors: [[10, 13], [16, 30], [33, 23],
              [30, 61], [62, 45], [59, 119],
              [116, 90], [156, 198], [373, 326]]
    downsample_ratios: [32, 16, 8]
  batch_size: 6
  shuffle: true
  mixup_epoch: 25000
  drop_last: true
  worker_num: 4
  bufsize: 4
  use_process: true

EvalReader:
  inputs_def:
    fields: ['image', 'im_size', 'im_id']
    num_max_boxes: 50
  dataset:
    !COCODataSet
      image_dir: val
      anno_path: annotations\instance_val.json
      dataset_dir: dataset\cocome
      with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
    - !ResizeImage
      target_size: 608
      interp: 2
    - !NormalizeImage
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_scale: True
      is_channel_first: false
    - !PadBox
      num_max_boxes: 50
    - !Permute
      to_bgr: false
      channel_first: True
  batch_size: 4
  drop_empty: false
  worker_num: 4
  bufsize: 4

TestReader:
  inputs_def:
    image_shape: [3, 608, 608]
    fields: ['image', 'im_size', 'im_id']
  dataset:
    !ImageFolder
      image_dir: test
      anno_path: annotations\instance_test.json
      dataset_dir: dataset\cocome
      with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
    - !ResizeImage
      target_size: 608
      interp: 2
    - !NormalizeImage
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_scale: True
      is_channel_first: false
    - !Permute
      to_bgr: false
      channel_first: True
  batch_size: 1
```
