### ISSUE TITLE
向大佬提两个问题

### ISSUE THREAD

**Issue by liboshi33** [PaddlePaddle/PaddleDetection#1803]
第一个如果我的模型误报比较固定的一类，但是我一般我训练的时候在我有误报的这种图里没有我要训练的目标，我可不可以把这个存成空的xml，这样可不可以减少这样的误报，让模型认识这个。
第二个我把yml的优化器改成了adam，loss直接飞了，请问我要想改别的优化器的时候还需要别的什么操作。

**Comment by yghstill** [comment]
@liboshi33 
1.YOLO系列模型支持输入GT为空，RCNN算法不支持输入GT为空，可以多标注一个背景类参与训练，也可以学习到这种图片里的特征。
2.adam可能在训练起始阶段不稳定，可尝试将warm up轮数调大， start_factor调成0
```yaml
- !LinearWarmup
    start_factor: 0.
    steps: 100
```
