### ISSUE TITLE
paddleDetection写的文档看不明白

### ISSUE THREAD

**Issue by haixuan-2004** [PaddlePaddle/PaddleDetection#1991]
我参照了手册一步步去做YOLOV3的目标检测，训练了一个基本模型，但是用这个模型去预测时，发现预测的目标位置是正确的，但是目标的标签名称不对，全yml的文件中没有说明用哪些参数来设定自定义的标签名，麻烦看看要怎么设定自已的标签名。

**Comment by yghstill** [comment]
- coco数据集：
```yaml
TestReader:
  ...
  dataset:
    !ImageFolder
      dataset_dir: dataset/coco
      anno_path: annotations/instances_val2017.json
      with_background: false
```
设置dataset_dir和anno_path即可
- voc数据集：
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-beta/configs/yolov3_r34_voc.yml#L88
```yaml
TestReader:
  dataset:
    !ImageFolder
    use_default_label: false
```
use_default_label设置false，然后替换label_list.txt文件即可：https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-beta/dataset/voc/label_list.txt
