### ISSUE TITLE
VOC数据集如何设置自定义标签

### ISSUE THREAD

**Issue by haixuan-2004** [PaddlePaddle/PaddleDetection#1998]
训练时显示的精度有73%，但是预测时，用训练过来的图片来预测，精度远远达不到73%呢？

另外，我参照配置文件进行训练与预测，但是预测时，VOC预测的标签名不对，需要如何调整配置文件：

```
architecture: YOLOv3
use_gpu: true
max_iters: 70000
log_iter: 3
save_dir: output
snapshot_iter: 200
metric: VOC
map_type: 11point
pretrain_weights: http://paddle-imagenet-models-name.bj.bcebos.com/MobileNetV1_pretrained.tar
weights: output/yolov3_mobilenet_v1_voc_light/model_final
num_classes: 4
use_fine_grained_loss: false

YOLOv3:
  backbone: MobileNet
  yolo_head: YOLOv3Head

MobileNet:
  norm_type: sync_bn
  norm_decay: 0.
  conv_group_scale: 1
  with_extra_blocks: false

YOLOv3Head:
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  anchors: [[10, 13], [16, 30], [33, 23],
            [30, 61], [62, 45], [59, 119],
            [116, 90], [156, 198], [373, 326]]
  norm_decay: 0.
  yolo_loss: YOLOv3Loss
  nms:
    background_label: -1
    keep_top_k: 100
    nms_threshold: 0.45
    nms_top_k: 1000
    normalized: false
    score_threshold: 0.01

YOLOv3Loss:
  ignore_thresh: 0.7
  label_smooth: false

LearningRate:
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 55000
    - 62000
  - !LinearWarmup
    start_factor: 0.
    steps: 1000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

_READER_: 'yolov3_reader.yml'
TrainReader:
  dataset:
    !VOCDataSet
    dataset_dir: dataset/light_voc
    anno_path: trans_voc.txt
    use_default_label: false
    with_background: false

EvalReader:
  inputs_def:
    fields: ['image', 'im_size', 'im_id', 'gt_bbox', 'gt_class', 'is_difficult']
    num_max_boxes: 50
  dataset:
    !VOCDataSet
    dataset_dir: dataset/light_voc
    anno_path: valad_voc.txt
    use_default_label: false
    with_background: false


TestReader:
  dataset:
    !ImageFolder
    use_default_label: false
    with_background: false
```
