### ISSUE TITLE
faster_rcnn_r34_fpn_1x 训练用的配置文件如何配置

### ISSUE THREAD

**Issue by haixuan-2004** [PaddlePaddle/PaddleDetection#2076]
我的配置文件如下：

```
architecture: FasterRCNN
max_iters: 90000
use_gpu: true
snapshot_iter: 100
log_iter: 20
save_dir: output
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNet34_vd_pretrained.tar
metric: COCO
weights: output/faster_rcnn_r34_fpn_1x/model_final
num_classes: 42

FasterRCNN:
  backbone: ResNet
  fpn: FPN
  rpn_head: FPNRPNHead
  roi_extractor: FPNRoIAlign
  bbox_head: BBoxHead
  bbox_assigner: BBoxAssigner

ResNet:
  norm_type: bn
  norm_decay: 0.
  depth: 34
  feature_maps: [2, 3, 4, 5]
  freeze_at: 2
  variant: d

FPN:
  min_level: 2
  max_level: 6
  num_chan: 256
  spatial_scale: [0.03125, 0.0625, 0.125, 0.25]

FPNRPNHead:
  anchor_generator:
    anchor_sizes: [32, 64, 128, 256, 512]
    aspect_ratios: [0.5, 1.0, 2.0]
    stride: [16.0, 16.0]
    variance: [1.0, 1.0, 1.0, 1.0]
  anchor_start_size: 32
  min_level: 2
  max_level: 6
  num_chan: 256
  rpn_target_assign:
    rpn_batch_size_per_im: 256
    rpn_fg_fraction: 0.5
    rpn_positive_overlap: 0.7
    rpn_negative_overlap: 0.3
    rpn_straddle_thresh: 0.0
  train_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 2000
    post_nms_top_n: 2000
  test_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 1000
    post_nms_top_n: 1000

FPNRoIAlign:
  canconical_level: 4
  canonical_size: 224
  min_level: 2
  max_level: 5
  box_resolution: 7
  sampling_ratio: 2

BBoxAssigner:
  batch_size_per_im: 512
  bbox_reg_weights: [0.1, 0.1, 0.2, 0.2]
  bg_thresh_lo: 0.0
  bg_thresh_hi: 0.5
  fg_fraction: 0.25
  fg_thresh: 0.5

BBoxHead:
  head: TwoFCHead
  nms:
    keep_top_k: 100
    nms_threshold: 0.5
    score_threshold: 0.05

TwoFCHead:
  mlp_dim: 1024

LearningRate:
  base_lr: 0.02
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [60000, 80000]
  - !LinearWarmup
    start_factor: 0.1
    steps: 1000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0001
    type: L2

_READER_: 'faster_fpn_reader.yml'
TrainReader:
  batch_size: 1

#####################################\u6570\u636E\u914D\u7F6E#####################################

# \u6A21\u578B\u8BAD\u7EC3\u96C6\u8BBE\u7F6E\u53C2\u8003
# \u8BAD\u7EC3\u3001\u9A8C\u8BC1\u3001\u6D4B\u8BD5\u4F7F\u7528\u7684\u6570\u636E\u914D\u7F6E\u4E3B\u8981\u533A\u522B\u5728\u6570\u636E\u8DEF\u5F84\u3001\u6A21\u578B\u8F93\u5165\u3001\u6570\u636E\u589E\u5F3A\u53C2\u6570\u8BBE\u7F6E
# \u5982\u679C\u4F7F\u7528 yolov3_reader.yml\uFF0C\u4E0B\u9762\u7684\u53C2\u6570\u8BBE\u7F6E\u4F18\u5148\u7EA7\u9AD8\uFF0C\u4F1A\u8986\u76D6yolov3_reader.yml\u4E2D\u7684\u53C2\u6570\u8BBE\u7F6E\u3002
# _READER_: 'yolov3_reader.yml'

TrainReader:
  # \u8BAD\u7EC3\u8FC7\u7A0B\u4E2D\u6A21\u578B\u7684\u8F93\u5165\u8BBE\u7F6E
  # \u5305\u62EC\u56FE\u7247\uFF0C\u56FE\u7247\u957F\u5BBD\u9AD8\u7B49\u57FA\u672C\u4FE1\u606F\uFF0C\u56FE\u7247id\uFF0C\u6807\u8BB0\u7684\u76EE\u6807\u6846\uFF0C\u7C7B\u522B\u7B49\u4FE1\u606F,, 'gt_score'
  inputs_def:
    fields: ['image', 'im_info', 'im_id', 'gt_bbox', 'gt_class', 'is_crowd']
  # \u8BAD\u7EC3\u6570\u636E\u96C6\u8DEF\u5F84
  dataset:
    # \u6307\u5B9A\u6570\u636E\u96C6\u683C\u5F0F
    !COCODataSet
      # \u56FE\u7247\u6587\u4EF6\u5939\u76F8\u5BF9\u8DEF\u5F84\uFF0C\u8DEF\u5F84\u662F\u76F8\u5BF9\u4E8Edataset_dir\uFF0C\u56FE\u50CF\u8DEF\u5F84= dataset_dir + image_dir + image_name
      image_dir: images
      # anno_path\uFF0C\u8DEF\u5F84\u662F\u76F8\u5BF9\u4E8Edataset_dir
      anno_path: annotations/coco_label.json
      # \u6570\u636E\u96C6\u76F8\u5BF9\u8DEF\u5F84\uFF0C\u8DEF\u5F84\u662F\u76F8\u5BF9\u4E8EPaddleDetection
      dataset_dir: dataset/light_coco_gd
      # \u662F\u5426\u5305\u542B\u80CC\u666F\u7C7B\uFF0C\u82E5with_background=true\uFF0Cnum_classes\u9700\u8981+1
      # YOLO \u7CFB\u5217with_background\u5FC5\u987B\u662Ffalse\uFF0CFasterRCNN\u7CFB\u5217\u662Ftrue ###
      with_background: true
  sample_transforms:
    # \u8BFB\u53D6Image\u56FE\u50CF\u4E3Anumpy\u6570\u7EC4
    # \u53EF\u4EE5\u9009\u62E9\u5C06\u56FE\u7247\u4ECEBGR\u8F6C\u5230RGB\uFF0C\u53EF\u4EE5\u9009\u62E9\u5BF9\u4E00\u4E2Abatch\u4E2D\u7684\u56FE\u7247\u505Amixup\u589E\u5F3A
    - !DecodeImage
      to_rgb: True
      with_mixup: True
    # MixupImage
    - !MixupImage
      alpha: 1.5
      beta: 1.5
    # ColorDistort
    - !ColorDistort {}
    # RandomExpand
    - !RandomExpand
      fill_value: [123.675, 116.28, 103.53]
      # \u968F\u673A\u6269\u5145\u6BD4\u4F8B\uFF0C\u9ED8\u8BA4\u503C\u662F4.0
      ratio: 1.5
    - !RandomCrop {}
    - !RandomFlipImage
      is_normalized: false
     # \u5F52\u4E00\u5316\u5750\u6807
    - !NormalizeBox {}
    # \u5982\u679C bboxes \u6570\u91CF\u5C0F\u4E8E num_max_boxes\uFF0C\u586B\u5145\u503C\u4E3A0\u7684 box
    - !PadBox
      num_max_boxes: 50
    # \u5750\u6807\u683C\u5F0F\u8F6C\u5316\uFF0C\u4ECEXYXY\u8F6C\u6210XYWH\u683C\u5F0F
    - !BboxXYXY2XYWH {}
  # \u4EE5\u4E0B\u662F\u5BF9\u4E00\u4E2Abatch\u4E2D\u7684\u6240\u6709\u56FE\u7247\u540C\u65F6\u505A\u7684\u6570\u636E\u5904\u7406
  batch_transforms:
  # \u591A\u5C3A\u5EA6\u8BAD\u7EC3\u65F6\uFF0C\u4ECElist\u4E2D\u968F\u673A\u9009\u62E9\u4E00\u4E2A\u5C3A\u5BF8\uFF0C\u5BF9\u4E00\u4E2Abatch\u6570\u636E\u540C\u65F6\u540C\u65F6resize
  - !RandomShape
    sizes: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608]
    random_inter: True
  # NormalizeImage
  - !NormalizeImage
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    is_scale: True
    is_channel_first: false
  - !Permute
    to_bgr: false
    channel_first: True
  # Gt2YoloTarget is only used when use_fine_grained_loss set as true,
  # this operator will be deleted automatically if use_fine_grained_loss
  # is set as false
  - !Gt2YoloTarget
    anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
    anchors: [[10, 13], [16, 30], [33, 23],
              [30, 61], [62, 45], [59, 119],
              [116, 90], [156, 198], [373, 326]]
    downsample_ratios: [32, 16, 8]
  # 1\u4E2AGPU\u7684batch size\uFF0C\u9ED8\u8BA4\u4E3A1\u3002\u9700\u8981\u6CE8\u610F\uFF1A\u6BCF\u4E2Aiter\u8FED\u4EE3\u4F1A\u8FD0\u884Cbatch_size * device_num\u5F20\u56FE\u7247
  batch_size: 8
  # \u662F\u5426shuffle
  shuffle: true
  # mixup\uFF0C-1\u8868\u793A\u4E0D\u505AMixup\u6570\u636E\u589E\u5F3A\u3002\u6CE8\u610F\uFF0C\u8FD9\u91CC\u662Fepoch\u4E3A\u5355\u4F4D
  mixup_epoch: 250
  # \u6CE8\u610F\uFF0C\u5728\u67D0\u4E9B\u60C5\u51B5\u4E0B\uFF0Cdrop_last=false\u65F6\u8BAD\u7EC3\u8FC7\u7A0B\u4E2D\u53EF\u80FD\u4F1A\u51FA\u9519\uFF0C\u5EFA\u8BAE\u8BAD\u7EC3\u65F6\u90FD\u8BBE\u7F6E\u4E3Atrue
  drop_last: true
  # \u82E5\u9009\u7528\u591A\u8FDB\u7A0B\uFF0C\u8BBE\u7F6E\u4F7F\u7528\u591A\u8FDB\u7A0B/\u7EBF\u7A0B\u7684\u6570\u76EE
  # \u5F00\u542F\u591A\u8FDB\u7A0B\u540E\uFF0C\u5360\u7528\u5185\u5B58\u4F1A\u6210\u500D\u589E\u52A0\uFF0C\u6839\u636E\u5185\u5B58\u8BBE\u7F6E###
  worker_num: 8
  # \u5171\u4EAB\u5185\u5B58bufsize\u3002\u6CE8\u610F\uFF0C\u7F13\u5B58\u662F\u4EE5batch\u4E3A\u5355\u4F4D\uFF0C\u7F13\u5B58\u7684\u6837\u672C\u6570\u636E\u603B\u91CF\u4E3Abatch_size * bufsize\uFF0C\u6240\u4EE5\u8BF7\u6CE8\u610F\u4E0D\u8981\u8BBE\u7F6E\u592A\u5927\uFF0C\u8BF7\u6839\u636E\u60A8\u7684\u786C\u4EF6\u8BBE\u7F6E\u3002
  bufsize: 16
  # \u662F\u5426\u4F7F\u7528\u591A\u8FDB\u7A0B
  use_process: true


EvalReader:
  # \u8BC4\u4F30\u8FC7\u7A0B\u4E2D\u6A21\u578B\u7684\u8F93\u5165\u8BBE\u7F6E
  # \u5305\u62EC\u56FE\u7247\uFF0C\u56FE\u7247\u957F\u5BBD\u9AD8\u7B49\u57FA\u672C\u4FE1\u606F\uFF0C\u56FE\u7247id\uFF0C\u6807\u8BB0\u7684\u76EE\u6807\u6846\uFF0C\u7C7B\u522B\u7B49\u4FE1\u606F
  inputs_def:
    fields: ['image', 'im_size', 'im_id']
    # num_max_boxes\uFF0C\u6BCF\u4E2A\u6837\u672C\u7684groud truth\u7684\u6700\u591A\u4FDD\u7559\u4E2A\u6570\uFF0C\u82E5\u4E0D\u591F\u75280\u586B\u5145\u3002
    num_max_boxes: 50
  # \u6570\u636E\u96C6\u8DEF\u5F84
  dataset:
    !COCODataSet
      # \u56FE\u7247\u6587\u4EF6\u5939\u76F8\u5BF9\u8DEF\u5F84\uFF0C\u8DEF\u5F84\u662F\u76F8\u5BF9\u4E8Edataset_dir\uFF0C\u56FE\u50CF\u8DEF\u5F84= dataset_dir + image_dir + image_name
      image_dir: images
      # anno_path\uFF0C\u8DEF\u5F84\u662F\u76F8\u5BF9\u4E8Edataset_dir
      anno_path: annotations/eval.json
      # \u6570\u636E\u96C6\u76F8\u5BF9\u8DEF\u5F84\uFF0C\u8DEF\u5F84\u662F\u76F8\u5BF9\u4E8EPaddleDetection
      dataset_dir: dataset/light_coco_gd
      # \u662F\u5426\u5305\u542B\u80CC\u666F\u7C7B\uFF0C\u82E5with_background=true\uFF0Cnum_classes\u9700\u8981+1
      # YOLO \u7CFB\u5217with_background\u5FC5\u987B\u662Ffalse\uFF0CFasterRCNN\u7CFB\u5217\u662Ftrue ###
      with_background: true
  sample_transforms:
    # \u8BFB\u53D6Image\u56FE\u50CF\u4E3Anumpy\u6570\u7EC4
    # \u53EF\u4EE5\u9009\u62E9\u5C06\u56FE\u7247\u4ECEBGR\u8F6C\u5230RGB\uFF0C\u53EF\u4EE5\u9009\u62E9\u5BF9\u4E00\u4E2Abatch\u4E2D\u7684\u56FE\u7247\u505Amixup\u589E\u5F3A
    - !DecodeImage
      to_rgb: True
    # ResizeImage
    - !ResizeImage
      target_size: 608
      interp: 2
    # NormalizeImage
    - !NormalizeImage
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_scale: True
      is_channel_first: false
    # \u5982\u679C bboxes \u6570\u91CF\u5C0F\u4E8E num_max_boxes\uFF0C\u586B\u5145\u503C\u4E3A0\u7684 box
    - !PadBox
      num_max_boxes: 50
    - !Permute
      to_bgr: false
      channel_first: True
  # 1\u4E2AGPU\u7684batch size\uFF0C\u9ED8\u8BA4\u4E3A1\u3002\u9700\u8981\u6CE8\u610F\uFF1A\u6BCF\u4E2Aiter\u8FED\u4EE3\u4F1A\u8FD0\u884Cbatch_size * device_num\u5F20\u56FE\u7247
  batch_size: 8
  # drop_empty
  drop_empty: false
  # \u82E5\u9009\u7528\u591A\u8FDB\u7A0B\uFF0C\u8BBE\u7F6E\u4F7F\u7528\u591A\u8FDB\u7A0B/\u7EBF\u7A0B\u7684\u6570\u76EE
  # \u5F00\u542F\u591A\u8FDB\u7A0B\u540E\uFF0C\u5360\u7528\u5185\u5B58\u4F1A\u6210\u500D\u589E\u52A0\uFF0C\u6839\u636E\u5185\u5B58\u8BBE\u7F6E###
  worker_num: 8
  # \u5171\u4EAB\u5185\u5B58bufsize\u3002\u6CE8\u610F\uFF0C\u7F13\u5B58\u662F\u4EE5batch\u4E3A\u5355\u4F4D\uFF0C\u7F13\u5B58\u7684\u6837\u672C\u6570\u636E\u603B\u91CF\u4E3Abatch_size * bufsize\uFF0C\u6240\u4EE5\u8BF7\u6CE8\u610F\u4E0D\u8981\u8BBE\u7F6E\u592A\u5927\uFF0C\u8BF7\u6839\u636E\u60A8\u7684\u786C\u4EF6\u8BBE\u7F6E\u3002
  bufsize: 16

TestReader:
  # \u9884\u6D4B\u8FC7\u7A0B\u4E2D\u6A21\u578B\u7684\u8F93\u5165\u8BBE\u7F6E
  # \u5305\u62EC\u56FE\u7247\uFF0C\u56FE\u7247\u957F\u5BBD\u9AD8\u7B49\u57FA\u672C\u4FE1\u606F\uFF0C\u56FE\u7247id\uFF0C\u6807\u8BB0\u7684\u76EE\u6807\u6846\uFF0C\u7C7B\u522B\u7B49\u4FE1\u606F
  inputs_def:
    # \u9884\u6D4B\u56FE\u50CF\u8F93\u5165\u5C3A\u5BF8
    image_shape: [3, 608, 608]
    fields: ['image', 'im_size', 'im_id']
  # \u6570\u636E\u96C6\u8DEF\u5F84
  dataset:
    !ImageFolder
      # anno_path\uFF0C\u8DEF\u5F84\u662F\u76F8\u5BF9\u4E8Edataset_dir
      anno_path: annotations/eval.json
      # \u662F\u5426\u5305\u542B\u80CC\u666F\u7C7B\uFF0C\u82E5with_background=true\uFF0Cnum_classes\u9700\u8981+1
      # YOLO \u7CFB\u5217with_background\u5FC5\u987B\u662Ffalse\uFF0CFasterRCNN\u7CFB\u5217\u662Ftrue ###
      with_background: true
  sample_transforms:
    - !DecodeImage
      to_rgb: True
    # ResizeImage
    - !ResizeImage
      target_size: 608
      interp: 2
    # NormalizeImage
    - !NormalizeImage
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_scale: True
      is_channel_first: false
    # Permute
    - !Permute
      to_bgr: false
      channel_first: True
  # 1\u4E2AGPU\u7684batch size\uFF0C\u9ED8\u8BA4\u4E3A1
  batch_size: 1
```

上述文件在执行时报错，想了解下是哪里配置错了吗，我的系统是Ubuntu,GPU环境。
```
loading annotations into memory...
Traceback (most recent call last):
  File "tools/train.py", line 399, in <module>
    main()
  File "tools/train.py", line 228, in main
    train_reader = create_reader(
  File "/root/chenhx/PaddleDetection/ppdet/data/reader.py", line 442, in create_reader
    reader = Reader(**cfg)()
  File "/root/chenhx/PaddleDetection/ppdet/data/reader.py", line 210, in __init__
    self._roidbs = self._dataset.get_roidb()
  File "/root/chenhx/PaddleDetection/ppdet/data/source/dataset.py", line 68, in get_roidb
    self.load_roidb_and_cname2cid()
  File "/root/chenhx/PaddleDetection/ppdet/data/source/coco.py", line 81, in load_roidb_and_cname2cid
    coco = COCO(anno_path)
  File "/root/anaconda3/envs/paddle_env/lib/python3.8/site-packages/pycocotools/coco.py", line 85, in __init__
    dataset = json.load(f)
  File "/root/anaconda3/envs/paddle_env/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/root/anaconda3/envs/paddle_env/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/root/anaconda3/envs/paddle_env/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/root/anaconda3/envs/paddle_env/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
