### ISSUE TITLE
PPyolo训练速度慢，请大佬们帮忙看看是什么问题。

### ISSUE THREAD

**Issue by Jorsen0** [PaddlePaddle/PaddleDetection#2090]
训练PPYOLO时，GPU使用长时间为0，经常GPU沉寂十几秒，活跃一两秒，修改work_num也没明显改善，请大佬们帮忙看看是什么问题。

# 配置文件如下：
```
architecture: YOLOv3
use_gpu: true
max_iters: 50000
log_smooth_window: 100
log_iter: 100
save_dir: output
snapshot_iter: 1000
metric: VOC
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/MobileNetV3_large_x1_0_ssld_pretrained.tar
weights: output/ppyolo_voc/best_model
num_classes: 19
use_fine_grained_loss: true
use_ema: true
ema_decay: 0.9998

YOLOv3:
  backbone: MobileNetV3
  yolo_head: YOLOv3Head
  use_fine_grained_loss: true

MobileNetV3:
  norm_type: sync_bn
  norm_decay: 0.
  model_name: large
  scale: 1.
  extra_block_filters: []
  feature_maps: [1, 2, 3, 4, 6]


YOLOv3Head:
  anchor_masks: [[3, 4, 5], [0, 1, 2]]
  anchors: [[18, 20], [28, 19], [82, 8],
            [30, 35], [44, 45], [94, 63]]
  norm_decay: 0.
  conv_block_num: 0
  coord_conv: true
  scale_x_y: 1.05
  yolo_loss: YOLOv3Loss
  spp: true
  nms:
    background_label: -1
    keep_top_k: 100
    nms_threshold: 0.45
    nms_top_k: 1000
    normalized: false
    score_threshold: 0.005
  drop_block: true

YOLOv3Loss:
  ignore_thresh: 0.5
  scale_x_y: 1.05
  label_smooth: false
  use_fine_grained_loss: true
  iou_loss: IouLoss

IouLoss:
  loss_weight: 2.5
  max_height: 512
  max_width: 512

LearningRate:
  base_lr: 0.005
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 35000
    - 40000
    - 45000
  - !LinearWarmup
    start_factor: 0.
    steps: 4000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

#_READER_: 'ppyolo_reader.yml'

TrainReader:
  inputs_def:
    fields: ['image', 'gt_bbox', 'gt_class', 'gt_score']
    num_max_boxes: 50
  dataset:
    !VOCDataSet
    dataset_dir: dataset/ppyolo_voc
    anno_path: trainval.txt
    use_default_label: false
    with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
      with_mixup: True
    - !MixupImage
      alpha: 1.5
      beta: 1.5
    - !ColorDistort {}
    - !RandomExpand
      fill_value: [123.675, 116.28, 103.53]
    - !RandomCrop {}
    - !RandomFlipImage
      is_normalized: false
    - !NormalizeBox {}
    - !PadBox
      num_max_boxes: 50
    - !BboxXYXY2XYWH {}
  batch_transforms:
  - !RandomShape
    sizes: [224, 256, 288, 320, 352, 384, 416, 448, 480, 512]
    random_inter: True
  - !NormalizeImage
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    is_scale: True
    is_channel_first: false
  - !Permute
    to_bgr: false
    channel_first: True

  - !Gt2YoloTarget
    anchor_masks: [[3, 4, 5], [0, 1, 2]]
    anchors: [[18, 20], [28, 19], [82, 8],
              [30, 35], [44, 45], [94, 63]]
    downsample_ratios: [32, 16]
    iou_thresh: 0.25
    num_classes: 19
  batch_size: 32
  shuffle: true
  mixup_epoch: 100000
  drop_last: true
  worker_num: 16
  bufsize: 16
  use_process: true

EvalReader:
  inputs_def:
    fields: ['image', 'im_size', 'im_id', 'gt_bbox', 'gt_class', 'is_difficult']
    num_max_boxes: 50
  dataset:
    !VOCDataSet
    dataset_dir: dataset/ppyolo_voc
    anno_path: test.txt
    use_default_label: false
    with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
    - !ResizeImage
      target_size: 320
      interp: 2
    - !NormalizeImage
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_scale: True
      is_channel_first: false
    - !PadBox
      num_max_boxes: 50
    - !Permute
      to_bgr: false
      channel_first: True
  batch_size: 8
  drop_empty: false
  worker_num: 16
  bufsize: 8

TestReader:
  inputs_def:
    image_shape: [3, 320, 320]
    fields: ['image', 'im_size', 'im_id']
  dataset:
    !ImageFolder
      anno_path: dataset/ppyolo_voc/label_list.txt
      use_default_label: false
      with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
    - !ResizeImage
      target_size: 320
      interp: 2
    - !NormalizeImage
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_scale: True
      is_channel_first: false
    - !Permute
      to_bgr: false
      channel_first: True
  batch_size: 1
```

# 显卡使用情况：
![image](https://user-images.githubusercontent.com/37362070/104978795-a86aab80-5a3d-11eb-9db6-23bb5c282b3b.png)

# 日志打印情况：
![image](https://user-images.githubusercontent.com/37362070/104978918-f8e20900-5a3d-11eb-9042-0732efbf12fd.png)

# 不同worker_num实验对比情况：
![image](https://user-images.githubusercontent.com/37362070/104992353-d232cb00-5a5b-11eb-9a54-eee9bedee770.png)

# 配置
python版本：3.6.12
paddle版本：1.8.4
