### ISSUE TITLE
关于FPN的anchor生成

### ISSUE THREAD

**Issue by jewelc92** [PaddlePaddle/PaddleDetection#2221]
```
FPN:
  min_level: 2
  max_level: 6
  num_chan: 256
  spatial_scale: [0.03125, 0.0625, 0.125, 0.25]

FPNRPNHead:
  anchor_generator:
    anchor_sizes: [16, 32, 64, 128, 256]
    aspect_ratios: [0.5, 1.0, 2.0]
    stride: [16.0, 16.0]
    variance: [1.0, 1.0, 1.0, 1.0]
  anchor_start_size: 32
  min_level: 2
  max_level: 6
  num_chan: 256
```

yml里的配置如上所示，第一个问题是计算anchor的时候是按anchor_start_size和fpn输出的层数来计算anchor大小的吧，理论上anchor_start_size和anchor_sizes的第一个值应该一样大吧，如果不一样大也是按照anchor_start_size来计算的是吗？

第二个问题是打印self.anchor_generator(）的返回self.anchors，输出如下：
```
Variable: anchor_generator_0.tmp_0
  - lod: {}
  - place: CPUPlace
  - shape: [80, 104, 3, 4]
  - layout: NCHW
  - dtype: float
  - data: [-22 -10 25 13 -14 -14 17 17 -10 -22 13 25 -18 -10 29 13 -10 -14 21 17]
 ```
理论来说fpn的一层anchor大小是固定的，有三个anchor_ratios，所以每个位置有三个anchor，shape这里也是[3,4]，可为什么data里确有5个anchor?
