### ISSUE TITLE
faster rcnn 使用vgg16做骨干网络，生成yml配置文件问题

### ISSUE THREAD

**Issue by AngZhai** [PaddlePaddle/PaddleDetection#2272]
使用VGG16作为faster rcnn的骨干网络，文件内容如下：

```
architecture: FasterRCNN
use_gpu: true
max_iters: 16000
log_iter: 50
save_dir: output
snapshot_iter: 200
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_cos_pretrained.tar
metric: COCO
weights: output/faster_rcnn_vgg/model_final
num_classes: 5

FasterRCNN:
  backbone: VGG
  fpn: null
  rpn_head: RPNHead
  roi_extractor: RoIAlign
  bbox_head: BBoxHead
  bbox_assigner: BBoxAssigner
  rpn_only: false


VGG:
  depth: 16
  extra_block_filters:
  - - 256
    - 512
    - 1
    - 2
    - 3
  - - 128
    - 256
    - 1
    - 2
    - 3
  - - 128
    - 256
    - 0
    - 1
    - 3
  - - 128
    - 256
    - 0
    - 1
    - 3
  normalizations:
  - 20.0
  - -1
  - -1
  - -1
  - -1
  - -1
  with_extra_blocks: false

ResNetC5:
  depth: 50
  norm_type: affine_channel

RPNHead:
  anchor_generator:
    anchor_sizes:
    - 32
    - 64
    - 128
    - 256
    - 512
    aspect_ratios:
    - 0.5
    - 1.0
    - 2.0
    stride:
    - 16.0
    - 16.0
    variance:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
  num_classes: 1
  rpn_target_assign:
    rpn_batch_size_per_im: 256
    rpn_fg_fraction: 0.5
    rpn_negative_overlap: 0.3
    rpn_positive_overlap: 0.7
    rpn_straddle_thresh: 0.0
    use_random: true
  test_proposal:
    eta: 1.0
    min_size: 0.1
    nms_thresh: 0.5
    post_nms_top_n: 1000
    pre_nms_top_n: 6000
  train_proposal:
    eta: 1.0
    min_size: 0.1
    nms_thresh: 0.5
    post_nms_top_n: 2000
    pre_nms_top_n: 12000

RoIAlign:
  resolution: 7
  sampling_ratio: 0
  spatial_scale: 0.0625

BBoxAssigner:
  batch_size_per_im: 512
  bbox_reg_weights:
  - 0.1
  - 0.1
  - 0.2
  - 0.2
  bg_thresh_hi: 0.5
  bg_thresh_lo: 0.0
  fg_fraction: 0.25
  fg_thresh: 0.5
  num_classes: 81
  shuffle_before_sample: true

BBoxHead:
  bbox_loss:
    sigma: 1.0
  box_coder:
    axis: 1
    box_normalized: false
    code_type: decode_center_size
    prior_box_var:
    - 0.1
    - 0.1
    - 0.2
    - 0.2
  head: ResNetC5
  nms:
    background_label: 0
    keep_top_k: 100
    nms_eta: 1.0
    nms_threshold: 0.5
    nms_top_k: -1
    normalized: false
    score_threshold: 0.05
  num_classes: 5

LearningRate:
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    gamma:
    - 0.1
    - 0.1
    milestones:
    - 60000
    - 80000
    values: null
  - !LinearWarmup
    start_factor: 0.3333333333333333
    steps: 500

OptimizerBuilder:
  clip_grad_by_norm: null
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0001
    type: L2
_READER_: 'faster_reader.yml'
```

当我使用python tools/train.py -c configs/faster_vgg.yml  -o use_gpu=true --use_vdl=True --vdl_log_dir=vdl_dir/scalar  --eval训练的时候，报如下错误：

```
Traceback (most recent call last):
  File "tools/train.py", line 399, in <module>
    main()
  File "tools/train.py", line 136, in main
    train_fetches = model.train(feed_vars)
  File "/home/aistudio/PaddleDetection/ppdet/modeling/architectures/faster_rcnn.py", line 240, in train
    return self.build(feed_vars, 'train')
  File "/home/aistudio/PaddleDetection/ppdet/modeling/architectures/faster_rcnn.py", line 90, in build
    body_feat_names = list(body_feats.keys())
AttributeError: 'Variable' object has no attribute 'keys'
```
请问我哪里配置出错了吗
