### ISSUE TITLE
我在win10训练solov2，使用的是coco数据集，效果很差，需要修改什么配置文件吗？

### ISSUE THREAD

**Issue by zsffuture** [PaddlePaddle/PaddleDetection#2304]
如题，我没动配置文件，只是把数据集下载下来并放到了dataset下，然后就开始训练了，训练到30000个epoch时，测试结果很差，这是什么问题啊？需要修改什么东西吗？

**Comment by qingqing01** [comment]
@zsffuture 您是几张卡训练？ SOLOv2默认是8卡训练的参数配置，如果您是卡数改变，注意依据下面FAQ改变参数

 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.0-rc/docs/FAQ.md#faq%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98

**Comment by zsffuture** [comment]
@qingqing01 根据你的建议把学习率除以8，linux下可以继续训练，但是win10无法训练，之前学习率没改之前是可以训练的，现在老是出现异常，有时候在训练第0epoch卡死了，有时候报cuda错误，开始饿现象是占用显存，但是没有计算，有时候训练了几个epoch死了，如下其中一个错误：
我估计我需要重启电脑，但是现在linux在训练，无法重启，明天再尝试：
creating index...
index created!
W0308 18:23:16.052332 15760 build_strategy.cc:171] fusion_group is not enabled for Windows/MacOS now, and only effective when running with CUDA GPU.
2021-03-08 18:23:19,518-INFO: iter: 0, lr: 0.000000, 'loss_ins': '2.681851', 'loss_cate': '1.219002', 'loss': '3.900854', eta: 15:24:31, batch_cost: 0.20545 sec, ips: 4.86735 images/sec
[INFO 2021-03-08 18:23:19,518 train.py:286] iter: 0, lr: 0.000000, 'loss_ins': '2.681851', 'loss_cate': '1.219002', 'loss': '3.900854', eta: 15:24:31, batch_cost: 0.20545 sec, ips: 4.86735 images/sec
Traceback (most recent call last):
  File "tools/train.py", line 399, in <module>
    main()
  File "tools/train.py", line 270, in main
    outs = exe.run(compiled_train_prog, fetch_list=train_values)
  File "C:\install\anconda2020.11\lib\site-packages\paddle\fluid\executor.py", line 1110, in run
    six.reraise(*sys.exc_info())
  File "C:\install\anconda2020.11\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "C:\install\anconda2020.11\lib\site-packages\paddle\fluid\executor.py", line 1098, in run
    return self._run_impl(
  File "C:\install\anconda2020.11\lib\site-packages\paddle\fluid\executor.py", line 1244, in _run_impl
    return self._run_parallel(
  File "C:\install\anconda2020.11\lib\site-packages\paddle\fluid\executor.py", line 913, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
OSError: (External)  Cuda error(719), unspecified launch failure.
  [Advise: Please search for the error code(719) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official solution about CUDA Error.] (at D:\v2.0.0\paddle\paddle\fluid\platform\stream\cuda_stream.cc:65)


D:\paddle\PaddleDetection-release-2.0-rc>

**Comment by yghstill** [comment]
也可以体验动态图版本SOLOv2，更易调试：https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.0-rc/dygraph/configs/solov2

**Comment by zsffuture** [comment]
@yghstill 昨天linux下训练的iter90000次的验证信息，还是很差，已经按照你说的调整学习率了，但是还是这样：
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.001
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.001
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.001
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.001

**Comment by zsffuture** [comment]
@yghstill 我仅仅调整了学习率，你们说的“计算规则表如下所示，它们是等价的，表中变化节点即为piecewise decay里的boundaries:”，这个到底要调整什么啊？在哪个文件夹或者哪个文件？学习你们的框架好麻烦啊，复现你们的训练模型就已经这么多坑了，你们能不能，把这些东西放到明显的地方？

**Comment by zsffuture** [comment]
@yghstill 讲真的，不想用这个了，一般跑一下模型，获取作者的模型评测信息，最多一天就可以出结果，你们呢？对一个不了解你们框架的人来说，直接上手，一天内很难得到他想要的结果，主要体现在：
1.框架正文里提到的都是很关键的信息，但是需要注意的细节问题都没有提醒或者给个链接，必须到github上提问才知道别人也遇到相类似的问题
2.给出的解答不详细，对于刚认识你们的框架的人来说有点麻烦，主要体现在细节，这一类人群，对你们的框架并不了解，所以你们给出回答尽量详细到文件和参数，而不是浅浅的说一下。
3.为什么你们的框架训练模型需要那么长时间，独立跑作者的代码，可以很快看到效果，但是你们的需要跑上万次？什么原因？
4.我作为刚开始了解你们框架的新人，感觉很不友好，虽说你们整体的引导还可以，但是针对细节问题，还是不行，无法很快复现你们的训练结果，这样给我的感觉，你们的结果是不是只能在你们的机器上才能跑出来
5.当然另一部分原因是我不熟悉你们的框架？换句话说你们不打算推广你们框架吗？难道只针对熟悉你们的框架的人？如果你们想要推广你们的框架，一定要对考虑一下对你们框架不熟悉的人的感受，他们如果觉得你们的框架很麻烦，他们就不会用的。
6.不说了，把我的问题解决一下啊，我想快速的了解你们的框架，同时可以训练它，现在整体对门的框架有了解，但是复现你们的模型训练结果存在问题， 如果我无法复现你们的结果，这个框架我是不敢用到工程上的，你们懂吗？

**Comment by zsffuture** [comment]
@yghstill 你看我这win10训练的动态图solov2的训练结果截图：不知道loss为什么不收敛，而且来回跳动，学习率还是过大？但是已经调整了啊，还需要调整什么啊？还有除了调整学习率还需要调整什么呀？感谢感谢
![image](https://user-images.githubusercontent.com/39027951/110412187-ba281100-80c6-11eb-8408-c6d79315e71a.png)

**Comment by qingqing01** [comment]
@zsffuture 感谢您的建议。 @yghstill  辛苦把单卡对应的参数，详细贴出来吧。以及我们以往都是8卡训练，我们也验证下单卡的收敛趋势吧。 另外，可以加下微信，我们详细对下？

**Comment by yghstill** [comment]
@zsffuture 单卡训练loss有震荡是正常现象，看整体loss是否是下降趋势。我启动了solov2单卡的训练实验：
环境：
- paddle 2.0.1：`pip3.7 install paddlepaddle-gpu==2.0.1`
- PaddleDtection: release/2.0-rc

配置文件：
- 修改`dygraph/configs/solov2/_base_/optimizer_1x.yml`
```yaml
epoch: 12                                                                                                                                          
LearningRate:  
  base_lr: 0.00125  
  schedulers:      
  - !PiecewiseDecay    
    gamma: 0.1                                
    milestones: [8, 11]                      
  - !LinearWarmup                      
    start_factor: 0.                             
    steps: 2000    
                              
OptimizerBuilder:                             
  optimizer:                       
    momentum: 0.9                    
    type: Momentum                                                                                                                                   
  regularizer:                     
    factor: 0.0001                  
    type: L2 
```

- `dygraph/configs/solov2/_base_/solov2_reader.yml`中`TrainReader`的`batch_size`我设置的是2，如果`batch_size`设置为1，上面的`optimizer_1x.yml`中`base_lr`需要再减半，设置为0.000625，如果显存占用太多，可设置如下环境变量，减少显存占用：
```shell
export FLAGS_allocator_strategy=auto_growth
```
单卡验证实验有结论我会随时发出来，感谢反馈。
