### ISSUE TITLE
边训练边评估，第一次评估时报错，KeyError: 'mask'

### ISSUE THREAD

**Issue by zxsitu** [PaddlePaddle/PaddleDetection#2712]
您好，我按照`RCNN系列模型参数配置教程`，配置了faster_rcnn_r50_fpn_1x_coco文件，然后进行训练，设置了边训练边评估，在完成第一个epoch训练后，进行评估然后报错，请问如何解决呢？我是win10系统，cuda10.2。
```
(venv) F:\PycharmProjects\paddle_env\PaddleDetection_v2>python tools/train.py -c configs/faster_rcnn/faster_rcnn_r50_fpn_1x_coco.yml --use_vdl=true --vdl_log_dir=vdl_dir/scalar --eval -o pretrain_weights=''
F:\PycharmProjects\paddle_env\venv\lib\site-packages\paddle\fluid\layers\utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify an
y behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
F:\PycharmProjects\paddle_env\venv\lib\site-packages\paddle\tensor\creation.py:143: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not mo
dify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
W0420 15:01:55.145293  9704 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.2, Runtime API Version: 10.2
W0420 15:01:55.182265  9704 device_context.cc:372] device: 0, cuDNN Version: 7.6.
F:\PycharmProjects\paddle_env\venv\lib\site-packages\paddle\tensor\creation.py:143: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not mo
dify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
F:\PycharmProjects\paddle_env\venv\lib\site-packages\paddle\fluid\layers\utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify an
y behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
F:\PycharmProjects\paddle_env\venv\lib\site-packages\paddle\tensor\creation.py:143: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not mo
dify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
loading annotations into memory...
Done (t=0.07s)
creating index...
index created!
loading annotations into memory...
Done (t=0.03s)
creating index...
index created!
[04/20 15:02:02] ppdet.engine INFO: Epoch: [0] [  0/840] learning_rate: 0.000125 loss_rpn_cls: 4.821977 loss_rpn_reg: 10.862030 loss_bbox_cls: 91.479721 loss_bbox_reg: 1.278989 loss: 108.442719 eta: 1 day, 21:20:10 batch_cost: 0.6477 d
ata_cost: 0.1160 ips: 1.5440 images/s
[04/20 15:02:19] ppdet.engine INFO: Epoch: [0] [ 50/840] learning_rate: 0.000181 loss_rpn_cls: 0.691800 loss_rpn_reg: 0.040076 loss_bbox_cls: 1.784807 loss_bbox_reg: 0.000132 loss: 2.519022 eta: 1 day, 0:12:02 batch_cost: 0.3398 data_c
ost: 0.0000 ips: 2.9433 images/s
[04/20 15:02:36] ppdet.engine INFO: Epoch: [0] [100/840] learning_rate: 0.000237 loss_rpn_cls: 0.686576 loss_rpn_reg: 0.022304 loss_bbox_cls: 0.998424 loss_bbox_reg: 0.000732 loss: 1.738900 eta: 23:54:43 batch_cost: 0.3376 data_cost: 0
.0001 ips: 2.9621 images/s
[04/20 15:02:53] ppdet.engine INFO: Epoch: [0] [150/840] learning_rate: 0.000294 loss_rpn_cls: 0.679094 loss_rpn_reg: 0.032696 loss_bbox_cls: 0.521117 loss_bbox_reg: 0.001856 loss: 1.242578 eta: 23:45:55 batch_cost: 0.3356 data_cost: 0
.0002 ips: 2.9796 images/s
[04/20 15:03:10] ppdet.engine INFO: Epoch: [0] [200/840] learning_rate: 0.000350 loss_rpn_cls: 0.671299 loss_rpn_reg: 0.040220 loss_bbox_cls: 0.301041 loss_bbox_reg: 0.003078 loss: 1.024274 eta: 23:46:50 batch_cost: 0.3409 data_cost: 0
.0000 ips: 2.9338 images/s
[04/20 15:03:27] ppdet.engine INFO: Epoch: [0] [250/840] learning_rate: 0.000406 loss_rpn_cls: 0.659900 loss_rpn_reg: 0.035226 loss_bbox_cls: 0.200786 loss_bbox_reg: 0.004224 loss: 0.902863 eta: 23:50:39 batch_cost: 0.3449 data_cost: 0
.0001 ips: 2.8994 images/s
[04/20 15:03:44] ppdet.engine INFO: Epoch: [0] [300/840] learning_rate: 0.000463 loss_rpn_cls: 0.648516 loss_rpn_reg: 0.021577 loss_bbox_cls: 0.145219 loss_bbox_reg: 0.003496 loss: 0.824361 eta: 23:47:11 batch_cost: 0.3364 data_cost: 0
.0001 ips: 2.9726 images/s
[04/20 15:04:01] ppdet.engine INFO: Epoch: [0] [350/840] learning_rate: 0.000519 loss_rpn_cls: 0.637691 loss_rpn_reg: 0.034506 loss_bbox_cls: 0.125543 loss_bbox_reg: 0.005119 loss: 0.813680 eta: 23:41:01 batch_cost: 0.3304 data_cost: 0
.0001 ips: 3.0271 images/s
[04/20 15:04:18] ppdet.engine INFO: Epoch: [0] [400/840] learning_rate: 0.000575 loss_rpn_cls: 0.622207 loss_rpn_reg: 0.032780 loss_bbox_cls: 0.102013 loss_bbox_reg: 0.003905 loss: 0.768084 eta: 23:41:19 batch_cost: 0.3399 data_cost: 0
.0001 ips: 2.9417 images/s
[04/20 15:04:35] ppdet.engine INFO: Epoch: [0] [450/840] learning_rate: 0.000631 loss_rpn_cls: 0.607092 loss_rpn_reg: 0.031646 loss_bbox_cls: 0.091219 loss_bbox_reg: 0.004072 loss: 0.740880 eta: 23:40:18 batch_cost: 0.3374 data_cost: 0
.0001 ips: 2.9642 images/s
[04/20 15:04:52] ppdet.engine INFO: Epoch: [0] [500/840] learning_rate: 0.000688 loss_rpn_cls: 0.594590 loss_rpn_reg: 0.033824 loss_bbox_cls: 0.084186 loss_bbox_reg: 0.004528 loss: 0.729883 eta: 23:38:48 batch_cost: 0.3358 data_cost: 0
.0002 ips: 2.9775 images/s
[04/20 15:05:09] ppdet.engine INFO: Epoch: [0] [550/840] learning_rate: 0.000744 loss_rpn_cls: 0.576788 loss_rpn_reg: 0.035546 loss_bbox_cls: 0.077287 loss_bbox_reg: 0.005873 loss: 0.698221 eta: 23:40:44 batch_cost: 0.3443 data_cost: 0
.0002 ips: 2.9041 images/s
[04/20 15:05:27] ppdet.engine INFO: Epoch: [0] [600/840] learning_rate: 0.000800 loss_rpn_cls: 0.561312 loss_rpn_reg: 0.035784 loss_bbox_cls: 0.069537 loss_bbox_reg: 0.004813 loss: 0.676612 eta: 23:44:10 batch_cost: 0.3497 data_cost: 0
.0000 ips: 2.8599 images/s
[04/20 15:05:43] ppdet.engine INFO: Epoch: [0] [650/840] learning_rate: 0.000856 loss_rpn_cls: 0.548270 loss_rpn_reg: 0.036237 loss_bbox_cls: 0.070788 loss_bbox_reg: 0.004914 loss: 0.665337 eta: 23:43:00 batch_cost: 0.3371 data_cost: 0
.0001 ips: 2.9661 images/s
[04/20 15:06:01] ppdet.engine INFO: Epoch: [0] [700/840] learning_rate: 0.000913 loss_rpn_cls: 0.528082 loss_rpn_reg: 0.028139 loss_bbox_cls: 0.066664 loss_bbox_reg: 0.004008 loss: 0.625097 eta: 23:44:26 batch_cost: 0.3454 data_cost: 0
.0001 ips: 2.8951 images/s
[04/20 15:06:18] ppdet.engine INFO: Epoch: [0] [750/840] learning_rate: 0.000969 loss_rpn_cls: 0.513337 loss_rpn_reg: 0.029147 loss_bbox_cls: 0.066550 loss_bbox_reg: 0.005035 loss: 0.620225 eta: 23:43:25 batch_cost: 0.3375 data_cost: 0
.0001 ips: 2.9631 images/s
[04/20 15:06:34] ppdet.engine INFO: Epoch: [0] [800/840] learning_rate: 0.001025 loss_rpn_cls: 0.493828 loss_rpn_reg: 0.037048 loss_bbox_cls: 0.063218 loss_bbox_reg: 0.005998 loss: 0.603519 eta: 23:40:52 batch_cost: 0.3313 data_cost: 0
.0001 ips: 3.0186 images/s
[04/20 15:06:52] ppdet.utils.checkpoint INFO: Save checkpoint: output\faster_rcnn_r50_fpn_1x_coco
F:\PycharmProjects\paddle_env\venv\lib\site-packages\paddle\fluid\layers\utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify an
y behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
F:\PycharmProjects\paddle_env\venv\lib\site-packages\paddle\tensor\creation.py:143: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not mo
dify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
loading annotations into memory...
Done (t=0.04s)
creating index...
index created!
[04/20 15:06:56] ppdet.engine INFO: Eval iter: 0
[04/20 15:07:05] ppdet.engine INFO: Eval iter: 100
[04/20 15:07:14] ppdet.engine INFO: Eval iter: 200
[04/20 15:07:14] ppdet.engine INFO: Total sample number: 210, averge FPS: 10.852178109389282
Traceback (most recent call last):
  File "tools/train.py", line 137, in <module>
    main()
  File "tools/train.py", line 133, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 111, in run
    trainer.train(FLAGS.eval)
  File "F:\PycharmProjects\paddle_env\venv\lib\site-packages\paddledet-2.0-py3.8.egg\ppdet\engine\trainer.py", line 304, in train
    self._eval_with_loader(self._eval_loader)
  File "F:\PycharmProjects\paddle_env\venv\lib\site-packages\paddledet-2.0-py3.8.egg\ppdet\engine\trainer.py", line 332, in _eval_with_loader
    self._compose_callback.on_epoch_end(self.status)
  File "F:\PycharmProjects\paddle_env\venv\lib\site-packages\paddledet-2.0-py3.8.egg\ppdet\engine\callbacks.py", line 76, in on_epoch_end
    c.on_epoch_end(status)
  File "F:\PycharmProjects\paddle_env\venv\lib\site-packages\paddledet-2.0-py3.8.egg\ppdet\engine\callbacks.py", line 182, in on_epoch_end
    if map_res[key][0] > self.best_ap:
KeyError: 'mask'
```

**Comment by ilem777** [comment]
我修改了如下文件：
`coco_detection.yml`文件
```
metric: COCO
num_classes: 5

TrainDataset:
  !COCODataSet
    image_dir: F:\PycharmProjects\paddle_env\PaddleDetection_v2\dataset\sewer-defects\train
    anno_path: F:\PycharmProjects\paddle_env\PaddleDetection_v2\dataset\sewer-defects\annotations\instance_train.json
    dataset_dir: F:\PycharmProjects\paddle_env\PaddleDetection_v2\dataset\sewer-defects
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: F:\PycharmProjects\paddle_env\PaddleDetection_v2\dataset\sewer-defects\val
    anno_path: F:\PycharmProjects\paddle_env\PaddleDetection_v2\dataset\sewer-defects\annotations\instance_val.json
    dataset_dir: F:\PycharmProjects\paddle_env\PaddleDetection_v2\dataset\sewer-defects

TestDataset:
  !ImageFolder
    anno_path: F:\PycharmProjects\paddle_env\PaddleDetection_v2\dataset\sewer-defects\annotations\instance_val.json
```

`optimizer_1x.yml`文件
```
epoch: 300 # default=12

LearningRate:
  base_lr: 0.00125 # default=0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [200, 290]
  - !LinearWarmup
    start_factor: 0.1
    steps: 1000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0001
    type: L2
```

其余文件我都没做修改。
