### ISSUE TITLE
新版本训练报错

### ISSUE THREAD

**Issue by guotongjian** [PaddlePaddle/PaddleDetection#2735]
![1619066600(1)](https://user-images.githubusercontent.com/73452319/115656827-73d1fd00-a368-11eb-8e6e-def740717296.jpg)
![1619066612(1)](https://user-images.githubusercontent.com/73452319/115656829-75032a00-a368-11eb-94cb-cc351b88c2a9.jpg)
设置了每5个epoch评价一次，5个epoch后模型评价不大对劲，map都是0，然后训练到10个epoch，评估的时候报错了。我配置文件的信息跟以前老版本用的参数都是一样的，是不是我哪里配置错的原因

**Comment by yghstill** [comment]
@guotongjian 哪个模型？是用的release 2.0分支最新代码吗

**Comment by guotongjian** [comment]
> @guotongjian 哪个模型？是用的release 2.0分支最新代码吗

yolov3加强版的模型，最新2.0的代码

**Comment by guotongjian** [comment]
> @guotongjian 哪个模型？是用的release 2.0分支最新代码吗

![1619069160(1)](https://user-images.githubusercontent.com/73452319/115660234-50aa4c00-a36e-11eb-97cb-6c39f162bc45.jpg)

**Comment by yghstill** [comment]
@guotongjian 感谢反馈，这个问题我们排查下

**Comment by wangxinxin08** [comment]
看你的模型训练的很差，如果方便的话可以发一下你的配置文件并描述下你的数据集(类别数目，特点)吗？

**Comment by guotongjian** [comment]
> 看你的模型训练的很差，如果方便的话可以发一下你的配置文件并描述下你的数据集(类别数目，特点)吗？
类别我只有4类，用以前老版本训练几个epoch的时候都有10几的map了，不是这样的00000，效果还是有的。
配置文件我给您看下：
**总的一个配置**：
```
_BASE_: [
  '../datasets/my_coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_400e.yml',
  '_base_/my_net.yml',
  '_base_/yolov3_reader.yml',
]

snapshot_epoch: 5
weights: output/my/best_model
```
**my_coco_detection**：
```
metric: COCO
num_classes: 4

TrainDataset:
  !COCODataSet
    image_dir: train2017
    anno_path: annotations/instances_train2017.json
    dataset_dir: data/coco
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: val2017
    anno_path: annotations/instances_val2017.json
    dataset_dir: data/coco

TestDataset:
  !ImageFolder
    anno_path: annotations/instances_test2017.json
```
**runtime**
```
use_gpu: true
log_iter: 10
save_dir: output
snapshot_epoch: 1
```
**yolov3_reader:**
```
worker_num: 2
TrainReader:
  inputs_def:
    num_max_boxes: 50
  sample_transforms:
    - Decode: {}
    - Mixup: {alpha: 1.5, beta: 1.5}
    - RandomDistort: {}
    - RandomExpand: {fill_value: [123.675, 116.28, 103.53]}
    - RandomCrop: {}
    - RandomFlip: {}
  batch_transforms:
    - BatchRandomResize: {target_size: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608], random_size: True, random_interp: True, keep_ratio: False}
    - NormalizeBox: {}
    - PadBox: {num_max_boxes: 50}
    - BboxXYXY2XYWH: {}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
    - Gt2YoloTarget: {anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]], anchors: [[10, 13], [16, 30], [33, 23], [30, 61], [62, 45], [59, 119], [116, 90], [156, 198], [373, 326]], downsample_ratios: [32, 16, 8]}
  batch_size: 8
  shuffle: true
  drop_last: true
  mixup_epoch: 250
  use_shared_memory: true

EvalReader:
  inputs_def:
    num_max_boxes: 50
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [608, 608], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 1
  drop_empty: false

TestReader:
  inputs_def:
    image_shape: [3, 608, 608]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [608, 608], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 1
```
**optimizer:**
```
epoch: 400

LearningRate:
  base_lr: 0.000125
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 240
    - 320
  - !LinearWarmup
    start_factor: 0.
    steps: 4000

OptimizerBuilder:

  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2
```

**mynet:**
```
architecture: YOLOv3
pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_vd_ssld_pretrained.pdparams
norm_type: sync_bn

YOLOv3:
  backbone: ResNet
  neck: YOLOv3FPN
  yolo_head: YOLOv3Head
  post_process: BBoxPostProcess

ResNet:
  depth: 50
  variant: d
  return_idx: [1, 2, 3]
  dcn_v2_stages: [1]
  freeze_at: -1
  freeze_norm: false
  norm_decay: 0.

# YOLOv3FPN:

YOLOv3Head:
  anchors: [[10, 13], [16, 30], [33, 23],
            [30, 61], [62, 45], [59, 119],
            [116, 90], [156, 198], [373, 326]]
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  loss: YOLOv3Loss

YOLOv3Loss:
  ignore_thresh: 0.7
  downsample: [32, 16, 8]
  label_smooth: false
  iou_loss: IouLoss

IouLoss:
  loss_weight: 2.5
  loss_square: true
  
BBoxPostProcess:
  decode:
    name: YOLOBox
    conf_thresh: 0.005
    downsample_ratio: 32
    clip_bbox: true
  nms:
    name: MultiClassNMS
    keep_top_k: 100
    score_threshold: 0.01
    nms_threshold: 0.45
    nms_top_k: 1000

```
