### ISSUE TITLE
PPYOLO模型单卡训练自制数据时报错：fail to map op [Gt2YoloTarget_dbee5d] with error: index 834 is out of bounds for axis 1 with size 56 and stack:

### ISSUE THREAD

**Issue by GreenValue** [PaddlePaddle/PaddleDetection#2804]
- Error
```2021-04-28 11:17:02,946-WARNING: fail to map op [Gt2YoloTarget_dbee5d] with error: index 834 is out of bounds for axis 1 with size 56 and stack:
Traceback (most recent call last):
  File "/paddle/PaddleDetection/PaddleDetection/ppdet/data/reader.py", line 46, in __call__
    data = f(data, ctx)
  File "/paddle/PaddleDetection/PaddleDetection/ppdet/data/transform/batch_operators.py", line 279, in __call__
    target[best_n, 6 + cls, gj, gi] = 1.
IndexError: index 834 is out of bounds for axis 1 with size 56
```
- Environment

1. Docker Image
 hub.baidubce.com/paddlepaddle/paddle:1.8.5-gpu-cuda10.0-cudnn7

2.  PaddleDetection
```/paddle/PaddleDetection/PaddleDetection {master} git branch
 * master
  origin/release/0.5
```
-ppyolo.yml，ppyolo_reader.yml 修改说明
![image](https://user-images.githubusercontent.com/16701660/116397234-ef481880-a858-11eb-9ab4-eec0326ef5eb.png)

-  ppyolo.yml
```
architecture: YOLOv3
use_gpu: true
max_iters: 50000
log_iter: 100
save_dir: output
snapshot_iter: 10000
metric: COCO
pretrain_weights: https://paddle-imagenet-models-name.bj.bcebos.com/ResNet50_vd_ssld_pretrained.tar
weights: output/ppyolo/model_final
num_classes: 50  
use_fine_grained_loss: true
use_ema: true
ema_decay: 0.9998

YOLOv3:
  backbone: ResNet
  yolo_head: YOLOv3Head
  use_fine_grained_loss: true

ResNet:
  norm_type: sync_bn
  freeze_at: 0
  freeze_norm: false
  norm_decay: 0.
  depth: 50
  feature_maps: [3, 4, 5]
  variant: d
  dcn_v2_stages: [5]

YOLOv3Head:
  anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
  anchors: [[10, 13], [16, 30], [33, 23],
            [30, 61], [62, 45], [59, 119],
            [116, 90], [156, 198], [373, 326]]
  norm_decay: 0.
  coord_conv: true
  iou_aware: true
  iou_aware_factor: 0.4
  scale_x_y: 1.05
  spp: true
  yolo_loss: YOLOv3Loss
  nms: MatrixNMS
  drop_block: true

YOLOv3Loss:
  ignore_thresh: 0.7
  scale_x_y: 1.05
  label_smooth: false
  use_fine_grained_loss: true
  iou_loss: IouLoss
  iou_aware_loss: IouAwareLoss

IouLoss:
  loss_weight: 2.5
  max_height: 320
  max_width: 320

IouAwareLoss:
  loss_weight: 1.0
  max_height: 320
  max_width: 320

MatrixNMS:
    background_label: -1
    keep_top_k: 100
    normalized: false
    score_threshold: 0.01
    post_threshold: 0.01

LearningRate:
  base_lr: 0.0002
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 40000
    - 45000
  - !LinearWarmup
    start_factor: 0.
    steps: 4000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

_READER_: 'ppyolo_reader.yml'

```

-  ppyolo_reader.yml
```
TrainReader:
  inputs_def:
    fields: ['image', 'gt_bbox', 'gt_class', 'gt_score']
    num_max_boxes: 50
  dataset:
    !COCODataSet
      image_dir: cloth_images
      anno_path: cloth_annotations/train.json
      dataset_dir: dataset/coco
      with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
      with_mixup: True
    - !MixupImage
      alpha: 1.5
      beta: 1.5
    - !ColorDistort {}
    - !RandomExpand
      ratio: 2.0
      fill_value: [123.675, 116.28, 103.53]
    - !RandomCrop {}
    - !RandomFlipImage
      is_normalized: false
    - !NormalizeBox {}
    - !PadBox
      num_max_boxes: 50
    - !BboxXYXY2XYWH {}
  batch_transforms:
  - !RandomShape
    sizes: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608]
    random_inter: True
  - !NormalizeImage
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    is_scale: True
    is_channel_first: false
  - !Permute
    to_bgr: false
    channel_first: True
  # Gt2YoloTarget is only used when use_fine_grained_loss set as true,
  # this operator will be deleted automatically if use_fine_grained_loss
  # is set as false
  - !Gt2YoloTarget
    anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]]
    anchors: [[10, 13], [16, 30], [33, 23],
              [30, 61], [62, 45], [59, 119],
              [116, 90], [156, 198], [373, 326]]
    downsample_ratios: [32, 16, 8]
  batch_size: 4
  shuffle: true
  #mixup_epoch: 25000
  mixup_epoch: 150 
  drop_last: true
  worker_num: 8
  bufsize: 4
  use_process: true

EvalReader:
  inputs_def:
    fields: ['image', 'im_size', 'im_id']
    num_max_boxes: 50
  dataset:
    !COCODataSet
      image_dir: cloth_images 
      anno_path: cloth_annotations/vali.json
      dataset_dir: dataset/coco
      with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
    - !ResizeImage
      target_size: 320
      interp: 2
    - !NormalizeImage
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_scale: True
      is_channel_first: false
    - !PadBox
      num_max_boxes: 50
    - !Permute
      to_bgr: false
      channel_first: True
  batch_size: 4
  drop_empty: false
  worker_num: 8
  bufsize: 4

TestReader:
  inputs_def:
    image_shape: [3, 320, 320]
    fields: ['image', 'im_size', 'im_id']
  dataset:
    !ImageFolder
      anno_path: cloth_annotations/test.json
      with_background: false
  sample_transforms:
    - !DecodeImage
      to_rgb: True
    - !ResizeImage
      target_size: 320
      interp: 2
    - !NormalizeImage
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      is_scale: True
      is_channel_first: false
    - !Permute
      to_bgr: false
      channel_first: True
  batch_size: 1

```
- Output log

```
/paddle/PaddleDetection/PaddleDetection {master} python tools/train.py -c configs/ppyolo/ppyolo.yml --eval
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: /paddle/PaddleDetection/PaddleDetection/ppdet/modeling/losses/yolo_loss.py:155
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: /paddle/PaddleDetection/PaddleDetection/ppdet/modeling/losses/yolo_loss.py:172
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: /paddle/PaddleDetection/PaddleDetection/ppdet/modeling/losses/yolo_loss.py:172
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: /paddle/PaddleDetection/PaddleDetection/ppdet/modeling/losses/yolo_loss.py:174
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: /paddle/PaddleDetection/PaddleDetection/ppdet/modeling/losses/yolo_loss.py:174
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: /paddle/PaddleDetection/PaddleDetection/ppdet/modeling/losses/yolo_loss.py:178
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: /paddle/PaddleDetection/PaddleDetection/ppdet/modeling/losses/yolo_loss.py:178
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: /paddle/PaddleDetection/PaddleDetection/ppdet/modeling/losses/yolo_loss.py:180
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: /paddle/PaddleDetection/PaddleDetection/ppdet/modeling/losses/yolo_loss.py:180
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: /paddle/PaddleDetection/PaddleDetection/ppdet/modeling/losses/iou_loss.py:219
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: /paddle/PaddleDetection/PaddleDetection/ppdet/modeling/losses/iou_loss.py:220
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: /paddle/PaddleDetection/PaddleDetection/ppdet/modeling/losses/iou_loss.py:221
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: /paddle/PaddleDetection/PaddleDetection/ppdet/modeling/losses/iou_loss.py:222
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: /paddle/PaddleDetection/PaddleDetection/ppdet/modeling/losses/iou_loss.py:102
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: /paddle/PaddleDetection/PaddleDetection/ppdet/modeling/losses/iou_loss.py:102
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: /paddle/PaddleDetection/PaddleDetection/ppdet/modeling/losses/iou_loss.py:104
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: /paddle/PaddleDetection/PaddleDetection/ppdet/modeling/losses/iou_loss.py:106
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: /paddle/PaddleDetection/PaddleDetection/ppdet/modeling/losses/iou_loss.py:106
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: /paddle/PaddleDetection/PaddleDetection/ppdet/modeling/losses/iou_loss.py:106
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: /paddle/PaddleDetection/PaddleDetection/ppdet/modeling/losses/iou_loss.py:107
The behavior of expression A / B has been unified with elementwise_div(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_div(X, Y, axis=0) instead of A / B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: /paddle/PaddleDetection/PaddleDetection/ppdet/modeling/losses/iou_loss.py:84
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: /paddle/PaddleDetection/PaddleDetection/ppdet/modeling/losses/yolo_loss.py:186
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: /paddle/PaddleDetection/PaddleDetection/ppdet/modeling/losses/yolo_loss.py:194
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: /paddle/PaddleDetection/PaddleDetection/ppdet/modeling/losses/yolo_loss.py:380
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: /paddle/PaddleDetection/PaddleDetection/ppdet/modeling/losses/yolo_loss.py:382
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: /paddle/PaddleDetection/PaddleDetection/ppdet/modeling/losses/yolo_loss.py:207
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: /paddle/PaddleDetection/PaddleDetection/ppdet/modeling/losses/yolo_loss.py:208
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: /paddle/PaddleDetection/PaddleDetection/ppdet/modeling/losses/yolo_loss.py:210
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
2021-04-28 11:16:54,982-INFO: If regularizer of a Parameter has been set by 'fluid.ParamAttr' or 'fluid.WeightNormParamAttr' already. The Regularization[L2Decay, regularization_coeff=0.000500] in Optimizer will not take effect, and it will only be applied to other Parameters!
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: /paddle/PaddleDetection/PaddleDetection/ppdet/modeling/anchor_heads/iou_aware.py:64
The behavior of expression A * B has been unified with elementwise_mul(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_mul(X, Y, axis=0) instead of A * B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/layers/math_op_patch.py:298: UserWarning: /paddle/PaddleDetection/PaddleDetection/ppdet/modeling/anchor_heads/iou_aware.py:40
The behavior of expression A / B has been unified with elementwise_div(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_div(X, Y, axis=0) instead of A / B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
W0428 11:16:58.037731    38 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.0, Runtime API Version: 10.0
W0428 11:16:58.040135    38 device_context.cc:372] device: 0, cuDNN Version: 7.6.
/usr/local/python2.7.15/lib/python2.7/site-packages/paddle/fluid/io.py:2284: UserWarning: This list is not set, Because of Paramerter not found in program. There are: fc_0.b_0 fc_0.w_0
  format(" ".join(unused_para_list)))
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
2021-04-28 11:17:02,911-WARNING: fail to map op [Gt2YoloTarget_dbee5d] with error: index 717 is out of bounds for axis 1 with size 56 and stack:
Traceback (most recent call last):
  File "/paddle/PaddleDetection/PaddleDetection/ppdet/data/reader.py", line 46, in __call__
    data = f(data, ctx)
  File "/paddle/PaddleDetection/PaddleDetection/ppdet/data/transform/batch_operators.py", line 279, in __call__
    target[best_n, 6 + cls, gj, gi] = 1.
IndexError: index 717 is out of bounds for axis 1 with size 56

2021-04-28 11:17:02,913-WARNING: recv endsignal from outq with errmsg[consumer[consumer-072-2] failed to map with error:[index 717 is out of bounds for axis 1 with size 56]]
2021-04-28 11:17:02,916-WARNING: fail to map op [Gt2YoloTarget_dbee5d] with error: index 114 is out of bounds for axis 1 with size 56 and stack:
Traceback (most recent call last):
  File "/paddle/PaddleDetection/PaddleDetection/ppdet/data/reader.py", line 46, in __call__
    data = f(data, ctx)
  File "/paddle/PaddleDetection/PaddleDetection/ppdet/data/transform/batch_operators.py", line 279, in __call__
    target[best_n, 6 + cls, gj, gi] = 1.
IndexError: index 114 is out of bounds for axis 1 with size 56

2021-04-28 11:17:02,919-WARNING: fail to map op [Gt2YoloTarget_dbee5d] with error: index 220 is out of bounds for axis 1 with size 56 and stack:
Traceback (most recent call last):
  File "/paddle/PaddleDetection/PaddleDetection/ppdet/data/reader.py", line 46, in __call__
    data = f(data, ctx)
  File "/paddle/PaddleDetection/PaddleDetection/ppdet/data/transform/batch_operators.py", line 279, in __call__
    target[best_n, 6 + cls, gj, gi] = 1.
IndexError: index 220 is out of bounds for axis 1 with size 56

2021-04-28 11:17:02,923-WARNING: fail to map op [Gt2YoloTarget_dbee5d] with error: index 973 is out of bounds for axis 1 with size 56 and stack:
Traceback (most recent call last):
  File "/paddle/PaddleDetection/PaddleDetection/ppdet/data/reader.py", line 46, in __call__
    data = f(data, ctx)
  File "/paddle/PaddleDetection/PaddleDetection/ppdet/data/transform/batch_operators.py", line 279, in __call__
    target[best_n, 6 + cls, gj, gi] = 1.
IndexError: index 973 is out of bounds for axis 1 with size 56

2021-04-28 11:17:02,923-WARNING: fail to map op [Gt2YoloTarget_dbee5d] with error: index 826 is out of bounds for axis 1 with size 56 and stack:
Traceback (most recent call last):
  File "/paddle/PaddleDetection/PaddleDetection/ppdet/data/reader.py", line 46, in __call__
    data = f(data, ctx)
  File "/paddle/PaddleDetection/PaddleDetection/ppdet/data/transform/batch_operators.py", line 279, in __call__
    target[best_n, 6 + cls, gj, gi] = 1.
IndexError: index 826 is out of bounds for axis 1 with size 56

2021-04-28 11:17:02,935-WARNING: fail to map op [Gt2YoloTarget_dbee5d] with error: index 839 is out of bounds for axis 1 with size 56 and stack:
Traceback (most recent call last):
  File "/paddle/PaddleDetection/PaddleDetection/ppdet/data/reader.py", line 46, in __call__
    data = f(data, ctx)
  File "/paddle/PaddleDetection/PaddleDetection/ppdet/data/transform/batch_operators.py", line 279, in __call__
    target[best_n, 6 + cls, gj, gi] = 1.
IndexError: index 839 is out of bounds for axis 1 with size 56

2021-04-28 11:17:02,940-WARNING: fail to map op [Gt2YoloTarget_dbee5d] with error: index 109 is out of bounds for axis 1 with size 56 and stack:
Traceback (most recent call last):
  File "/paddle/PaddleDetection/PaddleDetection/ppdet/data/reader.py", line 46, in __call__
    data = f(data, ctx)
  File "/paddle/PaddleDetection/PaddleDetection/ppdet/data/transform/batch_operators.py", line 279, in __call__
    target[best_n, 6 + cls, gj, gi] = 1.
IndexError: index 109 is out of bounds for axis 1 with size 56

2021-04-28 11:17:02,946-WARNING: fail to map op [Gt2YoloTarget_dbee5d] with error: index 834 is out of bounds for axis 1 with size 56 and stack:
Traceback (most recent call last):
  File "/paddle/PaddleDetection/PaddleDetection/ppdet/data/reader.py", line 46, in __call__
    data = f(data, ctx)
  File "/paddle/PaddleDetection/PaddleDetection/ppdet/data/transform/batch_operators.py", line 279, in __call__
    target[best_n, 6 + cls, gj, gi] = 1.
IndexError: index 834 is out of bounds for axis 1 with size 56

```
