### ISSUE TITLE
关于使用 YoLov3 MobilenetV3训练新数据

### ISSUE THREAD

**Issue by dengxinlong** [PaddlePaddle/PaddleDetection#2818]
我使用YOLOv3_mobilenetV3来训练自定义数据集（训练集图片张数为20232），本来直接使用贵方的配置文件中的学习率，但是直接Nan了，一开始损失就非常高，达到了几万；但是使用这个数据集训练SSD_mobilenet_v3一开始的损失也就几十，所以应该还是学习率的问题，或者预训练权重；下面是我的配置：
```
最大迭代次数：200000

LearningRate:
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 120000
    - 140000

batch_szie: 8
```
单卡，Tesla V100(显存为16G)，这里主要是我不知道贵方采用了几张显卡？所以学习率不太好计算。
