### ISSUE TITLE
剪裁不能用啊

### ISSUE THREAD

**Issue by guotongjian** [PaddlePaddle/PaddleDetection#2881]
之前用自己改动的一个模型剪裁一直不成功，又用原版的yolov3试了一下剪裁，还是报错，这个老说我名字不一样是为啥啊，我不知道我到底哪里错了。。。
![image](https://user-images.githubusercontent.com/73452319/117292756-25ae1500-aea3-11eb-87fb-2879e4e95470.png)
下面是我打印出来的部分参数名称截图
![image](https://user-images.githubusercontent.com/73452319/117292892-49715b00-aea3-11eb-8395-5a6263e300b9.png)
配置文件是这么写的，是我pretrain_weights的地址写错了吗？还是pruned_params的名称写错了？。。。。
```
pretrain_weights: output/yolov3_darknet53_270e_coco/215.pdparams
slim: Pruner

Pruner:
  criterion: fpgm
  pruned_params: ['conv2d_27.w_0', 'conv2d_28.w_0', 'conv2d_29.w_0',
                  'conv2d_30.w_0', 'conv2d_31.w_0', 'conv2d_32.w_0',
                  'conv2d_34.w_0', 'conv2d_35.w_0', 'conv2d_36.w_0',
                  'conv2d_37.w_0', 'conv2d_38.w_0', 'conv2d_39.w_0',
                  'conv2d_41.w_0', 'conv2d_42.w_0', 'conv2d_43.w_0',
                  'conv2d_44.w_0', 'conv2d_45.w_0', 'conv2d_46.w_0']
  pruned_ratios: [0.1,0.2,0.2,0.2,0.2,0.1,0.2,0.3,0.3,0.3,0.2,0.1,0.3,0.4,0.4,0.4,0.4,0.3]
  print_params: True
```

**Comment by yghstill** [comment]
@guotongjian 上面的配置是yolov3_mbv1的，yolov3_darknet的剪裁配置参考如下：
```yaml
pretrain_weights: https://paddledet.bj.bcebos.com/models/yolov3_darknet53_270e_coco.pdparams
slim: Pruner

Pruner:
  criterion: fpgm
  pruned_params: ['conv2d_52.w_0', 'conv2d_53.w_0', 'conv2d_54.w_0',
                  'conv2d_55.w_0', 'conv2d_56.w_0', 'conv2d_57.w_0',
                  'conv2d_59.w_0', 'conv2d_60.w_0', 'conv2d_61.w_0',
                  'conv2d_62.w_0', 'conv2d_63.w_0', 'conv2d_64.w_0',
                  'conv2d_66.w_0', 'conv2d_67.w_0', 'conv2d_68.w_0',
                  'conv2d_69.w_0', 'conv2d_70.w_0', 'conv2d_71.w_0']
  pruned_ratios: [0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.75,0.875,0.875,0.875,0.875,0.875,0.875]
  print_params: True
```
