### ISSUE TITLE
通过paddleSlim网络搜索获得模型结构后，如何添加至paddleDetection训练？

### ISSUE THREAD

**Issue by 670133189** [PaddlePaddle/PaddleDetection#2887]
在paddleDetection只有人脸nas的案例（static/slim/nas/search_space/blazefacespace_nas.py）
执行后会得到如下配置，可以直接添加至（static/configs/face_detection/blazeface.yml）进行训练：
```
------------->>> BlazeFace-NAS structure start: <<<----------------
BlazeNet:
  blaze_filters: XXX
  double_blaze_filters: XXX
  use_5x5kernel: XXX
  with_extra_blocks: XXX
  lite_edition: XXX
-------------->>> BlazeFace-NAS structure end! <<<-----------------
```

如果是其它网络的nas，比如MobileNet v2，最后得到网络结构比如：**var mobilenetv2_last_pool.tmp_0 : paddle.VarType.LOD_TENSOR.shape(-1, 1280, 1, 1).astype(VarType.FP32)**

该如何添加至paddleDetection的.yml中训练？
