### ISSUE TITLE
如何修改ppyolov2的输入大小

### ISSUE THREAD

**Issue by ANewAnonymous** [PaddlePaddle/PaddleDetection#2934]
目前我看到的输入大小是640x640,如果我想要修改成1280x1280应该修改哪些地方？

**Comment by liuhuiCNN** [comment]
主要是预处理中的Resize（BatchRandomResize或者Resize）。如有需要可以将TestReader.inputs_def.image_shape 默认值改成您的尺寸。

**Comment by ANewAnonymous** [comment]
> 主要是预处理中的Resize（BatchRandomResize或者Resize）。如有需要可以将TestReader.inputs_def.image_shape 默认值改成您的尺寸。
你可以帮我看看我修改的是否正确吗？非常感谢您的帮助！

默认为640x640的输入大小，配置文件如下
```

TrainReader:
  batch_transforms:
    - BatchRandomResize: {target_size: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608, 640, 672, 704, 736, 768], random_size: True, random_interp: True, keep_ratio: False}

EvalReader:
  sample_transforms:
    - Resize: {target_size: [640, 640], keep_ratio: False, interp: 2}

TestReader:
  inputs_def:
    image_shape: [3, 640, 640]
  sample_transforms:
    - Resize: {target_size: [640, 640], keep_ratio: False, interp: 2}

```
如果我想修改他的输入大小为1024，对他进行了下列修改

```
TrainReader:
  batch_transforms:
    - BatchRandomResize: {target_size: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 768, 960, 992, 1024], random_size: True, random_interp: True, keep_ratio: False}

EvalReader:
  sample_transforms:
    - Resize: {target_size: [1024, 1024], keep_ratio: False, interp: 2}

TestReader:
  inputs_def:
    image_shape: [3, 1024, 1024]
  sample_transforms:
    - Resize: {target_size: [1024,1024], keep_ratio: False, interp: 2}

```
我的修改是否正确？
