### ISSUE TITLE
mask_rcnn执行eval报错

### ISSUE THREAD

**Issue by thugbobby** [PaddlePaddle/PaddleDetection#2957]
在训练完成之后执行验证程序时报错，请问如何解决？执行指令为：
`python .\tools\eval.py -c .\configs\mask_rcnn\mask_rcnn_r50_1x_coco.yml -o use_gpu=True`
报错信息如下：
```
SystemError: (Fatal) Operator batch_norm raises an struct paddle::memory::allocation::BadAlloc exception.
The exception content is
:ResourceExhaustedError:

Out of memory error on GPU 0. Cannot allocate 382.812744MB memory on GPU 0, available memory is only 271.000000MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model.

 (at D:\v2.0.2\paddle\paddle\fluid\memory\allocation\cuda_allocator.cc:69)
. (at D:\v2.0.2\paddle\paddle\fluid\imperative\tracer.cc:172)
```
验证集代码为：
```
EvalReader:
  sample_transforms:
  - Decode: {}
  - Resize: {interp: 2, target_size: [300, 600], keep_ratio: True}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: -1}
  batch_size: 1
  shuffle: false
  drop_last: false
  drop_empty: false
```
看报错信息是提示显存不足，但查看显存是基本没有使用的
![image](https://user-images.githubusercontent.com/68416779/117862845-b16dda00-b2c5-11eb-86e7-cc9014a3d69a.png)
运行环境为：GTX1660+WIN10+python3.7+paddleDetection2.0最新版
