### ISSUE TITLE
关于ppyolov2训练网络模型的输入大小

### ISSUE THREAD

**Issue by ANewAnonymous** [PaddlePaddle/PaddleDetection#3121]
如果我的预测目标是1920*1080的图像，我不想图片被resize到608x608，这样会造成拉伸，我是否可以将他除以2以 960x544的输入大小进行模型训练和预测
如下配置:
```
TrainReader:
  inputs_def:
    image_shape: [3, 544, 960]
  batch_transforms:
    - BatchRandomResize: {target_size: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 768, 960], random_size: True, random_interp: True, keep_ratio: False}

EvalReader:
  sample_transforms:
    - Resize: {target_size: [544, 960], keep_ratio: False, interp: 2}

TestReader:
  inputs_def:
    image_shape: [3, 544, 960]
  sample_transforms:
    - Resize: {target_size: [544,960], keep_ratio: False, interp: 2}
```

**Comment by jerrywgz** [comment]
https://github.com/PaddlePaddle/PaddleDetection/pull/3132 这个pr修复了BatchRandomResize中两维输入的问题，合入后即可支持960x544的输入大小进行模型训练和预测

**Comment by ANewAnonymous** [comment]
> #3132 这个pr修复了BatchRandomResize中两维输入的问题，合入后即可支持960x544的输入大小进行模型训练和预测

我没有看到与此相关的文档，我应该怎么修改配置来使用960x544的输入大小进行模型训练，非常感谢您的帮助
```
TrainReader:
  inputs_def:
    image_shape: [3, 544, 960]
  batch_transforms:
    - BatchRandomResize: {target_size: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800, 832, 864, 896, 928, 768, 960], random_size: True, random_interp: True, keep_ratio: False}

EvalReader:
  sample_transforms:
    - Resize: {target_size: [544, 960], keep_ratio: False, interp: 2}

TestReader:
  inputs_def:
    image_shape: [3, 544, 960]
  sample_transforms:
    - Resize: {target_size: [544,960], keep_ratio: False, interp: 2}

```
