### ISSUE TITLE
Paddle框架和Pytorch框架，在检测速度方面的差距大？

### ISSUE THREAD

**Issue by zxsitu** [PaddlePaddle/PaddleDetection#3127]
开发者您好，我因为使用Win10系统，所以没法使用主流的目标检测框架（detectron2或者mmdetection等），考虑使用paddledetection完成我的研究。paddle框架下的模型训练很正常，检测精度也很高，但为什么检测速度会比pytorch框架的模型或代码差那么多呢？
我使用
1、[YOLOv5](https://github.com/ultralytics/yolov5)进行YOLOv5的训练，200个epoch，其中YOLOv5s的检测精度AP为0.231，FPS为80.0（批大小为1）；YOLOv5x的检测精度AP为0.311，FPS为18.5（批大小为1）。
2、[YOLOv4](https://github.com/WongKinYiu/PyTorch_YOLOv4)进行YOLOv4的训练，200个epoch，检测精度AP为0.266，FPS为22.6（批大小为1）

但我使用Paddledetection训练PP-YOLO系列
1、PP-YOLO（ppyolo_r50vd_dcn_1x_coco），200个epoch，检测精度AP为0.226，FPS仅为10.7（批大小为1）；
2、PP-YOLO-tiny（ppyolo_tiny_650e_coco），200个epoch，检测精度AP为0.173，FPS最离谱仅为20.7（批大小为1），甚至我都怀疑这究竟是不是tiny模型；
3、PP-YOLOv2（﻿ppyolov2_r50vd_dcn_365e_coco），200个epoch，检测精度AP为0.297，FPS为13.2（批大小为1）。

综上，是Paddledetection框架和pytorch框架在哪部分存在差异呢？请问这个检测速度FPS可信吗？
我的电脑是Win10，cuda 10.2，GPU为NVIDIA Quadro P5000 16G 单卡。

**Comment by wangxinxin08** [comment]
你好，请问各个模型给出的FPS是怎么测量得到的？

**Comment by zxsitu** [comment]
@wangxinxin08 对于YOLOv3、v4、v5都是一样的测试代码，使用[test.py](https://github.com/ultralytics/yolov5/blob/9f3a388cea66ca71b9bbe057929eed8fbc920a7e/test.py)。
举例：
测试YOLOv5s的代码如下`python test.py --data data/coco128.yaml --weights runs/train/yolov5s-ch/weights/best.pt --verbose --save-txt --batch-size 1 --name yolov5s-ch-inference-b1`
``` 
all        200         823       0.527        0.64       0.573       0.231
CR         200         129       0.385       0.427       0.331      0.0968
DJ         200         144       0.599       0.623       0.641       0.267
OB         200         375       0.388       0.744       0.593       0.301
RW         200          47       0.803       0.787       0.784       0.323
TR         200         128        0.46       0.617       0.515       0.165
Speed: 18.7/3.6/22.3 ms inference/NMS/total per 640x640 image at batch-size 1
                 ↑   Pytorch的YOLO我选择了这个加和的总时间。
Results saved to runs\test\yolov5s-ch-inference-b12
200 labels saved to runs\test\yolov5s-ch-inference-b12\labels
```

而测试PP-YOLO系列时，我使用[tools/eval.py](https://github.com/PaddlePaddle/PaddleDetection/blob/bd99ac42165df2afff07aac637a33f064ea0dd75/tools/eval.py)进行评估
`python tools/eval.py -c configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml --classwise -o weights=output/ppyolo_r50vd_dcn_1x_coco/best_model --bias`
```
DONE (t=0.28s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.226
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.468
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.208
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.345
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.120
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.271
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.198
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.424
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.519
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.611
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.410
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.558
[05/24 13:19:27] ppdet.metrics.coco_utils INFO: Per-category of bbox AP:
+----------+-------+----------+-------+----------+-------+
| category | AP    | category | AP    | category | AP    |
+----------+-------+----------+-------+----------+-------+
| CR       | 0.086 | DJ       | 0.338 | RW       | 0.214 |
| OB       | 0.300 | TR       | 0.193 | None     | None  |
+----------+-------+----------+-------+----------+-------+
[05/24 13:19:27] ppdet.metrics.coco_utils INFO: per-category PR curve has output to bbox_pr_curve folder.
[05/24 13:19:27] ppdet.engine INFO: Total sample number: 210, averge FPS: 11.042707497593351
                                                                           ↑ Paddledetection我全部使用这个FPS进行记录
```

**Comment by wangxinxin08** [comment]
1. 请使用deploy/python/infer.py进行测速, 一般不使用tools/eval.py进行测速，yolov5的测速方式其实有些tricky，也就是不同的图片被resize到了不同的尺寸
2. 如果重新训练了模型的话，进行精度评估的时候不要使用--bias选项
3.  看tiny，ppyolo以及ppyolov2精度的差距，认为ppyolo应当没有设置合理的参数，精度偏低，ppyolov2_r50vd精度应当略低于yolov5x

**Comment by zxsitu** [comment]
@wangxinxin08 非常感谢您详细的解释！
1、我使用`deploy/python/infer.py`重新进行测速了，以下的结果应该很准确了：
PP-YOLO：Inference: 43.99475574493408 ms per batch image
PP-YOLOv2：Inference: 46.183576583862305 ms per batch image
PP-YOLO-tiny：Inference: 8.215279579162598 ms per batch image
```
举例PP-YOLO-tiny
-----------  Running Arguments -----------
camera_id: -1
image_file: val1.png
model_dir: output_inference/ppyolo_tiny_650e_coco
output_dir: output
run_benchmark: True
run_mode: fluid
threshold: 0.5
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
use_dynamic_shape: False
use_gpu: True
video_file:
------------------------------------------
-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order:
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
Inference: 8.215279579162598 ms per batch image
```
2、我取消了`--bias`重新测试了PP-YOLO和PP-YOLO-tiny（PP-YOLOv2我没有设置bias选项），感觉差距不大，没关系了。
PP-YOLO的AP从0.226→0.227
PP-YOLO-tiny的AP从0.173→0.174

3、我的PP-YOLO的配置如下，请问有什么需要修改的地方吗？
`ppyolo_reader.yml`
```
worker_num: 2
TrainReader:
  inputs_def:
    num_max_boxes: 50
  sample_transforms:
    - Decode: {}
    - Mixup: {alpha: 1.5, beta: 1.5}
    - RandomDistort: {}
    - RandomExpand: {fill_value: [123.675, 116.28, 103.53]}
    - RandomCrop: {}
    - RandomFlip: {}
  batch_transforms:
    - BatchRandomResize: {target_size: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608], random_size: True, random_interp: True, keep_ratio: False}
    - NormalizeBox: {}
    - PadBox: {num_max_boxes: 50}
    - BboxXYXY2XYWH: {}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
    - Gt2YoloTarget: {anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]], anchors: [[10, 13], [16, 30], [33, 23], [30, 61], [62, 45], [59, 119], [116, 90], [156, 198], [373, 326]], downsample_ratios: [32, 16, 8]}
  batch_size: 2    # default=24
  shuffle: true
  drop_last: true
  mixup_epoch: 25000
  use_shared_memory: true

EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [608, 608], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 1    # default=8   
  drop_empty: false

TestReader:
  inputs_def:
    image_shape: [3, 608, 608]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [608, 608], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 1
```
`optimizer_1x.yml`
```
epoch: 200    # default=405

LearningRate:
  base_lr: 0.000625  # default=0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 120        # default=243
    - 180        # default=324
  - !LinearWarmup
    start_factor: 0.
    steps: 4000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2
```
`ppyolo_r50vd_dcn.yml`这个文件我没有修改。
