### ISSUE TITLE
MOT数据集问题

### ISSUE THREAD

**Issue by Monday-Leo** [PaddlePaddle/PaddleDetection#3179]
请问这里五个数据集分别是什么意思？和普通的detection数据集不太一样
![6}J%`0QNAHBH`CHWIEMNQ8E](https://user-images.githubusercontent.com/53975909/119653221-a6847f00-be59-11eb-883b-9bb0ddf50f85.png)

**Comment by nemonameless** [comment]
TrainDataset是训练的数据配置，EvalDataset是eval的数据配置(单独评估跟踪的detection任务或reid任务)，TestDataset是单独inference检测任务的数据配置，可以是一张图或一个图片文件夹。EvalMOTDataset是专门评估跟踪效果的MOTA指标的，TestMOTDataset是专门inference一个待跟踪的视频。

EvalDataset是按照JDE原论文设置的。JDE论文中评估检测指标只使用'citypersons.val'和'caltech.val'，而且metric和COCO VOC的不同。JDE论文评估ReID指标只使用'caltech.10k.val', 'cuhksysu.val', 'prw.val'。MOT任务中评估检测指标和ReID指标在PaddleDetection中并不常用，后期会删除EvalDataset和TestDataset。

**Comment by Monday-Leo** [comment]
如果我只想训练MOT20的数据集，该怎么修改？

**Comment by nemonameless** [comment]
```
TrainDataset:
  !MOTDataSet
    dataset_dir: dataset/mot
    image_lists: ['mot20.train']
    data_fields: ['image', 'gt_bbox', 'gt_class', 'gt_ide']

EvalMOTDataset:
  !MOTImageFolder
    task: MOT20_train
    dataset_dir: dataset/mot
    data_root: MOT20/images/train
    keep_ori_im: False # set True if save visualization images or video

TestMOTDataset:
  !MOTVideoDataset
    dataset_dir: dataset/mot
    keep_ori_im: True # set True if save visualization images or video
```
