### ISSUE TITLE
边训练边测试时存在bug

### ISSUE THREAD

**Issue by zhengzhe97** [PaddlePaddle/PaddleDetection#3209]
使用训练边测试，在评估mAP时出现如下报错。开始以为是没有生成正确coco类型的json，排查后发现格式无误，使用./tools/eval.py直接验证，正确输出。
<img width="854" alt="wrong" src="https://user-images.githubusercontent.com/26462054/120090391-b25f9200-c134-11eb-8d90-14a509d801dd.png">
<img width="705" alt="right" src="https://user-images.githubusercontent.com/26462054/120090392-b55a8280-c134-11eb-9622-a46f91152ea3.png">

coco_detection.yml如下：
```
metric: COCO
num_classes: 3 # 将其修改为数据集的类别，不包含背景类

TrainDataset:
  !COCODataSet
    image_dir: train # 训练集的图片所在文件相对于dataset_dir的路径
    anno_path: annotations/t.json # 训练集的标注文件相对于dataset_dir的路径
    dataset_dir: dataset/camera #数据集所在路径
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: train # 训练集的图片所在文件相对于dataset_dir的路径
    anno_path: annotations/val.json # 训练集的标注文件相对于dataset_dir的路径
    dataset_dir: dataset/camera #数据集所在路径
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

TestDataset:
  !COCODataSet
    image_dir: train # 训练集的图片所在文件相对于dataset_dir的路径
    anno_path: annotations/val.json # 训练集的标注文件相对于dataset_dir的路径
    dataset_dir: dataset/camera #数据集所在路径
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']
```
