### ISSUE TITLE
关于reader抛出异常的错误

### ISSUE THREAD

**Issue by terrancraft** [PaddlePaddle/PaddleDetection#3247]
自己标注的数据集转换成voc数据之后产生如下错误：
![Screenshot from 2021-06-02 16-00-44](https://user-images.githubusercontent.com/51820927/120447177-e816ac00-c3bc-11eb-830d-12376a08f3df.png)

**Comment by terrancraft** [comment]
这是我的标签格式和tree结构，感觉没有什么问题
![Screenshot from 2021-06-02 16-03-21](https://user-images.githubusercontent.com/51820927/120447298-0c728880-c3bd-11eb-8497-48b648f63a45.png)
![Screenshot from 2021-06-02 16-06-20](https://user-images.githubusercontent.com/51820927/120447306-10060f80-c3bd-11eb-90d0-c57d420dfd6a.png)

**Comment by terrancraft** [comment]
感觉数据没有什么问题，但是reader总是抛出
typeerror的异常，请问是不是需要自己定义自己的reader才行？
望解答，多谢~

**Comment by nemonameless** [comment]
你好，可以提供一下几个config配置信息吗？方便查原因

**Comment by terrancraft** [comment]
> 你好，可以提供一下几个config配置信息吗？方便查原因

当然可以～ 明早打印出来给您看

**Comment by terrancraft** [comment]
> 你好，可以提供一下几个config配置信息吗？方便查原因
![Screenshot from 2021-06-03 10-50-34](https://user-images.githubusercontent.com/51820927/120579281-d33c2600-c459-11eb-957e-447609b69728.png)

**Comment by terrancraft** [comment]
![Screenshot from 2021-06-03 10-49-22](https://user-images.githubusercontent.com/51820927/120579298-dc2cf780-c459-11eb-9e5d-9583f7b5da54.png)

**Comment by terrancraft** [comment]
![Screenshot from 2021-06-03 10-48-57](https://user-images.githubusercontent.com/51820927/120579319-e2bb6f00-c459-11eb-9cab-45d7cbf9c96c.png)

**Comment by terrancraft** [comment]
用的是ppyolov2 数据放在dataset/voc_data下面

**Comment by nemonameless** [comment]
建议按照`configs/ppyolo/_base_/ppyolov2_reader.yml`的sample_transforms的顺序
```
  sample_transforms:
    - Decode: {}
    - Mixup: {alpha: 1.5, beta: 1.5}
    - RandomDistort: {}
    - RandomExpand: {fill_value: [123.675, 116.28, 103.53]}
    - RandomCrop: {}
    - RandomFlip: {}
```
如果不使用mixup，只要设置  mixup_epoch: -1，不用删除Mixup: {alpha: 1.5, beta: 1.5}这一行
