### ISSUE TITLE
yolov3评估时报错

### ISSUE THREAD

**Issue by nianyush** [PaddlePaddle/PaddleDetection#3249]
在[这里](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.1/configs/yolov3)下载的pdparams，
yolov3_mobilenet_v1_270e_voc.pdparams

eval reader里输入尺寸为608，320都能正确评估，但416就会报错
![image](https://user-images.githubusercontent.com/5505684/120453079-4d6e9b00-c3c5-11eb-97cd-20639e9259b2.png)

错误信息：
![image](https://user-images.githubusercontent.com/5505684/120452718-fbc61080-c3c4-11eb-91d4-237483fca8e4.png)

**Comment by nemonameless** [comment]
#2731 已修复
```
EvalReader:
  inputs_def:
    num_max_boxes: 50
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [608, 608], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 2
  collate_batch: false

# set collate_batch to false because ground-truth info is needed
# on voc dataset and should not collate data in batch when batch size
# is larger than 1.
```
