### ISSUE TITLE
farimot训练时报错

### ISSUE THREAD

**Issue by Mr-ind1fferent** [PaddlePaddle/PaddleDetection#3289]
![image](https://user-images.githubusercontent.com/74087260/120881998-901fb580-c607-11eb-8275-072fc9c04fcc.png)

**Comment by nemonameless** [comment]
你好，请根据 JDE原论文给的数据集[链接](https://github.com/Zhongdao/Towards-Realtime-MOT/blob/master/DATASET_ZOO.md)下载，我们也是这么下载使用的，应该没有问题。

**Comment by Mr-ind1fferent** [comment]
> 你好，请根据 JDE原论文给的数据集[链接](https://github.com/Zhongdao/Towards-Realtime-MOT/blob/master/DATASET_ZOO.md)下载，我们也是这么下载使用的，应该没有问题。

所有的数据都要准备好吗

**Comment by nemonameless** [comment]
你想训哪个就下载哪个，对应改配置文件configs/datasets/mot.yml即可。mot模型不建议开启--eval 边训边验证，而且只是验证检测的结果而不是MOT指标，前期效果差速度慢，可以多训几个epoch后手动eval

**Comment by Mr-ind1fferent** [comment]
> 你想训哪个就下载哪个，对应改配置文件configs/datasets/mot.yml即可。mot模型不建议开启--eval 边训边验证，而且只是验证检测的结果而不是MOT指标，前期效果差速度慢，可以多训几个epoch后手动eval

对应的配置文件该如何修改？只想用mot20的train和test

**Comment by nemonameless** [comment]
```
TrainDataset:
  !MOTDataSet
    dataset_dir: dataset/mot
    image_lists: ['mot20.train']
    data_fields: ['image', 'gt_bbox', 'gt_class', 'gt_ide']

# for MOT evaluation
# If you want to change the MOT evaluation dataset, please modify 'task' and 'data_root'
EvalMOTDataset:
  !MOTImageFolder
    task: MOT20_test
    dataset_dir: dataset/mot
    data_root: MOT20/images/test
    keep_ori_im: False # set True if save visualization images or video
```

mot20 test数据集也可以直接eval，由于没有gt指标会全-1或-inf，但是会生成符合格式的结果txt文件，需要交到[MOT官网](MOT官网) 才能出mot20 test的MOTA指标。
