### ISSUE TITLE
ppyolo_tiny模型使用自定义数据集训练loss不下降的问题

### ISSUE THREAD

**Issue by claudehotline** [PaddlePaddle/PaddleDetection#3437]
paddle版本：2.1.0GPU版本
paddleDetection版本：release/2.1版本
使用train.py训练安全帽数据集的时候loss一直在37-40之间.
训练使用的配置文件为`ppyolo_tiny_650e_coco.yml`，GPU单卡训练，学习率改为了base_lr=0.000625. 训练命令为:  `python tools/train.py -c configs/ppyolo/ppyolo_tiny_650e_coco.yml`

---
#### 数据集配置为：
```
metric: VOC
map_type: 11point
num_classes: 3

TrainDataset:
  !VOCDataSet
    dataset_dir: dataset\HelmetDetection
    anno_path: trainval.txt
    label_list: label_list.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

EvalDataset:
  !VOCDataSet
    dataset_dir: dataset\HelmetDetection
    anno_path: test.txt
    label_list: label_list.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

TestDataset:
  !ImageFolder
    anno_path: dataset\HelmetDetection\label_list.txt
```
#### 数据集目录结构
![捕获](https://user-images.githubusercontent.com/12108736/122646268-dff69480-d150-11eb-84b7-bb1635147863.PNG)
