### ISSUE TITLE
迁移学习的选择数据问题

### ISSUE THREAD

**Issue by andycoder7** [PaddlePaddle/PaddleDetection#3451]
我参照了官方文档：https://paddledetection.readthedocs.io/advanced_tutorials/TRANSFER_LEARNING_cn.html 尝试对模型进行迁移学习，版本：release/2.1，执行的命令是：

```
python -u tools/train.py -c configs/yolov3/yolov3_mobilenet_v3_large_ssld_270e_voc.yml -o use_gpu=false pretrain_weights=https://paddledet.bj.bcebos.com/models/yolov3_mobilenet_v3_large_ssld_270e_voc.pdparams finetune_exclude_pretrained_params=['yolo_output']
```

我按照文档在修改了 `configs/yolov3/yolov3_mobilenet_v3_large_ssld_270e_voc.yml` 中配置:

```
_BASE_: [
#  '../datasets/voc.yml',
  '../runtime.yml',
  '_base_/optimizer_270e.yml',
  '_base_/yolov3_mobilenet_v3_large.yml',
  '_base_/yolov3_reader.yml',
]

dataset:
    !VOCDataSet
    dataset_dir: /home/PaddleDetection/dataset/voc
    anno_path: trainval.txt
    use_default_label: true
    with_background: false

snapshot_epoch: 5
pretrain_weights:  https://paddledet.bj.bcebos.com/models/pretrained/MobileNetV3_large_x1_0_ssld_pretrained.pdparams
weights: output/yolov3_mobilenet_v3_large_ssld_270e_voc/model_final

# set collate_batch to false because ground-truth info is needed
# on voc dataset and should not collate data in batch when batch size
# is larger than 1.
EvalReader:
  collate_batch: false

LearningRate:
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 216
    - 243
  - !LinearWarmup
    start_factor: 0.
    steps: 1000
```

> /home/PaddleDetection/dataset/voc 的目录内容：
> ![image](https://user-images.githubusercontent.com/5010614/122713326-1ab71480-d298-11eb-8c08-347ac5f467d3.png)

然后提示：unexpected keyword argument 'use_default_label'

之后我把 `yolov3_mobilenet_v3_large_ssld_270e_voc.yml` 恢复了默认的内容，并修改 configs/datasets/voc.yml 中对应的目录：

```
metric: VOC
map_type: 11point
num_classes: 20

TrainDataset:
  !VOCDataSet
    dataset_dir: /home/PaddleDetection/dataset/voc
    anno_path: trainval.txt
    label_list: label_list.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

EvalDataset:
  !VOCDataSet
    dataset_dir: /home/PaddleDetection/dataset/voc
    anno_path: test.txt
    label_list: label_list.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

TestDataset:
  !ImageFolder
    anno_path: dataset/voc/label_list.txt
```
再次执行，得到以下报错信息：

![image](https://user-images.githubusercontent.com/5010614/122720470-17288b00-d2a2-11eb-84a2-ca60feedd8f6.png)

其他说明：

1. VOCdeckit/VOC2012 中的内容格式与 VOC 数据集一致
2. /home/PaddleDetection/dataset/voc/trainval.txt 文件由 /home/PaddleDetection/dataset/voc/create_list.py 生成
