### ISSUE TITLE
paddle inference基于GPU/tensorRT进行推理报错

### ISSUE THREAD

**Issue by ximitiejiang** [PaddlePaddle/PaddleDetection#3489]
你好，使用paddle inference的cpp部署代码进行模型推理时，采用gpu的run_mode为trt_int8时报错！

基本设置：
- paddle inference2.1.0 with cuda10.2/cudnn7.6.5/trt7.0.0.1

问题：
- 在设置为gpu使能，run_mode="fluid"条件下，cpp推理代码运行正常，在fasterrcnn下预测一张1k*1k的图片推理时间大概在450ms左右，这个时间貌似在gpu下有点久啊，不知道这算合理吗？
- 但设置gpu使能，run_mode=“trt_int8”条件下，就会报错如下信息:
```
InvalidArgumentError: The input [image] shape of trt subgraph is [-1,3,-1,-1], please enable trt dynamic_shape mode by SetTRTDynamicShapeInfo. (at C:\home\workspace\Paddle_release\paddle/fluid/inference/tensorrt/engine.h:103)
```
我看了下python下面的export_model.py的代码，默认会导出image_shape=[3,-1,-1]也就是输入图像宽高为dynamic的。但在我的cpp推理代码中，我已经设置了use_dynamic_shape=true，如下所示为加载paddle部署模型的函数调用设置：
```
LoadModel(model_dir, 
    use_gpu,    // true
    min_subgraph_size, // 40, not sure the meaning
    batch_size,   // 1
    run_mode,   // trt_int8
    gpu_id,    // 0
    use_dynamic_shape,  // true
    trt_min_shape,   // 1
    trt_max_shape,   // 1280
    trt_opt_shape);  // 640
```
请问下：
- 在LoadModel()这个函数的设置是否正确，还需要做什么修改设置才能使能trt_dynamic_shape
- 又或者我在导出部署模型时需要做些什么额外设置？
下面是导出的部署模型infer_cfg.yml文件
```
mode: fluid
draw_threshold: 0.5
metric: COCO
image_shape:
- 3
- -1
- -1
arch: RCNN
min_subgraph_size: 40
Preprocess:
- interp: 2
  keep_ratio: true
  target_size:
  - 800
  - 1333
  type: Resize
- is_scale: true
  mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
  type: NormalizeImage
- type: Permute
- stride: 32
  type: PadStride
label_list:
- exposed
- break
- strip
- ok-noexposed1
- ok-noexposed2
- wrinkle
```

thanks!
