### ISSUE TITLE
Deepsort使用eval_mot.py路径问题

### ISSUE THREAD

**Issue by Fitz-Fitz** [PaddlePaddle/PaddleDetection#3509]
Deepsort使用eval_mot.py路径问题自己检测生成的txt文件和视频路径关系应该是什么样子的呢？对应配置文件中EvalMOTDataset:又该如何修改？

**Comment by nemonameless** [comment]
eval_mot.py只支持图片预测，生成的txt文件和视频图片路径可以自己设置--output_dir 默认是叫output。
infer_mot.py只支持视频预测，同理可设置--output_dir
请参考文档 https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/mot/deepsort/README_cn.md
自定义数据集准备请参考 https://github.com/PaddlePaddle/PaddleDetection/blob/develop/docs/tutorials/PrepareMOTDataSet_cn.md 
换MOT-17数据集测可修改为：
```
# for MOT evaluation
# If you want to change the MOT evaluation dataset, please modify 'task' and 'data_root'
EvalMOTDataset:
  !MOTImageFolder
    task: MOT17_train
    dataset_dir: dataset/mot
    data_root: MOT17/images/train
    keep_ori_im: False # set True if save visualization images or video, or used in DeepSORT
```

**Comment by Fitz-Fitz** [comment]
> eval_mot.py只支持图片预测，生成的txt文件和视频图片路径可以自己设置--output_dir 默认是叫output。
> infer_mot.py只支持视频预测，同理可设置--output_dir
> 请参考文档 https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/mot/deepsort/README_cn.md
> 自定义数据集准备请参考 https://github.com/PaddlePaddle/PaddleDetection/blob/develop/docs/tutorials/PrepareMOTDataSet_cn.md
> 换MOT-17数据集测可修改为：
> 
> ```
> # for MOT evaluation
> # If you want to change the MOT evaluation dataset, please modify 'task' and 'data_root'
> EvalMOTDataset:
>   !MOTImageFolder
>     task: MOT17_train
>     dataset_dir: dataset/mot
>     data_root: MOT17/images/train
>     keep_ori_im: False # set True if save visualization images or video, or used in DeepSORT
> ```

嗯嗯根据官方文档是可以操作出来fairmot和jde，我想问的是针对deepsort，现在已有了检测的txt结果文件，如何构建结果txt文件和原图目录结构并修改对应的yml文件，期待您的回复

**Comment by nemonameless** [comment]
请先确保结果txt文件的每行格式是`[frame_id],[bb_left],[bb_top],[width],[height],[conf]`，txt文件夹放哪里都可以，只要你运行的时候`python tools/eval_mot.py -c configs/mot/deepsort/deepsort_pcb_pyramid_r101.yml --det_results_dir` --det_results_dir指定你放的路径即可。

修改对应的yml文件建议修改`configs/mot/deepsort/deepsort_yolov3_pcb_pyramid_r101.yml`或`configs/mot/deepsort/deepsort_pcb_pyramid_r101.yml`的
```
EvalMOTDataset:
  !MOTImageFolder
    task: MOT16_train
    dataset_dir: dataset/mot
    data_root: MOT16/images/train
    keep_ori_im: True # set as True in DeepSORT
```
主要是改task和data_root

请先参考文档 https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/mot/deepsort/README_cn.md
https://github.com/PaddlePaddle/PaddleDetection/blob/develop/docs/tutorials/PrepareMOTDataSet_cn.md
如有文档中写的不清楚的可以具体再问
