### ISSUE TITLE
Fairmot切换custom_data跟踪其他目标

### ISSUE THREAD

**Issue by fly2008begin** [PaddlePaddle/PaddleDetection#3559]
您好 我想利用fairmot 训练跟踪车辆数据，现在我遇到了三个问题
（一）我现在整理好的目录是【custom_data/images/train/seq1/img1/xxx_01.jpg 】、【custom_data/labels_with_ids/train/seq1/xxx_01.txt 】和【custom_data.train】 三类 ，是不是有了labels_with_ids就不用管gt.txt和seqinfo.ini 了 ，原来的Caltech 应该就不往image_lists 放了吧？
（二）我还需要更改什么文件比如configs/datasets/mot.yml 或者configs/mot/fairmot/fairmot_dla34_30e_1088x608.yml 什么的
（三）因为我只有一块GPU，所以我迁移fairmot_dla34_30e_1088x608.pdparams 进行迁移学习是否可行，还需要调整什么？比如在optimizer_30e.yml 调整学习率，epoch什么的，batch size我没有找到在哪里调。

**Comment by nemonameless** [comment]
（一）gt.txt和seqinfo.ini 在eval和infer时有用，建议还是制作下。训自定义数据集，原来的Caltech等都可以不放的。
（二）configs/datasets/mot.yml 里需要改：
```
# for MOT training
TrainDataset:
  !MOTDataSet
    dataset_dir: dataset/mot
    image_lists: ['custom_data.train']
    data_fields: ['image', 'gt_bbox', 'gt_class', 'gt_ide']
```
（三）只有一块GPU，fairmot_dla34_30e_1088x608.pdparams 进行迁移学习也可以，batch size不变时学习率需要调整为默认8卡的lr的1/8，epoch数尽可能多吧按理说应8倍，如果数据集相近finetune也可以不用这么多epoch，batch size在`configs/mot/fairmot/_base_/fairmot_reader_1088x608.yml`的TrainReader最后
