### ISSUE TITLE
自定义coco数据集的问题

### ISSUE THREAD

**Issue by oldZhangYH** [PaddlePaddle/PaddleDetection#3579]
这是报错信息，在数据预处理的时候报错了。
![image](https://user-images.githubusercontent.com/44888861/124346679-c0f90780-dc12-11eb-9797-f0185dbee8c5.png)
这是报错时`sample`的值
![image](https://user-images.githubusercontent.com/44888861/124346815-88a5f900-dc13-11eb-8a4e-aadd7f8c339f.png)
这是我的配置文件
![image](https://user-images.githubusercontent.com/44888861/124346718-edad1f00-dc12-11eb-90b3-0b126e2b62bf.png)
请问是什么原因？

**Comment by nemonameless** [comment]
Mixup使用不当，reader里有改动吗？用的哪个模型，请截图一下类似以下内容看看。
```
TrainReader:
  inputs_def:
    num_max_boxes: 100
  sample_transforms:
    - Decode: {}
    - Mixup: {alpha: 1.5, beta: 1.5}
    - RandomDistort: {}
    - RandomExpand: {fill_value: [123.675, 116.28, 103.53]}
    - RandomCrop: {}
    - RandomFlip: {}
  batch_transforms:
    - BatchRandomResize: {target_size: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608, 640, 672, 704, 736, 768], random_size: True, random_interp: True, keep_ratio: False}
    - NormalizeBox: {}
    - PadBox: {num_max_boxes: 100}
    - BboxXYXY2XYWH: {}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
    - Gt2YoloTarget: {anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]], anchors: [[10, 13], [16, 30], [33, 23], [30, 61], [62, 45], [59, 119], [116, 90], [156, 198], [373, 326]], downsample_ratios: [32, 16, 8]}
  batch_size: 12
  shuffle: true
  drop_last: true
  mixup_epoch: 25000
  use_shared_memory: true
```
