### ISSUE TITLE
FairMOT模型，用MOT20的测试集进行评估出问题。

### ISSUE THREAD

**Issue by zouzhuo777** [PaddlePaddle/PaddleDetection#3582]
我用MOT20数据集训练了FariMOT模型
- 用MOT20训练集评估模型，生成的日志是正常的。
![image](https://user-images.githubusercontent.com/81903241/124358765-5a94d900-dc54-11eb-9c88-c3ea77ce137d.png)

- 但是用MOT20测试集评估模型，生成的日志的[identity]不是从1开始。
![image](https://user-images.githubusercontent.com/81903241/124358752-4d77ea00-dc54-11eb-95d3-a2569c36b0d5.png)

mot.yml配置文件内容如下:
```
# for MOT training
TrainDataset:
  !MOTDataSet
    dataset_dir: dataset/mot
    image_lists: ['mot20.train']
    data_fields: ['image', 'gt_bbox', 'gt_class', 'gt_ide']

# for MOT evaluation
# If you want to change the MOT evaluation dataset, please modify 'task' and 'data_root'
EvalMOTDataset:
  !MOTImageFolder
    task: MOT20_test
    dataset_dir: dataset/mot
    data_root: MOT20/images/test
    keep_ori_im: False # set True if save visualization images or video

# for MOT video inference
TestMOTDataset:
  !MOTVideoDataset
    dataset_dir: dataset/mot
    keep_ori_im: True # set True if save visualization images or video
```
