### ISSUE TITLE
yolov3_r50vd_dcn 导出infer模型，用cpp_infer.py预测没有结果。

### ISSUE THREAD

**Issue by XiaoheYou** [PaddlePaddle/PaddleDetection#366]
paddle 1.7.1
用训练导出的pd.model预测是有结果的。但是export_model之后导出的模型没有结果。
参数配置没有问题，输入的数据没有问题。

**Comment by heavengate** [comment]
测试了下是有结果的，`tools/cpp_demo.yml`如下设置，注意`tools/cpp_infer.py`需要设置`--visualize`
```
# demo for cpp_infer.py

use_python_inference: true # whether to use python inference
mode: fluid # trt_fp32, trt_fp16, trt_int8, fluid
arch: YOLO # YOLO, SSD, RCNN, RetinaNet
min_subgraph_size: 40 # need 3 for YOLO arch

# visualize the predicted image
metric: COCO # COCO, VOC
draw_threshold: 0.1

Preprocess:
- type: Resize
  target_size: 608
  max_size: 608
- type: Normalize
  mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
  is_scale: True
- type: Permute
  to_bgr: False
- type: PadStride
  stride: 0 # set 32 on FPN and 128 on RetinaNet
```
