### ISSUE TITLE
关键点检测的配置文件是否有参数说明文档呀？

### ISSUE THREAD

**Issue by TinyQi** [PaddlePaddle/PaddleDetection#4028]
RT

btw，如果我训练我自己的数据集，需要改哪几个参数啊，我自己瞎改，训出来的模型好像最后输出的张量的shape还是17维（人体关键点数量）的，而不是我数据集的关键点类型数。

我的配置文件如下，我的数据集是证件，然后关键点我是按证件的4个角点作为关键点的。
谢谢各位

```
use_gpu: true
log_iter: 10
save_dir: output
snapshot_epoch: 10
weights: output/higherhrnet_hrnet_w32_512/model_final
epoch: 300
#num_joints: &num_joints 17
#flip_perm: &flip_perm [0, 2, 1, 4, 3, 6, 5, 8, 7, 10, 9, 12, 11, 14, 13, 16, 15]
num_joints: &num_joints 4
flip_perm: &flip_perm [0, 1, 2, 3]
input_size: &input_size 512
hm_size: &hm_size 128
hm_size_2x: &hm_size_2x 256
max_people: &max_people 30
metric: COCO
IouType: keypoints
num_classes: 1


#####model
architecture: HigherHRNet
pretrain_weights: #download_model/higherhrnet_hrnet_w32_512.pdparams

HigherHRNet:
  backbone: HRNet
  hrhrnet_head: HrHRNetHead
  post_process: HrHRNetPostProcess
  flip_perm: *flip_perm
  eval_flip: true

HRNet:
  width: &width 32
  freeze_at: -1
  freeze_norm: false
  return_idx: [0]

HrHRNetHead:
  num_joints: *num_joints
  width: *width
  loss: HrHRNetLoss
  swahr: false

HrHRNetLoss:
  num_joints: *num_joints
  swahr: false


#####optimizer
LearningRate:
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    milestones: [200, 260]
    gamma: 0.1
  - !LinearWarmup
    start_factor: 0.001
    steps: 1000

OptimizerBuilder:
  optimizer:
    type: Adam
  regularizer: None

#####data
TrainDataset:
  !KeypointBottomUpCocoDataset
    image_dir: img
    anno_path: train_little_data_try_4_class.json
    dataset_dir: dataset/business_card/testdata/
    num_joints: *num_joints

EvalDataset:
  !KeypointBottomUpCocoDataset
    image_dir: img
    anno_path: val_little_data_try_4_class.json
    dataset_dir: dataset/business_card/testdata/
    num_joints: *num_joints
    test_mode: true

TestDataset:
  !ImageFolder
    anno_path: dataset/coco/keypoint_imagelist.txt

worker_num: 8
global_mean: &global_mean [0.485, 0.456, 0.406]
global_std: &global_std [0.229, 0.224, 0.225]
TrainReader:
  sample_transforms:
    - RandomAffine:
        max_degree: 30
        scale: [0.75, 1.5]
        max_shift: 0.2
        trainsize: *input_size
        hmsize: [*hm_size, *hm_size_2x]
    - KeyPointFlip:
        flip_prob: 0.5
        flip_permutation: *flip_perm
        hmsize: [*hm_size, *hm_size_2x]
    - ToHeatmaps:
        num_joints: *num_joints
        hmsize: [*hm_size, *hm_size_2x]
        sigma: 2
    - TagGenerate:
        num_joints: *num_joints
        max_people: *max_people
    - NormalizePermute:
        mean: *global_mean
        std: *global_std
  batch_size: 10
  shuffle: true
  drop_last: true
  use_shared_memory: true

EvalReader:
  sample_transforms:
    - EvalAffine:
        size: *input_size
    - NormalizeImage:
        mean: *global_mean
        std: *global_std
        is_scale: true
    - Permute: {}
  batch_size: 1

TestReader:
  sample_transforms:
    - Decode: {}
    - EvalAffine:
        size: *input_size
    - NormalizeImage:
        mean: *global_mean
        std: *global_std
        is_scale: true
    - Permute: {}
  batch_size: 1
```
