### ISSUE TITLE
关于paddledetection resize的问题

### ISSUE THREAD

**Issue by violetweir** [PaddlePaddle/PaddleDetection#4031]
我想请问一下paddledetection在读入照片的时候的resize照片的源代码是哪里呀请问一下

```
worker_num: 2
TrainReader:
  inputs_def:
    num_max_boxes: 100
  sample_transforms:
    - Decode: {}
    - Mixup: {alpha: 1.5, beta: 1.5}
    - RandomDistort: {}
    - RandomExpand: {fill_value: [123.675, 116.28, 103.53]}
    - RandomCrop: {}
    - RandomFlip: {}
  batch_transforms:
    - BatchRandomResize: {target_size: [768], random_size: True, random_interp: True, keep_ratio: False}
    - NormalizeBox: {}
    - PadBox: {num_max_boxes: 100}
    - BboxXYXY2XYWH: {}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
    - Gt2YoloTarget: {anchor_masks: [[6, 7, 8], [3, 4, 5], [0, 1, 2]], anchors: [[25, 37],[35, 58],[50, 73],[57, 109],[85, 82],[79, 142],[116, 158],[151, 248],[337, 464]], downsample_ratios: [32, 16, 8]}
  batch_size: 12
  shuffle: true
  drop_last: true
  mixup_epoch: 25000
  use_shared_memory: true
```
