### ISSUE TITLE
学习率配置的含义

### ISSUE THREAD

**Issue by kingbirdWc** [PaddlePaddle/PaddleDetection#4053]
您好，请教，下面的PiecewiseDecay gamma milestones， LinearWarmup start_factor steps里面的含义是什么呢？
```
LearningRate:
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 216
    - 243
  - !LinearWarmup
    start_factor: 0.
    steps: 4000
```
