### ISSUE TITLE
在配置文件中哪里可以修改优化器？

### ISSUE THREAD

**Issue by zhengzhe97** [PaddlePaddle/PaddleDetection#406]

**Comment by heavengate** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/a3eb2de17b89527f18f69ef33e91da85e16ba0d2/configs/yolov3_darknet.yml#L58

配置文件里面这一段落是配置优化器的

**Comment by zhengzhe97** [comment]
@heavengate 
```
OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0000
    type: L2
```
具体怎么设置，比如说adam和sgd

**Comment by heavengate** [comment]
这里实际上是用`type`和对应的参数去invoke出来paddle的优化器，可以在官网查找优化器需要哪些参数，比如说对于`SGDOptimizer `  https://www.paddlepaddle.org.cn/documentation/docs/zh/api_cn/optimizer_cn/SGDOptimizer_cn.html#cn-api-fluid-optimizer-sgdoptimizer

可以用以下配置
```
OptimizerBuilder:
  optimizer:
    type: SGD
  regularizer:
    factor: 0.0005
    type: L2
```

`optimizer.type`指明优化器名字，其他字段配置参数，`regularizer`按配置里定义，`learning_rate`在配置文件中`LearningRate`段定义
https://github.com/PaddlePaddle/PaddleDetection/blob/a3eb2de17b89527f18f69ef33e91da85e16ba0d2/configs/yolov3_darknet.yml#L46
