### ISSUE TITLE
使用paddle tensorRT进行python推理，无法设置输入的形状尺寸

### ISSUE THREAD

**Issue by xupengao** [PaddlePaddle/PaddleDetection#4193]
GPU为 2080ti paddle为2.0.2，tensorRT=6.0.1.5
以下为我的测试代码，一直报错

```
  File "/data/xupengao/PaddleDetection/paddle_test.py", line 75, in create_predictor
    predictor = paddle_infer.create_predictor(config)
ValueError: (InvalidArgument) some trt inputs dynamic shape info not set, check the INFO log above for more details.
  [Hint: Expected all_dynamic_shape_set == true, but received all_dynamic_shape_set:0 != true:1.] (at /paddle/paddle/fluid/inference/tensorrt/convert/op_converter.h:221)

import numpy as np
import paddle.inference as paddle_infer

def create_predictor():
    config = paddle_infer.Config("/data/xupengao/download/paddle_tensorRT/__model__", "/data/xupengao/download/paddle_tensorRT/__params__")
    config.enable_memory_optim()
    config.enable_use_gpu(1000, 0)


    config.enable_tensorrt_engine(workspace_size = 1 << 30,
                                  max_batch_size = 1,
                                  min_subgraph_size = 3,
                                  precision_mode=paddle_infer.PrecisionType.Float32,
                                  use_static = False, use_calib_mode = False)
    min_input_shape = {"image":[1,3, 400, 400]}
    max_input_shape = {"image":[1,3, 1800, 1800]}
    opt_input_shape = {"image":[1,3, 1216, 1612]}

    config.set_trt_dynamic_shape_info(min_input_shape, max_input_shape, opt_input_shape)
    predictor = paddle_infer.create_predictor(config)
    return predictor

def run(predictor, img):
    # 准备输入
    input_names = predictor.get_input_names()
    for i,  name in enumerate(input_names):
        input_tensor = predictor.get_input_handle(name)
        input_tensor.reshape(img[i].shape)
        input_tensor.copy_from_cpu(img[i].copy())
    # 预测
    predictor.run()
    results = []
    # 获取输出
    output_names = predictor.get_output_names()
    for i, name in enumerate(output_names):
        output_tensor = predictor.get_output_handle(name)
        output_data = output_tensor.copy_to_cpu()
        results.append(output_data)
    return results

if __name__ == '__main__':
    pred = create_predictor()
    img = np.ones((1, 3, 2592, 1944)).astype(np.float32)
    result = run(pred, [img])
    print ("class index: ", np.argmax(result[0][0]))
```

**Comment by jerrywgz** [comment]
建议更新版本到release/2.2分支，然后重新导出模型，目前使用tensorrt6是会自动设置动态shape的

**Comment by xupengao** [comment]
所以是我训练的模型导出的问题么，我直接用deploy/python/infer.py直接去推理是没有问题的，我单拿出来去测试，就会有问题，不知道是哪里的问题

**Comment by jerrywgz** [comment]
可以看下你导出模型时候生成的infer_cfg.yml吗，如果在导出模型的时候，在testreader里指定了shape，那在部署的时候输入大小就需要是固定的

**Comment by xupengao** [comment]
应该是没有指定，我在推理代码上加上指定的尺寸，是没有问题的，但是自己单独测试时不行的。具体参数如下
yaml文件如下
```
use_python_inference: false
mode: fluid
draw_threshold: 0.5
metric: COCO
arch: RCNN
min_subgraph_size: 40
with_background: true
Preprocess:
- is_channel_first: false
  is_scale: true
  mean:
  - 0.485
  - 0.456
  - 0.406
  std:
  - 0.229
  - 0.224
  - 0.225
  type: Normalize
- interp: 1
  max_size: 1621
  target_size: 1216
  type: Resize
  use_cv2: true
- channel_first: true
  to_bgr: false
  type: Permute
- stride: 32
  type: PadStride
label_list:
```
