### ISSUE TITLE
How to get correct label map while train and evaluate mask_rcnn_r101_fpn_1x_coco model.

### ISSUE THREAD

**Issue by fsultana44** [PaddlePaddle/PaddleDetection#4268]
I trained and evaluated my custom coco format dataset namely **COCO**. The dataset has 2 classes.
For train this custom data set I just modify the `configs/datasets/coco_instance.yml ` by providing the dataset path and number of classes 3(with background). I train the dataset using `configs/mask_rcnn/mask_rcnn_r101_fpn_1x_coco.yml ` after the train and evaluate the model using the `configs/mask_rcnn/mask_rcnn_r101_fpn_1x_coco.yml ` I found the output of the inference images provide the correct bounding boxes and objects but wondering to see the wrong label map in the resultant output it has shown **person** and **bicycle** except desire class name.
Here are the snippets of coco annotation JSON file, modified `coco_instance.yml` and the output image.

How can I get my desire class name while using custom training? I appreciate help in this regard.

**Comment by nemonameless** [comment]
Try to modify the anno_path in the TestDataset to the absolute path of your test.json
```
TestDataset:
  !ImageFolder
    anno_path: xxx.json # the absolute path of your xxx.json
```
Even inference a single image, it will read the dataset category from your 'anno_path' json file in TestDataset.   If the category in the 'anno_path' json file is not set or the 'anno_path' json file has not been found, the default category of COCO dataset will be used.

**Comment by fsultana44** [comment]
> Try to modify the anno_path in the TestDataset to the absolute path of your test.json
> 
> ```
> TestDataset:
>   !ImageFolder
>     anno_path: xxx.json # the absolute path of your xxx.json
> ```
> 
> Even inference a single image, it will read the dataset category from your 'anno_path' json file in TestDataset. If the category in the 'anno_path' json file is not set or the 'anno_path' json file has not been found, the default category of COCO dataset will be used.
After modifying the _TestDataset's anno_path_, it still remains the same wrong label map(person and bicycle).
```
TestDataset:
  !ImageFolder
    anno_path: xxx.json # the absolute path of your xxx.json
```

I assumed this problem arose for my dataset. While I used the name of my custom data set **COCO**, its train was evaluated the **mask_rcnn** model well without any error; only inference output gave the wrong label map. I uploaded the same dataset to the **dataset** folder with a different name ***COCO*** and modified the path below.
```
metric: COCO
num_classes: 3 

TrainDataset:
  !COCODataSet
    image_dir: train  
    anno_path: annotation/train.json 
    dataset_dir: dataset/COCO
    data_fields: ['image', 'gt_bbox', 'gt_class', 'gt_poly', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: test 
    anno_path: annotation/test.json 
    dataset_dir: dataset/COCO

TestDataset:
  !ImageFolder
    anno_path: test.json 

```
It has shown the error `ValueError: Dataset dataset/COCO_crack is not valid and cannot parse dataset type 'COCO_crack' for automaticly downloading, which only supports 'voc' , 'coco', 'wider_face', 'fruit', 'roadsign_voc' and 'mot' currently`


I could not get any clue to solve this problem.
