### ISSUE TITLE
[Other General Issues] PPYolo_tiny 训练, mAp 很低, loss无法下降

### ISSUE THREAD

**Issue by Aaron930** [PaddlePaddle/PaddleDetection#4416]
## 环境/Environment
ubuntu 18.04
paddle-det   2.2.0
paddlepaddle-gpu    2.1.0
python   3.7
CUDA    10.2.89
cuDNN 7

## 问题
目标想要训练(火焰，烟雾，行人)三类的模组，gpu单卡训练, 可是mAP卡在30-40，loss也在20-30，实际测试起来效果没有很好... ， 想请问一下是哪边参数出了问题？下的指令是 
```
python3 tools/train.py -c configs/ppyolo/ppyolo_tiny_fs.yml -o pretrain_weights=./pretrain_weight/ppyolo_tiny_650e_coco.pdparams --eval
```
```
[11/01 12:05:50] ppdet.engine INFO: Epoch: [219] [580/603] learning_rate: 0.000040 loss_xy: 2.035727 loss_wh: 2.159919 loss_iou: 7.221734 loss_obj: 12.575647 loss_cls: 0.861220 loss: 24.249638 eta: 1:33:37 batch_cost: 0.2401 data_cost: 0.0008 ips: 49.9837 images/s
[11/01 12:05:54] ppdet.engine INFO: Epoch: [219] [600/603] learning_rate: 0.000040 loss_xy: 2.264960 loss_wh: 2.528252 loss_iou: 8.185173 loss_obj: 12.608075 loss_cls: 1.063343 loss: 27.537605 eta: 1:33:31 batch_cost: 0.1499 data_cost: 0.0001 ips: 80.0328 images/s
[11/01 12:05:56] ppdet.utils.checkpoint INFO: Save checkpoint: output/ppyolo_tiny_fs
[11/01 12:05:56] ppdet.engine INFO: Eval iter: 0
[11/01 12:06:07] ppdet.engine INFO: Eval iter: 100
[11/01 12:06:08] ppdet.metrics.metrics INFO: Accumulating evaluatation results...
[11/01 12:06:08] ppdet.metrics.metrics INFO: mAP(0.50, 11point) = 38.31%
[11/01 12:06:08] ppdet.engine INFO: Total sample number: 804, averge FPS: 67.93417431498997
[11/01 12:06:08] ppdet.engine INFO: Best test bbox ap is 0.383.
[11/01 12:06:08] ppdet.utils.checkpoint INFO: Save checkpoint: output/ppyolo_tiny_fs
[11/01 12:06:09] ppdet.engine INFO: Epoch: [220] [  0/603] learning_rate: 0.000040 loss_xy: 2.281526 loss_wh: 2.528252 loss_iou: 8.185173 loss_obj: 12.958117 loss_cls: 1.014619 loss: 27.537605 eta: 1:33:31 batch_cost: 0.1547 data_cost: 0.0004 ips: 77.5545 images/s
[11/01 12:06:15] ppdet.engine INFO: Epoch: [220] [ 20/603] learning_rate: 0.000040 loss_xy: 2.137350 loss_wh: 2.087429 loss_iou: 6.938436 loss_obj: 13.784716 loss_cls: 0.929574 loss: 25.984428 eta: 1:33:26 batch_cost: 0.2267 data_cost: 0.0004 ips: 52.9300 images/s
```

## 资料集
行人  -  使用voc 2007/2008 的行人资料,总共2500左右
火焰烟雾 - https://aistudio.baidu.com/aistudio/projectdetail/2503301 ,大概6000左右

# yml
```
_BASE_: [
  '../datasets/aaron_yolo.yml',
  '../runtime.yml',
  './_base_/ppyolo_tiny.yml',
  './_base_/optimizer_650e.yml',
  './_base_/ppyolo_tiny_reader.yml',
]

pretrain_weights: ./pretrain_weight/ppyolo_tiny_650e_coco.pdparams
snapshot_epoch: 20
weights: output/latest/model_final

TrainReader:
  mixup_epoch: 350
  batch_size: 12

EvalReader:
  batch_size: 12

# set collate_batch to false because ground-truth info is needed
# on voc dataset and should not collate data in batch when batch size
# is larger than 1.
EvalReader:
  collate_batch: false

epoch: 260

LearningRate:
  base_lr: 0.0004
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 170
    - 235
  - !LinearWarmup
    start_factor: 0.
    steps: 4000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2
```
```
metric: VOC
map_type: 11point
num_classes: 3

TrainDataset:
  !VOCDataSet
    dataset_dir: dataset/211030_fire_smoke
    anno_path: train.txt
    label_list: label_list.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

EvalDataset:
  !VOCDataSet
    dataset_dir: dataset/211030_fire_smoke
    anno_path: val.txt
    label_list: label_list.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

TestDataset:
  !ImageFolder
    anno_path: dataset/211030_fire_smoke/label_list.txt
```
