### ISSUE TITLE
大神么，想在c++上部署Yolov3 无奈不知道Yolov3的yaml文件如何编写。

### ISSUE THREAD

**Issue by baigang666** [PaddlePaddle/PaddleDetection#45]
现在遇到一个问题，按照模型导出方案，将Yolov3模型和参数导出了，在c++部署的时候，找不到对应的Yolov3的yaml配置文件，请问可以尽快更新一下Yolov3的yaml配置文件么？谢谢

**Comment by sjtubinlong** [comment]
@baigang666 您好，后续我们会把几个主要模型的配置文件补全。

Yolov3 配置和 fastrcnn 区别在于两个:
1. `RESIZE_TYPE ` 修改为`UNPADDING_SCALING`
2. `FEEDS_SIZE ` 修改为`2`

参考文件如下：
```yaml
DEPLOY:
    USE_GPU: 1
    MODEL_PATH: "/root/projects/models/yolov3"
    MODEL_FILENAME: "__model__"
    PARAMS_FILENAME: "__params__"
    EVAL_CROP_SIZE: (608, 608)
    RESIZE_TYPE: "UNPADDING_SCALING"
    TARGET_SHORT_SIZE : 800
    MEAN:  [0.485, 0.456, 0.406]
    STD: [0.229, 0.224, 0.225]
    IMAGE_TYPE: "rgb"
    NUM_CLASSES: 1
    CHANNELS : 3
    PRE_PROCESSOR: "DetectionPreProcessor"
    PREDICTOR_MODE: "ANALYSIS"
    BATCH_SIZE : 1 
    RESIZE_MAX_SIZE: 1333
    FEEDS_SIZE: 2
```

每个字段的注释参考文档 https://github.com/PaddlePaddle/PaddleDetection/tree/release/0.1/inference
