### ISSUE TITLE
[Other General Issues]papddleDetection 如何从头开始训练

### ISSUE THREAD

**Issue by lyy1988323** [PaddlePaddle/PaddleDetection#4637]
1. 执行代码：`!python ./tools/train.py -c ../steel_bug_detect/train/ppyolov2_r50vd_dcn_voc.yml --eval --use_vdl=True`
2. 开始正常训练
3.发现参数设置错误，重新修改配置文件后，再次执行代码，发现之前的训练次数被记录下来
4.现在希望从头开始训练，如何操作
   据说可以通过删除训练日志来解决，不知道在哪里删除

我是如何判断之前的训练轮数被记录下来了？
我设置的学习率如下：
```
LearningRate:
  base_lr: 0.00333
  schedulers:
  - !PiecewiseDecay
    gamma: 0.3
    milestones:
    - 410
    - 516
  - !LinearWarmup
    start_factor: 0.
    steps: 4000
```
但是当重新训练的时候，一开始学习率低的惊人
```
[11/21 01:57:00] ppdet.engine INFO: Epoch: [0] [  0/105] learning_rate: 0.000000 loss_xy: 1.762286 loss_wh: 5.321059 loss_iou: 6.392201 loss_iou_aware: 1.458756 loss_obj: 22933.056641 loss_cls: 7.556442 loss: 22955.546875 eta: 1 day, 0:01:19 batch_cost: 0.8236 data_cost: 0.0004 ips: 14.5699 images/s
[11/21 01:57:13] ppdet.engine INFO: Epoch: [0] [ 20/105] learning_rate: 0.000017 loss_xy: 2.071189 loss_wh: 5.465271 loss_iou: 7.198914 loss_iou_aware: 1.557672 loss_obj: 13592.886719 loss_cls: 9.053679 loss: 13622.308594 eta: 16:35:35 batch_cost: 0.5563 data_cost: 0.0003 ips: 21.5714 images/s
```
