### ISSUE TITLE
Setting input size and augmentation on custom dataset during training

### ISSUE THREAD

**Issue by Chitti21** [PaddlePaddle/PaddleDetection#4705]
Hi, 
I am training on PPYOLOv2.

1. How can I disable all augmentations during Training ? I do not want any form of augmentation as my dataset is already augmented.
  (Will deleting the sample transforms and batch transforms in ppyolov2_reader.yml disable all augmentation?)

2. Where can I set the input image size for training. (say 448 x 448)

**Comment by qingqing01** [comment]
1.  You are right,  delete the data augmentation op you don't need in `sample_transforms` and `batch_transforms`

https://github.com/PaddlePaddle/PaddleDetection/blob/2fa33bcc6bdcb497f763e1b88790c6500b825f79/configs/ppyolo/_base_/ppyolov2_reader.yml#L2-L19

2. Now use multi-scale tranining, you can change shape in   `BatchRandomResize`  or add `Resize` in `sample_transforms` like 

https://github.com/PaddlePaddle/PaddleDetection/blob/2fa33bcc6bdcb497f763e1b88790c6500b825f79/configs/ssd/_base_/ssd_reader.yml#L12

**Comment by Chitti21** [comment]
@qingqing01 Thank you for the help. If I don delete any options, the training goes well. 
But when I delete augmentation option, I get keyerror=image. Following is my reader.yml file

```
worker_num: 4
TrainReader:
  inputs_def:
    num_max_boxes: 100
  sample_transforms:
    - Resize: {target_size: [416, 416], keep_ratio: False, interp: 2}
  batch_transforms:
    - BatchRandomResize: {target_size: [416, 448], random_size: True, random_interp: True, keep_ratio: False}
  batch_size: 4
  shuffle: true
  drop_last: true
  mixup_epoch: 200
  use_shared_memory: true

EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [416, 416], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 4

TestReader:
  inputs_def:
    image_shape: [3, 320, 320]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [320, 320], keep_ratio: False, interp: 2}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 1
```


The error that I get is : 

[error_log1.txt](https://github.com/PaddlePaddle/PaddleDetection/files/7601430/error_log1.txt)


1. How can I fix this issue ?
2.  what is worker_num : 4 refer to ? GPU devices ?
