### ISSUE TITLE
训练的时候为什么默认不保持keep ration？，把keep tation设置为True时，训练报错

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/PaddleDetection#4774]
各位大佬，训练的时候为啥默认把图像resize成正方形呢，保持长宽比不更好吗，而且把keep ration设置成True还报错，错误如下
![7J(T8U F` ~E0Z57SGRM1}M](https://user-images.githubusercontent.com/48303408/144337842-0f64c113-6eb8-4a29-8a21-3cb638bccc5f.png)

**Comment by yghstill** [comment]
@Dandelion111 你是指PicoDet模型训练吗？
1.首先，我们验证了在小模型中，keep_ratio=True时，像素很多区域空白，小模型能力有限，尽量图像中所有像素区域都可以用到，所以resize成正方形，同时训练和测试同时保持正方形，就不会影响正常的模型使用。
2.keep_ratio=True时，你的报错，应该是TrainReader中组batch没有对齐图像的shape，需要Pad batch到32的倍数：
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/gfl/_base_/gfl_reader.yml#L10
```yaml
- PadBatch: {pad_to_stride: 32}
```

**Comment by Dandelion111** [comment]
> @Dandelion111 你是指PicoDet模型训练吗？ 1.首先，我们验证了在小模型中，keep_ratio=True时，像素很多区域空白，小模型能力有限，尽量图像中所有像素区域都可以用到，所以resize成正方形，同时训练和测试同时保持正方形，就不会影响正常的模型使用。 2.keep_ratio=True时，你的报错，应该是TrainReader中组batch没有对齐图像的shape，需要Pad batch到32的倍数： https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/gfl/_base_/gfl_reader.yml#L10
> 
> ```yaml
> - PadBatch: {pad_to_stride: 32}
> ```

你好，resize不会对目标造成畸变吗？加入输入的图像长宽比比较大的话，这样训练会有影响吗?我试了下，ap达到0.99，这个指标挺高的

**Comment by Dandelion111** [comment]
> @Dandelion111 你是指PicoDet模型训练吗？ 1.首先，我们验证了在小模型中，keep_ratio=True时，像素很多区域空白，小模型能力有限，尽量图像中所有像素区域都可以用到，所以resize成正方形，同时训练和测试同时保持正方形，就不会影响正常的模型使用。 2.keep_ratio=True时，你的报错，应该是TrainReader中组batch没有对齐图像的shape，需要Pad batch到32的倍数： https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/gfl/_base_/gfl_reader.yml#L10
> 
> ```yaml
> - PadBatch: {pad_to_stride: 32}
> ```

ppdetection所有的检测模型训练都是keep ration关闭，yolov3和ppyolo也是关闭的，这些大模型也不开启keep ration吗

**Comment by yghstill** [comment]
@Dandelion111 训练和验证保持一致就行，物体变形是规律的，让模型学习到这个规律是没有问题的。你说ap达到0.99，是keep_ratio=False时吧？
除了YOLO系列和PicoDet系列，其余模型都是keep_ratio=True的。这个的确实做过对比实验。感兴趣你也可以尝试下。

**Comment by Dandelion111** [comment]
> @Dandelion111 训练和验证保持一致就行，物体变形是规律的，让模型学习到这个规律是没有问题的。你说ap达到0.99，是keep_ratio=False时吧？ 除了YOLO系列和PicoDet系列，其余模型都是keep_ratio=True的。这个的确实做过对比实验。感兴趣你也可以尝试下。

确实是keep ration为False的时候map0.5为0.992，不过AR0.5:0.95只有0.7几，谢谢大佬的解答

**Comment by yghstill** [comment]
@Dandelion111 0.5:0.95比较严苛，按照0.5，指标已经很高啦。

**Comment by Dandelion111** [comment]
> @Dandelion111 0.5:0.95比较严苛，按照0.5，指标已经很高啦。

大佬，您刚才说的- PadBatch: {pad_to_stride: 32}
在picodet中不能加，
![0Z%5%5S0OIU5DN~@SY%NVUW](https://user-images.githubusercontent.com/48303408/144347151-6815a5f7-43c8-443e-90a2-13ae27f256b0.png)
加了这个，开不开keep ration都无法训练，会出现这种错误
![TSYNE}GH0SRK47$(FY2R50M](https://user-images.githubusercontent.com/48303408/144347228-7dea0f64-e9a1-41ca-9d59-7cb8f3421d55.jpg)

**Comment by Dandelion111** [comment]
> @Dandelion111 0.5:0.95比较严苛，按照0.5，指标已经很高啦。

原来开启keep ration显示的错误是输入的图像shape不一致

**Comment by yghstill** [comment]
@Dandelion111 先resize后Pad batch

**Comment by Dandelion111** [comment]
> @Dandelion111 先resize后Pad batch

谢谢大佬，验证了一下，确实如您说的，还是keep ration为false效果更好

**Comment by ChungTak** [comment]
@Dandelion111  请问PicoDet 训练 keep ration为false ，推理前处理是不是也是直接把图片resize就可以。
我自己训练的PicoDet模型用 官方的openvino推理(deploy/third_engine/demo_openvino) 比在Paddle Inference c++ 精度低 10%-20%  一直找不到原因。·。·。·试过直接resize会提高一点，但同一张图片还是比Paddle Inference 低，很奇怪。

**Comment by Dandelion111** [comment]
> @Dandelion111 请问PicoDet 训练 keep ration为false ，推理前处理是不是也是直接把图片resize就可以。 我自己训练的PicoDet模型用 官方的openvino推理(deploy/third_engine/demo_openvino) 比在Paddle Inference c++ 精度低 10%-20% 一直找不到原因。·。·。·试过直接resize会提高一点，但同一张图片还是比Paddle Inference 低，很奇怪。

是的，直接resize，推理和训练保持一致

**Comment by Gmgge** [comment]
@Dandelion111  你好，我按照上面设置  keep_ratio: True ，在之后增加- PadBatch: {pad_to_stride: 32}，但是出现报错ValueError: operands could not be broadcast together with shapes (448,448,32) (1,1,3) (448,448,32) 这是因为最后一个维度也被pad到32了嘛？ 请问下当初有遇到这种情况嘛？

**Comment by Dandelion111** [comment]
> @Dandelion111 你好，我按照上面设置 keep_ratio: True ，在之后增加- PadBatch: {pad_to_stride: 32}，但是出现报错ValueError: operands could not be broadcast together with shapes (448,448,32) (1,1,3) (448,448,32) 这是因为最后一个维度也被pad到32了嘛？ 请问下当初有遇到这种情况嘛？

把PadBatch: {pad_to_stride: 32}放到最后试试

**Comment by Dandelion111** [comment]
> PadBatch

应该是先先resize再padbatch，具体我记不太清了

**Comment by Dandelion111** [comment]
> @Dandelion111 你好，我按照上面设置 keep_ratio: True ，在之后增加- PadBatch: {pad_to_stride: 32}，但是出现报错ValueError: operands could not be broadcast together with shapes (448,448,32) (1,1,3) (448,448,32) 这是因为最后一个维度也被pad到32了嘛？ 请问下当初有遇到这种情况嘛？

应该是先先resize再padbatch，具体我记不太清了

**Comment by Gmgge** [comment]
你好，我也是先resize之后在padbatch
![image](https://user-images.githubusercontent.com/48548141/167777697-18105aaf-ed2f-460b-b88a-26429d93664d.png)
在NormalizeImage 时候报错 维度不匹配 无法计算
![image](https://user-images.githubusercontent.com/48548141/167777746-ddde47dd-ace9-4756-9ddb-27d763c75cfc.png)
@yghstill 你好，这边尝试PicoDet新版本开启keep_ratio训练报错，想请教下有什么其他设置问题嘛？

**Comment by wiekern** [comment]
keep_ratio=True时要进行padding，训练的时候一般是batch_size>1，这时候在batch_transforms里加 `- PadBatch: {pad_to_stride: 32}`，PadBatch这个是批量的，不能加在sample_transforms中，如：
```
TrainReader:
  sample_transforms:
    - Decode: {}
    - Poly2Mask: {del_poly: True}
    - RandomDistort: {prob: 0.8}
    - RandomExpand: {fill_value: [123.675, 116.28, 103.53]}
    - RandomCrop: {prob: 0.8}
    - RandomFlip: {}
  batch_transforms:
    - BatchRandomResize: {target_size: [480, 512, 544, 576, 608, 640, 640, 640, 672, 704, 736, 768, 800], random_size: True, random_interp: True, keep_ratio: True}
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - NormalizeBox: {}
    - BboxXYXY2XYWH: {}
    - Permute: {}
    - PadBatch: {pad_to_stride: 32}  # 新增对齐，PadBatch
```
验证的时候keep_ratio=True, 如果batch_size=1，就在sample_transforms里加，在Reize操作之后加 Pad，Pad 操作是处理单个样本的 如：
```
EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [640, 640], keep_ratio: True, interp: 2}
    - Pad: {size: [640, 640], fill_value: [114., 114., 114.]}
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - Permute: {}
  batch_size: 1 # must be 1
```
验证时，如果开了kepp_ratio，不加Pad操作会导致某些tensor运算时候 shape不匹配，比如我使用mask_rtdetr时，没加Pad报错如下：
```
File "PaddleDetection/ppdet/modeling/transformers/hybrid_encoder.py", line 106, in with_pos_embed
    return tensor if pos_embed is None else tensor + pos_embed
```
