### ISSUE TITLE
[Other General Issues]

### ISSUE THREAD

**Issue by codedlong** [PaddlePaddle/PaddleDetection#4862]
**PaddleDetection team appreciate any suggestion or problem you delivered~**

## 描述问题/Describe the bug
使用ssdlite_mobilenetV3_large_fpn训练Visdrone数据集，训练了600多个epoch，map（iou=0.5）值仍然为0.3，损失始终降不下来，也采用了预训练模型。但是使用faster_rcnn_r50_fpn_1x_visdrone训练VisDrone训练，map(iou=0.5)值达到了41.1，这让我有点不解，是我的训练方式不对吗？

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?

```bash
python tools/train.py -c configs/ssd/ssdlite_mobilenet_v3_large_fpn.yml   --eval
python tools/train.py -c configs/sniper/faster_rcnn_r50_fpn_1x_visdrone.yml --eval
```
2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.

> PaddleDetection rc-2.0 paddlepaddle 2.2.0
> configs/ssd/ssdlite_mobilenet_v3_large_fpn.yml

```yaml
architecture: SSD
use_gpu: true
max_iters: 80000
snapshot_iter: 3000
log_iter: 20
metric: COCO
pretrain_weights: pretrainWeights/MobileNetV3_large_x1_0_ssld_fpn_pretrained
save_dir: output
weights: output/ssdlite_mobilenet_v3_large_fpn/model_final
# 80(label_class) + 1(background)
num_classes: 10

SSD:
  backbone: MobileNetV3
  fpn: FPN
  multi_box_head: SSDLiteMultiBoxHead
  output_decoder:
    background_label: 0
    keep_top_k: 200
    nms_eta: 1.0
    nms_threshold: 0.45
    nms_top_k: 400
    score_threshold: 0.01

FPN:
  num_chan: 256
  max_level: 7
  norm_type: bn
  norm_decay: 0.00004
  reverse_out: true

MobileNetV3:
  scale: 1.0
  model_name: large
  extra_block_filters: [[256, 512], [128, 256], [128, 256], [64, 128]]
  feature_maps: [5, 7, 8, 9, 10, 11]
  lr_mult_list: [0.25, 0.25, 0.5, 0.5, 0.75]
  conv_decay: 0.00004

SSDLiteMultiBoxHead:
  aspect_ratios: [[2.], [2., 3.], [2., 3.], [2., 3.], [2., 3.], [2., 3.]]
  base_size: 320
  steps: [16, 32, 64, 107, 160, 320]
  flip: true
  clip: true
  max_ratio: 95
  min_ratio: 20
  offset: 0.5
  conv_decay: 0.00004

LearningRate:
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [54000, 74000]

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2

TrainReader:
  inputs_def:
    image_shape: [3, 320, 320]
    fields: ['image', 'gt_bbox', 'gt_class']
  dataset:
    !COCODataSet
    dataset_dir: dataset/VisDrone2019_coco
    anno_path: annotations/train.json
    image_dir: train
  sample_transforms:
  - !DecodeImage
    to_rgb: true
  - !RandomDistort
    brightness_lower: 0.875
    brightness_upper: 1.125
    is_order: true
  - !RandomExpand
    fill_value: [123.675, 116.28, 103.53]
  - !RandomCrop
    allow_no_crop: false
  - !NormalizeBox {}
  - !ResizeImage
    interp: 1
    target_size: 320
    use_cv2: false
  - !RandomFlipImage
    is_normalized: false
  - !NormalizeImage
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    is_scale: true
    is_channel_first: false
  - !Permute
    to_bgr: false
    channel_first: true
  batch_size: 64
  shuffle: true
  drop_last: true
  # Number of working threads/processes. To speed up, can be set to 16 or 32 etc.
  worker_num: 8
  # Size of shared memory used in result queue. After increasing `worker_num`, need expand `memsize`.
  memsize: 8G
  # Buffer size for multi threads/processes.one instance in buffer is one batch data.
  # To speed up, can be set to 64 or 128 etc.
  bufsize: 32
  use_process: true


EvalReader:
  inputs_def:
    image_shape: [3, 320, 320]
    fields: ['image', 'gt_bbox', 'gt_class', 'im_shape', 'im_id']
  dataset:
    !COCODataSet
    dataset_dir: dataset/VisDrone2019_coco
    anno_path: annotations/val.json
    image_dir: val
  sample_transforms:
  - !DecodeImage
    to_rgb: true
  - !NormalizeBox {}
  - !ResizeImage
    interp: 1
    target_size: 320
    use_cv2: false
  - !NormalizeImage
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    is_scale: true
    is_channel_first: false
  - !Permute
    to_bgr: false
    channel_first: True
  batch_size: 8
  worker_num: 8
  bufsize: 32
  use_process: false

TestReader:
  inputs_def:
    image_shape: [3,320,320]
    fields: ['image', 'im_id', 'im_shape']
  dataset:
    !ImageFolder
    anno_path: annotations/instances_val2017.json
  sample_transforms:
  - !DecodeImage
    to_rgb: true
  - !ResizeImage
    interp: 1
    max_size: 0
    target_size: 320
    use_cv2: true
  - !NormalizeImage
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    is_scale: true
    is_channel_first: false
  - !Permute
    to_bgr: false
    channel_first: True
  batch_size: 1
```

> PaddleDetection 2.3 paddlepaddle 2.2.0
> configs/sniper/faster_rcnn_r50_fpn_1x_visdrone.yml

**这个配置文件没有任何修改**
```yaml
_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '../faster_rcnn/_base_/optimizer_1x.yml',
  '../faster_rcnn/_base_/faster_rcnn_r50_fpn.yml',
  '../faster_rcnn/_base_/faster_fpn_reader.yml',
]
weights: output/faster_rcnn_r50_fpn_1x_visdrone/model_final


metric: COCO
num_classes: 9

TrainDataset:
  !COCODataSet
    image_dir: train
    anno_path: annotations/train.json
    dataset_dir: dataset/VisDrone2019_coco
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: val
    anno_path: annotations/val.json
    dataset_dir: dataset/VisDrone2019_coco

TestDataset:
  !ImageFolder
    anno_path: annotations/val.json
```
说明：由于在paddleDetection2.3中没有找到关于SSD_mobileNetv3_fpn的yaml文件，所以还是到老版本中进行训练，但是这训练的结果着实有点低了。。。。

3. 您使用的数据集是？/What dataset did you use?
VisDrone2019

4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.
none

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：
Tesla V100 单卡训练
