### ISSUE TITLE
[Document Improvement] 关于ssd_vgg16_300.yml文件问题

### ISSUE THREAD

**Issue by dengxinlong** [PaddlePaddle/PaddleDetection#4867]
在该文件中，对于SSDBoxHead模块中的一些设置比较困惑，比如min_ratio和max_ratio、min_sizes和max_sizes，因为这几个部分和原论文中存在较大区别
```yaml
SSDHead:
   anchor_generator:
   steps: [8, 16, 32, 64, 100, 300]
   aspect_ratios: [[2.], [2., 3.], [2., 3.], [2., 3.], [2.], [2.]]
   min_ratio: 20
   max_ratio: 90
   min_sizes: [30.0, 60.0, 111.0, 162.0, 213.0, 264.0]
   max_sizes: [60.0, 111.0, 162.0, 213.0, 264.0, 315.0]
   offset: 0.5
   flip: true
   min_max_aspect_ratios_order: true
```
我的问题就是：min_ratio和max_ratio、min_sizes和max_sizes是怎么计算得到的？
