### ISSUE TITLE
yolov3_r50vd_dcn.yml 修改报错

### ISSUE THREAD

**Issue by aixier** [PaddlePaddle/PaddleDetection#49]
想去掉 https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.1/configs/dcn/yolov3_r50vd_dcn.yml
里面的这些工具，但是报错不知道还还要改哪里
    - !RandomDistort {}
    - !ExpandImage
    - !CropImage
    - !RandomInterpImage
    - !RandomFlipImage
    - !NormalizeImage

**Comment by qingqing01** [comment]
麻烦给下您修改后的写法，以及贴下具体错误

**Comment by coopot** [comment]
就是把 这几个删除
- !RandomDistort {}
- !ExpandImage
- !CropImage
- !RandomInterpImage
- !RandomFlipImage
- !NormalizeImage

**Comment by aixier** [comment]
不使用这几个增强 ，我们项目不适用。会导致很多问题

**Comment by aixier** [comment]
附 yaml文件和errorlog

[config_and_errorlog.zip](https://github.com/PaddlePaddle/PaddleDetection/files/3909395/config_and_errorlog.zip)

**Comment by qingqing01** [comment]
@aixier 

你发的格式有误，如下的方式，可以正确运行，`NormalizeBox`, `ResizeImage`, `ResizeImage`,  `ResizeImage` 这几个还是必要用的

```
YoloTrainFeed:
  batch_size: 8
  dataset:
    dataset_dir: dataset/coco
    annotation: annotations/instances_val2017.json
    image_dir: val2017
  sample_transforms:
    - !DecodeImage
      to_rgb: True
      with_mixup: false
    - !NormalizeBox {}
    - !ResizeImage
      interp: 2
      target_size: 608
    - !NormalizeImage
      mean:
      - 0.485
      - 0.456
      - 0.406
      std:
      - 0.229
      - 0.224
      - 0.225
      is_scale: True
      is_channel_first: False
    - !Permute
      to_bgr: False
  batch_transforms: []
  num_workers: 8
  bufsize: 128
  use_process: true
```
