### ISSUE TITLE
使用visdrone数据集训练SSD_vgg16_512模型，模型训练到epoch=82，mAP仍然为0？

### ISSUE THREAD

**Issue by dengxinlong** [PaddlePaddle/PaddleDetection#4925]
## 描述问题/Describe the bug
使用visdrone数据集训练SSD_vgg16_512模型，模型训练到epoch=82，mAP仍然为0，对于ssd中配置文件的设置，是我哪里设置错了吗，我使用ssd_vgg16_300训练该数据集，虽然mAP只有9左右（考虑到visdrone这个数据集本身目标尺寸非常小，输入又是300x300像素的图像，经过卷积之后，特征其实已经不能用于分类和定位了），但这个值我个人认为还是正常的，所以我通过提高输入模型的图像的分辨率（512x512），但是结果却为0。（visdrone数据集转换为coco格式，这里转换是没有问题的）

## 复现/Reproduction

1. 您使用的命令是？/What command or script did you run?

```bash
python tools/train.py -c configs/ssd/ssd_vgg16_512_540e_visdrone.yml -o pretrain_weights='' --evalpython tools/train.py -c configs/s
```
这里没有使用预训练模型，因为贵方给定的是ssd_vgg16_300的预训练参数，所以这里不使用

2. 您是否更改过代码或配置文件？您是否理解您所更改的内容？还请您提供所更改的部分代码。/Did you make any modifications on the code or config? Did you understand what you have modified? Please provide the codes that you modified.
> ssd_vgg16_512_540e_visdrone.yml
```yaml
_BASE_: [
  '../datasets/visdrone_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_540e.yml',
  '_base_/ssd_vgg16_512.yml',
  '_base_/ssd_reader_512.yml',
]
weights: output/ssd_vgg16_512_540e_visdrone/model_final

# set collate_batch to false because ground-truth info is needed
# on voc dataset and should not collate data in batch when batch size
# is larger than 1 
EvalReader:
  collate_batch: false
```

> visdrone_detection.yml
```yaml
metric: COCO
num_classes: 9

TrainDataset:
  !COCODataSet
    image_dir: train
    anno_path: annotations/train.json
    dataset_dir: dataset/VisDrone2019_coco
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: val
    anno_path: annotations/val.json
    dataset_dir: dataset/VisDrone2019_coco

TestDataset:
  !ImageFolder
    anno_path: annotations/instances_val2017.json
```

> runtime.yml
```yaml
use_gpu: true
log_iter: 20
save_dir: output
snapshot_epoch: 2
print_flops: false
```

> optimizer_540e.yml
```yaml
epoch: 540

LearningRate:
  base_lr: 0.0001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 360
    - 450
  - !LinearWarmup
    start_factor: 0.3333333333333333
    steps: 500

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0005
    type: L2
```

> ssd_vgg16_512.yml
```yaml
architecture: SSD
pretrain_weights: ./pretrainWeights/VGG16_caffe_pretrained.pdparams

# Model Achitecture
SSD:
  # model feat info flow
  backbone: VGG
  ssd_head: SSDHead
  # post process
  post_process: BBoxPostProcess

VGG:
  depth: 16
  normalizations: [20., -1, -1, -1, -1, -1]

SSDHead:
  anchor_generator:
    steps: [26, 51, 102, 170, 256, 512]
    aspect_ratios: [[2.], [2., 3.], [2., 3.], [2., 3.], [2.], [2.]]
    min_ratio: 1
    max_ratio: 15
    # min_sizes: [30.0, 60.0, 111.0, 162.0, 213.0, 264.0]
    # max_sizes: [60.0, 111.0, 162.0, 213.0, 264.0, 315.0]
    min_sizes: []
    max_sizes: []
    offset: 0.5
    flip: true
    min_max_aspect_ratios_order: true

BBoxPostProcess:
  decode:
    name: SSDBox
  nms:
    name: MultiClassNMS
    keep_top_k: 200
    score_threshold: 0.01
    nms_threshold: 0.45
    nms_top_k: 400
    nms_eta: 1.0
```

> ssd_reader_512.yml
```yaml
worker_num: 2
TrainReader:
  inputs_def:
    num_max_boxes: 90

  sample_transforms:
    - Decode: {}
    - RandomDistort: {brightness: [0.5, 1.125, 0.875], random_apply: False}
    - RandomExpand: {fill_value: [104., 117., 123.]}
    - RandomCrop: {allow_no_crop: true}
    - RandomFlip: {}
    - Resize: {target_size: [512, 512], keep_ratio: False, interp: 1}
    - NormalizeBox: {}
    - PadBox: {num_max_boxes: 90}

  batch_transforms:
    - NormalizeImage: {mean: [104., 117., 123.], std: [1., 1., 1.], is_scale: false}
    - Permute: {}

  batch_size: 20
  shuffle: true
  drop_last: true


EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [512, 512], keep_ratio: False, interp: 1}
    - NormalizeImage: {mean: [104., 117., 123.], std: [1., 1., 1.], is_scale: false}
    - Permute: {}
  batch_size: 16

TestReader:
  inputs_def:
    image_shape: [3, 512, 512]
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [512, 512], keep_ratio: False, interp: 1}
    - NormalizeImage: {mean: [104., 117., 123.], std: [1., 1., 1.], is_scale: false}
    - Permute: {}
  batch_size: 1
```

说明：首先将epoch修改为了540。然后ssd_vgg16_512.yml文件中的min_ratio和max_ratio修改为了1和15，这里主要还是考虑到visdrone数据集目标尺寸过小，所以根据anchor-free方法生成了一系列anchor的尺寸，得到了这两个值，同时将min_sizes和max_sizes注释掉，使用代码中的生成的min_sizes和max_sizes。最后就是ssd_reader_512.yml文件中target_size修改为了512.

3. 您使用的数据集是？/What dataset did you use?
visdrone2019

4. 请提供您出现的报错信息及相关log。/Please provide the error messages or relevant log information.
结果显示
```bash
[12/17 08:48:50] ppdet.engine INFO: Epoch: [78] [  0/323] learning_rate: 0.000100 loss: 11.744663 eta: 4 days, 1:28:44 batch_cost: 2.1480 data_cost: 1.1991 ips: 9.3111 images/s
[12/17 08:49:32] ppdet.engine INFO: Epoch: [78] [ 20/323] learning_rate: 0.000100 loss: 12.019836 eta: 4 days, 1:27:25 batch_cost: 2.0766 data_cost: 1.1337 ips: 9.6311 images/s
[12/17 08:50:15] ppdet.engine INFO: Epoch: [78] [ 40/323] learning_rate: 0.000100 loss: 12.022238 eta: 4 days, 1:26:15 batch_cost: 2.1580 data_cost: 1.2069 ips: 9.2677 images/s
[12/17 08:50:57] ppdet.engine INFO: Epoch: [78] [ 60/323] learning_rate: 0.000100 loss: 11.515100 eta: 4 days, 1:25:00 batch_cost: 2.1125 data_cost: 1.1613 ips: 9.4672 images/s
[12/17 08:51:45] ppdet.engine INFO: Epoch: [78] [ 80/323] learning_rate: 0.000100 loss: 11.901532 eta: 4 days, 1:24:16 batch_cost: 2.3804 data_cost: 1.4325 ips: 8.4018 images/s
[12/17 08:52:30] ppdet.engine INFO: Epoch: [78] [100/323] learning_rate: 0.000100 loss: 11.967754 eta: 4 days, 1:23:18 batch_cost: 2.2579 data_cost: 1.3061 ips: 8.8579 images/s
[12/17 08:53:16] ppdet.engine INFO: Epoch: [78] [120/323] learning_rate: 0.000100 loss: 12.091450 eta: 4 days, 1:22:22 batch_cost: 2.2727 data_cost: 1.3206 ips: 8.8000 images/s
[12/17 08:54:02] ppdet.engine INFO: Epoch: [78] [140/323] learning_rate: 0.000100 loss: 11.721924 eta: 4 days, 1:21:28 batch_cost: 2.2965 data_cost: 1.3395 ips: 8.7091 images/s
[12/17 08:54:43] ppdet.engine INFO: Epoch: [78] [160/323] learning_rate: 0.000100 loss: 11.813888 eta: 4 days, 1:20:06 batch_cost: 2.0535 data_cost: 1.0939 ips: 9.7393 images/s
[12/17 08:55:28] ppdet.engine INFO: Epoch: [78] [180/323] learning_rate: 0.000100 loss: 11.819774 eta: 4 days, 1:19:09 batch_cost: 2.2604 data_cost: 1.3113 ips: 8.8479 images/s
[12/17 08:56:13] ppdet.engine INFO: Epoch: [78] [200/323] learning_rate: 0.000100 loss: 11.759878 eta: 4 days, 1:18:10 batch_cost: 2.2474 data_cost: 1.2708 ips: 8.8994 images/s
[12/17 08:56:59] ppdet.engine INFO: Epoch: [78] [220/323] learning_rate: 0.000100 loss: 11.874834 eta: 4 days, 1:17:15 batch_cost: 2.2887 data_cost: 1.3329 ips: 8.7387 images/s
[12/17 08:57:42] ppdet.engine INFO: Epoch: [78] [240/323] learning_rate: 0.000100 loss: 11.721977 eta: 4 days, 1:16:05 batch_cost: 2.1504 data_cost: 1.1922 ips: 9.3004 images/s
[12/17 08:58:29] ppdet.engine INFO: Epoch: [78] [260/323] learning_rate: 0.000100 loss: 12.070805 eta: 4 days, 1:15:17 batch_cost: 2.3447 data_cost: 1.4021 ips: 8.5300 images/s
[12/17 08:59:15] ppdet.engine INFO: Epoch: [78] [280/323] learning_rate: 0.000100 loss: 11.869123 eta: 4 days, 1:14:23 batch_cost: 2.2926 data_cost: 1.3417 ips: 8.7239 images/s
[12/17 09:00:00] ppdet.engine INFO: Epoch: [78] [300/323] learning_rate: 0.000100 loss: 11.949878 eta: 4 days, 1:13:23 batch_cost: 2.2322 data_cost: 1.2754 ips: 8.9600 images/s
[12/17 09:00:43] ppdet.engine INFO: Epoch: [78] [320/323] learning_rate: 0.000100 loss: 11.903643 eta: 4 days, 1:12:12 batch_cost: 2.1499 data_cost: 1.2024 ips: 9.3028 images/s
[12/17 09:00:53] ppdet.engine INFO: Epoch: [79] [  0/323] learning_rate: 0.000100 loss: 11.940117 eta: 4 days, 1:12:23 batch_cost: 2.3852 data_cost: 1.4373 ips: 8.3849 images/s
[12/17 09:01:39] ppdet.engine INFO: Epoch: [79] [ 20/323] learning_rate: 0.000100 loss: 11.894506 eta: 4 days, 1:11:30 batch_cost: 2.3017 data_cost: 1.3529 ips: 8.6894 images/s
[12/17 09:02:23] ppdet.engine INFO: Epoch: [79] [ 40/323] learning_rate: 0.000100 loss: 11.938265 eta: 4 days, 1:10:25 batch_cost: 2.1970 data_cost: 1.2541 ips: 9.1034 images/s
[12/17 09:03:06] ppdet.engine INFO: Epoch: [79] [ 60/323] learning_rate: 0.000100 loss: 11.825841 eta: 4 days, 1:09:12 batch_cost: 2.1226 data_cost: 1.1716 ips: 9.4226 images/s
[12/17 09:03:50] ppdet.engine INFO: Epoch: [79] [ 80/323] learning_rate: 0.000100 loss: 11.830574 eta: 4 days, 1:08:11 batch_cost: 2.2294 data_cost: 1.2803 ips: 8.9712 images/s
[12/17 09:04:37] ppdet.engine INFO: Epoch: [79] [100/323] learning_rate: 0.000100 loss: 11.841778 eta: 4 days, 1:07:22 batch_cost: 2.3286 data_cost: 1.3786 ips: 8.5889 images/s
[12/17 09:05:19] ppdet.engine INFO: Epoch: [79] [120/323] learning_rate: 0.000100 loss: 11.721057 eta: 4 days, 1:06:08 batch_cost: 2.1230 data_cost: 1.1675 ips: 9.4207 images/s
[12/17 09:06:04] ppdet.engine INFO: Epoch: [79] [140/323] learning_rate: 0.000100 loss: 11.839280 eta: 4 days, 1:05:06 batch_cost: 2.2176 data_cost: 1.2767 ips: 9.0188 images/s
[12/17 09:06:49] ppdet.engine INFO: Epoch: [79] [160/323] learning_rate: 0.000100 loss: 12.102294 eta: 4 days, 1:04:07 batch_cost: 2.2501 data_cost: 1.3068 ips: 8.8883 images/s
[12/17 09:07:34] ppdet.engine INFO: Epoch: [79] [180/323] learning_rate: 0.000100 loss: 11.982029 eta: 4 days, 1:03:08 batch_cost: 2.2383 data_cost: 1.2957 ips: 8.9354 images/s
[12/17 09:08:18] ppdet.engine INFO: Epoch: [79] [200/323] learning_rate: 0.000100 loss: 12.075586 eta: 4 days, 1:02:08 batch_cost: 2.2438 data_cost: 1.2929 ips: 8.9134 images/s
[12/17 09:09:06] ppdet.engine INFO: Epoch: [79] [220/323] learning_rate: 0.000100 loss: 11.968622 eta: 4 days, 1:01:21 batch_cost: 2.3489 data_cost: 1.3588 ips: 8.5145 images/s
[12/17 09:09:51] ppdet.engine INFO: Epoch: [79] [240/323] learning_rate: 0.000100 loss: 11.653918 eta: 4 days, 1:00:25 batch_cost: 2.2706 data_cost: 1.2983 ips: 8.8082 images/s
[12/17 09:10:37] ppdet.engine INFO: Epoch: [79] [260/323] learning_rate: 0.000100 loss: 12.095556 eta: 4 days, 0:59:31 batch_cost: 2.2843 data_cost: 1.3185 ips: 8.7552 images/s
[12/17 09:11:23] ppdet.engine INFO: Epoch: [79] [280/323] learning_rate: 0.000100 loss: 11.853638 eta: 4 days, 0:58:37 batch_cost: 2.2876 data_cost: 1.3289 ips: 8.7427 images/s
[12/17 09:12:05] ppdet.engine INFO: Epoch: [79] [300/323] learning_rate: 0.000100 loss: 11.789781 eta: 4 days, 0:57:22 batch_cost: 2.1103 data_cost: 1.1599 ips: 9.4774 images/s
[12/17 09:12:52] ppdet.engine INFO: Epoch: [79] [320/323] learning_rate: 0.000100 loss: 11.638730 eta: 4 days, 0:56:36 batch_cost: 2.3536 data_cost: 1.3954 ips: 8.4977 images/s
[12/17 09:12:58] ppdet.utils.checkpoint INFO: Save checkpoint: output/ssd_vgg16_512_540e_visdrone
[12/17 09:12:58] ppdet.engine INFO: Eval iter: 0
[12/17 09:13:16] ppdet.metrics.metrics INFO: The bbox result is saved to bbox.json.
loading annotations into memory...
Done (t=0.25s)
creating index...
index created!
[12/17 09:13:16] ppdet.metrics.coco_utils INFO: Start evaluate...
Loading and preparing results...
DONE (t=0.88s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=40.01s).
Accumulating evaluation results...
DONE (t=0.65s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
[12/17 09:13:58] ppdet.engine INFO: Total sample number: 548, averge FPS: 35.555246669857
[12/17 09:13:58] ppdet.engine INFO: Best test bbox ap is 0.000.
[12/17 09:13:59] ppdet.engine INFO: Epoch: [80] [  0/323] learning_rate: 0.000100 loss: 11.677496 eta: 4 days, 0:56:22 batch_cost: 2.3081 data_cost: 1.3493 ips: 8.6652 images/s
[12/17 09:14:41] ppdet.engine INFO: Epoch: [80] [ 20/323] learning_rate: 0.000100 loss: 11.725384 eta: 4 days, 0:55:08 batch_cost: 2.1134 data_cost: 1.1600 ips: 9.4633 images/s
[12/17 09:15:27] ppdet.engine INFO: Epoch: [80] [ 40/323] learning_rate: 0.000100 loss: 11.678532 eta: 4 days, 0:54:14 batch_cost: 2.2867 data_cost: 1.3434 ips: 8.7464 images/s
[12/17 09:16:10] ppdet.engine INFO: Epoch: [80] [ 60/323] learning_rate: 0.000100 loss: 11.671333 eta: 4 days, 0:53:06 batch_cost: 2.1636 data_cost: 1.2168 ips: 9.2439 images/s
[12/17 09:16:58] ppdet.engine INFO: Epoch: [80] [ 80/323] learning_rate: 0.000100 loss: 11.969685 eta: 4 days, 0:52:23 batch_cost: 2.3896 data_cost: 1.4429 ips: 8.3697 images/s
[12/17 09:17:45] ppdet.engine INFO: Epoch: [80] [100/323] learning_rate: 0.000100 loss: 12.113137 eta: 4 days, 0:51:39 batch_cost: 2.3718 data_cost: 1.4214 ips: 8.4325 images/s
[12/17 09:18:26] ppdet.engine INFO: Epoch: [80] [120/323] learning_rate: 0.000100 loss: 11.810704 eta: 4 days, 0:50:16 batch_cost: 2.0340 data_cost: 1.0813 ips: 9.8330 images/s
[12/17 09:19:11] ppdet.engine INFO: Epoch: [80] [140/323] learning_rate: 0.000100 loss: 11.802250 eta: 4 days, 0:49:18 batch_cost: 2.2541 data_cost: 1.3049 ips: 8.8729 images/s
[12/17 09:20:00] ppdet.engine INFO: Epoch: [80] [160/323] learning_rate: 0.000100 loss: 11.796503 eta: 4 days, 0:48:40 batch_cost: 2.4264 data_cost: 1.4652 ips: 8.2428 images/s
[12/17 09:20:50] ppdet.engine INFO: Epoch: [80] [180/323] learning_rate: 0.000100 loss: 11.835796 eta: 4 days, 0:48:10 batch_cost: 2.4939 data_cost: 1.5226 ips: 8.0195 images/s
[12/17 09:21:35] ppdet.engine INFO: Epoch: [80] [200/323] learning_rate: 0.000100 loss: 12.080269 eta: 4 days, 0:47:15 batch_cost: 2.2745 data_cost: 1.3218 ips: 8.7931 images/s
[12/17 09:22:22] ppdet.engine INFO: Epoch: [80] [220/323] learning_rate: 0.000100 loss: 12.006727 eta: 4 days, 0:46:26 batch_cost: 2.3307 data_cost: 1.3709 ips: 8.5810 images/s
[12/17 09:23:06] ppdet.engine INFO: Epoch: [80] [240/323] learning_rate: 0.000100 loss: 11.818688 eta: 4 days, 0:45:23 batch_cost: 2.2111 data_cost: 1.2649 ips: 9.0453 images/s
[12/17 09:23:47] ppdet.engine INFO: Epoch: [80] [260/323] learning_rate: 0.000100 loss: 11.912148 eta: 4 days, 0:43:57 batch_cost: 2.0080 data_cost: 1.0318 ips: 9.9601 images/s
[12/17 09:24:31] ppdet.engine INFO: Epoch: [80] [280/323] learning_rate: 0.000100 loss: 11.733059 eta: 4 days, 0:42:57 batch_cost: 2.2291 data_cost: 1.2865 ips: 8.9724 images/s
[12/17 09:25:18] ppdet.engine INFO: Epoch: [80] [300/323] learning_rate: 0.000100 loss: 11.759735 eta: 4 days, 0:42:11 batch_cost: 2.3548 data_cost: 1.3917 ips: 8.4934 images/s
[12/17 09:26:03] ppdet.engine INFO: Epoch: [80] [320/323] learning_rate: 0.000100 loss: 11.794756 eta: 4 days, 0:41:14 batch_cost: 2.2568 data_cost: 1.2814 ips: 8.8621 images/s
[12/17 09:26:13] ppdet.engine INFO: Epoch: [81] [  0/323] learning_rate: 0.000100 loss: 11.794756 eta: 4 days, 0:41:21 batch_cost: 2.4686 data_cost: 1.4988 ips: 8.1019 images/s
[12/17 09:26:58] ppdet.engine INFO: Epoch: [81] [ 20/323] learning_rate: 0.000100 loss: 11.816735 eta: 4 days, 0:40:19 batch_cost: 2.2145 data_cost: 1.2569 ips: 9.0313 images/s
[12/17 09:27:40] ppdet.engine INFO: Epoch: [81] [ 40/323] learning_rate: 0.000100 loss: 11.867622 eta: 4 days, 0:39:06 batch_cost: 2.1111 data_cost: 1.1413 ips: 9.4737 images/s
[12/17 09:28:23] ppdet.engine INFO: Epoch: [81] [ 60/323] learning_rate: 0.000100 loss: 11.859762 eta: 4 days, 0:37:53 batch_cost: 2.1199 data_cost: 1.1773 ips: 9.4343 images/s
[12/17 09:29:10] ppdet.engine INFO: Epoch: [81] [ 80/323] learning_rate: 0.000100 loss: 11.872942 eta: 4 days, 0:37:09 batch_cost: 2.3723 data_cost: 1.4262 ips: 8.4307 images/s
[12/17 09:29:54] ppdet.engine INFO: Epoch: [81] [100/323] learning_rate: 0.000100 loss: 11.818016 eta: 4 days, 0:36:04 batch_cost: 2.1899 data_cost: 1.2359 ips: 9.1330 images/s
[12/17 09:30:40] ppdet.engine INFO: Epoch: [81] [120/323] learning_rate: 0.000100 loss: 11.874178 eta: 4 days, 0:35:11 batch_cost: 2.2917 data_cost: 1.3184 ips: 8.7272 images/s
[12/17 09:31:26] ppdet.engine INFO: Epoch: [81] [140/323] learning_rate: 0.000100 loss: 12.007284 eta: 4 days, 0:34:21 batch_cost: 2.3257 data_cost: 1.3762 ips: 8.5995 images/s
[12/17 09:32:10] ppdet.engine INFO: Epoch: [81] [160/323] learning_rate: 0.000100 loss: 11.686701 eta: 4 days, 0:33:14 batch_cost: 2.1646 data_cost: 1.2056 ips: 9.2395 images/s
[12/17 09:32:54] ppdet.engine INFO: Epoch: [81] [180/323] learning_rate: 0.000100 loss: 11.627678 eta: 4 days, 0:32:14 batch_cost: 2.2272 data_cost: 1.2843 ips: 8.9799 images/s
[12/17 09:33:41] ppdet.engine INFO: Epoch: [81] [200/323] learning_rate: 0.000100 loss: 11.935854 eta: 4 days, 0:31:23 batch_cost: 2.3134 data_cost: 1.3706 ips: 8.6451 images/s
[12/17 09:34:23] ppdet.engine INFO: Epoch: [81] [220/323] learning_rate: 0.000100 loss: 11.997539 eta: 4 days, 0:30:13 batch_cost: 2.1457 data_cost: 1.1906 ips: 9.3211 images/s
[12/17 09:35:08] ppdet.engine INFO: Epoch: [81] [240/323] learning_rate: 0.000100 loss: 11.733990 eta: 4 days, 0:29:13 batch_cost: 2.2257 data_cost: 1.2762 ips: 8.9858 images/s
[12/17 09:35:53] ppdet.engine INFO: Epoch: [81] [260/323] learning_rate: 0.000100 loss: 11.869278 eta: 4 days, 0:28:12 batch_cost: 2.2223 data_cost: 1.2729 ips: 8.9999 images/s
[12/17 09:36:39] ppdet.engine INFO: Epoch: [81] [280/323] learning_rate: 0.000100 loss: 11.645747 eta: 4 days, 0:27:24 batch_cost: 2.3404 data_cost: 1.3962 ips: 8.5454 images/s
[12/17 09:37:25] ppdet.engine INFO: Epoch: [81] [300/323] learning_rate: 0.000100 loss: 11.787794 eta: 4 days, 0:26:29 batch_cost: 2.2713 data_cost: 1.3248 ips: 8.8056 images/s
[12/17 09:38:06] ppdet.engine INFO: Epoch: [81] [320/323] learning_rate: 0.000100 loss: 11.791275 eta: 4 days, 0:25:07 batch_cost: 2.0327 data_cost: 1.0813 ips: 9.8392 images/s
[12/17 09:38:11] ppdet.utils.checkpoint INFO: Save checkpoint: output/ssd_vgg16_512_540e_visdrone
[12/17 09:38:12] ppdet.engine INFO: Eval iter: 0
[12/17 09:38:29] ppdet.metrics.metrics INFO: The bbox result is saved to bbox.json.
loading annotations into memory...
Done (t=0.26s)
creating index...
index created!
[12/17 09:38:29] ppdet.metrics.coco_utils INFO: Start evaluate...
Loading and preparing results...
DONE (t=0.89s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=50.54s).
Accumulating evaluation results...
DONE (t=0.81s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.000
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.000
[12/17 09:39:22] ppdet.engine INFO: Total sample number: 548, averge FPS: 35.74674490079638
[12/17 09:39:22] ppdet.engine INFO: Best test bbox ap is 0.000.
```

## 环境/Environment
1. 请提供您使用的Paddle和PaddleDetection的版本号/Please provide the version of Paddle and PaddleDetection you use：
Paddle: 2.2.0
PaddleDetection: 2.3
