### ISSUE TITLE
python要怎么调用voc.yml

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleDetection#4944]
想进行调用yml，修改yml
但是报错

`configs\datasets\voc.yml`

```python
data = load(`configs\datasets\voc.yml`, Loader=Loader)
output = dump(data, Dumper=Dumper, encoding=('utf-8'))
```

```
yaml.constructor.ConstructorError: could not determine a constructor for the tag '!VOCDataSet'
  in "<unicode string>", line 6, column 3:
      !VOCDataSet
```

**Comment by nemonameless** [comment]
在你的总的yml里写下数据集的修改配置，会覆盖掉原先voc的配置的。

**Comment by monkeycc** [comment]
PaddleDetection  数据集的格式是
!VOCDataSet
前面带着!

正常的yml格式 读取不了

总的yml里写下数据集的修改配置 
也就是改为 哪个数据集文件

但是不能直接修改里面的参数 
比如 anno_path 和 label_list
```
metric: VOC
map_type: 11point
num_classes: 20

TrainDataset:
  !VOCDataSet:
    dataset_dir: dataset/voc
    anno_path: trainval.txt
    label_list: label_list.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

EvalDataset:
  !VOCDataSet:
    dataset_dir: dataset/voc
    anno_path: test.txt
    label_list: label_list.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

TestDataset:
  !ImageFolder:
    anno_path: dataset/voc/label_list.txt

```
