### ISSUE TITLE
我改用自己的数据训练后，用python tools/train.py -c configs/picodet/picodet_s_320_coco.yml --eval命令运行，跑完的模型识别不出东西

### ISSUE THREAD

**Issue by LMR2018** [PaddlePaddle/PaddleDetection#4950]
我改用自己的数据训练后，用python tools/train.py -c configs/picodet/picodet_s_320_coco.yml --eval命令运行，跑完的模型识别不出东西，我修改了picodet_s_320_coco.yml配置和read.py的num_classes、category.py的clsid2catid、catid2name

[12/19 10:05:55] ppdet.engine INFO: Epoch: [299] [180/208] learning_rate: 0.000000 loss_vfl: 0.017243 loss_bbox: 0.191480 loss_dfl: 0.008528 loss: 0.220344 eta: 0:00:12 batch_cost: 0.4152 data_cost: 0.0003 ips: 19.2693 images/s
[12/19 10:06:05] ppdet.engine INFO: Epoch: [299] [200/208] learning_rate: 0.000000 loss_vfl: 0.016072 loss_bbox: 0.189017 loss_dfl: 0.008492 loss: 0.213641 eta: 0:00:03 batch_cost: 0.4084 data_cost: 0.0001 ips: 19.5886 images/s
[12/19 10:06:09] ppdet.utils.checkpoint INFO: Save checkpoint: output\picodet_s_320_coco
[12/19 10:06:09] ppdet.engine INFO: Eval iter: 0
[12/19 10:06:15] ppdet.engine INFO: Total sample number: 87, averge FPS: 15.869124847785027
[12/19 10:06:15] ppdet.engine WARNING: Evaluation results empty, this may be due to training iterations being too few or not loading the correct weights.

```
_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/picodet_esnet.yml',
  '_base_/optimizer_300e.yml',
  '_base_/picodet_320_reader.yml',
]

pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ESNet_x0_75_pretrained.pdparams
weights: output/picodet_s_320_coco/model_final
find_unused_parameters: True
use_ema: true
cycle_epoch: 20
snapshot_epoch: 5
worker_num: 12

ESNet:
  scale: 0.75
  feature_maps: [4, 11, 14]
  act: hard_swish
  channel_ratio: [0.875, 0.5, 0.5, 0.5, 0.625, 0.5, 0.625, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]

CSPPAN:
  out_channels: 96

PicoHead:
  conv_feat:
    name: PicoFeat
    feat_in: 96
    feat_out: 96
    num_convs: 2
    num_fpn_stride: 4
    norm_type: bn
    share_cls_reg: True
  feat_in_chan: 96


TrainReader:
#  inputs_def:
#    image_shape: [3, 320, 320]
#    num_max_boxes: 5
  sample_transforms:
    - Decode: {}
    - Mixup: {alpha: 1.5, beta: 1.5}
    - RandomDistort: {}
    - RandomExpand: {fill_value: [123.675, 116.28, 103.53]}
    - RandomCrop: {}
    - RandomFlip: {}
#    - AutoAugment: {autoaug_type: v1}
  batch_transforms:
    - BatchRandomResize: {target_size: [320, 352, 384, 416, 448, 480, 512, 544, 576, 608, 640, 672], random_size: True, random_interp: True, keep_ratio: False}
    - NormalizeBox: {}
#    - PadBox: {num_max_boxes: 5}
    - BboxXYXY2XYWH: {}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_size: 8
  shuffle: true
  drop_last: true
  mixup_epoch: 100
  use_shared_memory: true

LearningRate:
  base_lr: 0.001
  schedulers:
  - !CosineDecay
    max_epochs: 20
  - !LinearWarmup
    start_factor: 0.1
    steps: 20
    
EvalReader:
  batch_size: 1

TestReader:
  batch_size: 1
```
