### ISSUE TITLE
detr 训练过程中，验证结果一直是0

### ISSUE THREAD

**Issue by insoliang** [PaddlePaddle/PaddleDetection#5003]
使用自己的数据集，单卡训练，在defomable detr上可以得到90%的map。
在detr上，学习率分别改为0.0001，0.000003，0.00001，结果一直是0。请问是什么原因呢，麻烦帮我看看谢谢！
配置文件如下

```
epoch: 500

LearningRate:
  base_lr: 0.000003
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [400]
    use_warmup: false

OptimizerBuilder:
  clip_grad_by_norm: 0.1
  regularizer: false
  optimizer:
    type: AdamW
    weight_decay: 0.0001
------------------------------------------------------------
worker_num: 2
TrainReader:
  sample_transforms:
  - Decode: {}
  - RandomSelect: { transforms1: [ RandomShortSideResize: { short_side_sizes: [ 480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800 ], max_size: 1333 } ],
                    transforms2: [
                        RandomShortSideResize: { short_side_sizes: [ 400, 500, 600 ] },
                        RandomSizeCrop: { min_size: 384, max_size: 600 },
                        RandomShortSideResize: { short_side_sizes: [ 480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800 ], max_size: 1333 } ]
  }
  - Resize: { interp: 2, target_size: [ 512, 512 ], keep_ratio: False }
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - NormalizeBox: {}
  - BboxXYXY2XYWH: {}
  - Permute: {}
  batch_transforms:
  - PadMaskBatch: {pad_to_stride: -1, return_pad_mask: true}
  batch_size: 2
  shuffle: true
  drop_last: true
  collate_batch: false
  use_shared_memory: false


EvalReader:
  sample_transforms:
  - Decode: {}
  - Resize: {interp: 2, target_size: [512, 512], keep_ratio: False}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadMaskBatch: {pad_to_stride: -1, return_pad_mask: true}
  batch_size: 1
  shuffle: false
  drop_last: false
  drop_empty: false


TestReader:
  sample_transforms:
  - Decode: {}
  - Resize: {interp: 2, target_size: [512, 512], keep_ratio: False}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadMaskBatch: {pad_to_stride: -1, return_pad_mask: true}
  batch_size: 1
  shuffle: false
  drop_last: false
------------------------------------------------------------
architecture: DETR
#pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_vb_normal_pretrained.pdparams
hidden_dim: 256


DETR:
  backbone: ResNet
  transformer: DETRTransformer
  detr_head: DETRHead
  post_process: DETRBBoxPostProcess


ResNet:
  # index 0 stands for res2
  depth: 50
  norm_type: bn
  freeze_at: 0
  return_idx: [3]
  lr_mult_list: [0.0, 0.1, 0.1, 0.1]
  num_stages: 4


DETRTransformer:
  num_queries: 100
  position_embed_type: sine
  nhead: 8
  num_encoder_layers: 6
  num_decoder_layers: 6
  dim_feedforward: 2048
  dropout: 0.1
  activation: relu


DETRHead:
  num_mlp_layers: 3


DETRLoss:
  loss_coeff: {class: 1, bbox: 5, giou: 2, no_object: 0.1, mask: 1, dice: 1}
  aux_loss: True


HungarianMatcher:
  matcher_coeff: {class: 1, bbox: 5, giou: 2}

```
