### ISSUE TITLE
training detection model in voc format

### ISSUE THREAD

**Issue by cena001plus** [PaddlePaddle/PaddleDetection#5126]
When training the detection model in voc format, the pictures and paths and label xml paths in train.txt in the provided example are relative paths. My question is:
(1) Is it possible to make an absolute path so that my data storage address doesn't need to be moved
(2) Does data storage have to be in VOC format? I mean, the absolute paths of the images and labels in my train.txt already exist, so the format of the data storage is so necessary, right?

Another question, why is the configuration file of picodet-m empty?

**Comment by nemonameless** [comment]
(1) You can design it yourself, as long as you can read the data images according to the path. We recommend following the VOC or COCO dataset( format, directory, and img/label path), just change the dataset_dir path in yml file of the dataset ([coco_detection.yml](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/datasets/coco_detection.yml) or [voc.yml](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/datasets/voc.yml)) like this
```
metric: VOC
map_type: 11point
num_classes: 20

TrainDataset:
  !VOCDataSet
    dataset_dir: dataset/voc # your data root
    anno_path: trainval.txt
    label_list: label_list.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

EvalDataset:
  !VOCDataSet
    dataset_dir: dataset/voc  # your data root
    anno_path: test.txt
    label_list: label_list.txt
    data_fields: ['image', 'gt_bbox', 'gt_class', 'difficult']

TestDataset:
  !ImageFolder
    anno_path: dataset/voc/label_list.txt  # your data root
```
(2) Both VOC and COCO format are supported. Please read the [doc](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/docs/tutorials/PrepareDataSet_en.md) to generate your dataset.
