### ISSUE TITLE
关于模型裁剪与量化的问题

### ISSUE THREAD

**Issue by WeizXy** [PaddlePaddle/PaddleDetection#5842]
PaddleDetection开发者你好，
在PaddleDetection中可以看到单独关于剪枝Purne或是量化Quant的配置文件，联合压缩策略也只有蒸馏+剪枝的配置文件，因此请问如果使用裁剪+量化的联合压缩策略时配置文件应该如何写？以联合压缩的配置文件 _PaddleDetection/configs/slim/extensions/yolov3_mobilenet_v1_coco_distill_prune.yml_ 为例该如何修改?

```
_BASE_: [
  '../../yolov3/yolov3_r34_270e_coco.yml',
 ]       #_BASE_部分好像只有蒸馏需要，可否舍去？
 
 pretrain_weights: .....       #预训练权重文件
 
 slim: DistillPrune        #主要是这里，我尝试了PurneQat、PurneQuant，训练时报错:the module PurneQuant is not registered
 #下面是各项压缩策略的具体配置
 distill_loss: DistillYOLOv3Loss    
 
 DistillYOLOv3Loss:
   weight: 1000
 
 pruner: Pruner
 
 Pruner:
   criterion: l1_norm
   pruned_params: ['conv2d_27.w_0', '....]
   pruned_ratios: [0.5,0**....]
```
谢谢！
