### ISSUE TITLE
使用自定义数据集训练solov2模型出现问题

### ISSUE THREAD

**Issue by ahxiaofengzheng** [PaddlePaddle/PaddleDetection#5895]
使用自定义数据集训练solov2模型，运行一个epoch报错。

```
/home/xfz/anaconda3/envs/paddledetection/lib/python3.8/site-packages/paddle/tensor/creation.py:130: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if data.dtype == np.object:
loading annotations into memory...
Done (t=0.02s)
creating index...
index created!
W0506 21:50:37.042760 14745 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 11.2
W0506 21:50:37.050819 14745 device_context.cc:465] device: 0, cuDNN Version: 8.1.
[05/06 21:50:40] ppdet.utils.checkpoint INFO: Finish loading model weights: /home/xfz/.cache/paddle/weights/ResNet101_vd_pretrained.pdparams
[05/06 21:50:43] ppdet.engine INFO: Epoch: [0] [  0/400] learning_rate: 0.000000 loss_ins: 1.758987 loss_cate: 0.969716 loss: 2.728704 eta: 9:45:42 batch_cost: 2.4404 data_cost: 0.0013 ips: 0.8195 images/s
[05/06 21:50:59] ppdet.engine INFO: Epoch: [0] [ 20/400] learning_rate: 0.000100 loss_ins: 0.272232 loss_cate: 0.825926 loss: 1.124424 eta: 3:25:18 batch_cost: 0.7774 data_cost: 0.0001 ips: 2.5725 images/s
[05/06 21:51:16] ppdet.engine INFO: Epoch: [0] [ 40/400] learning_rate: 0.000200 loss_ins: 0.112158 loss_cate: 0.402924 loss: 0.514848 eta: 3:19:55 batch_cost: 0.8129 data_cost: 0.0001 ips: 2.4602 images/s
[05/06 21:51:33] ppdet.engine INFO: Epoch: [0] [ 60/400] learning_rate: 0.000300 loss_ins: 0.076666 loss_cate: 0.337055 loss: 0.410614 eta: 3:15:01 batch_cost: 0.7765 data_cost: 0.0001 ips: 2.5757 images/s
[05/06 21:51:49] ppdet.engine INFO: Epoch: [0] [ 80/400] learning_rate: 0.000400 loss_ins: 0.079139 loss_cate: 0.263513 loss: 0.326394 eta: 3:11:33 batch_cost: 0.7617 data_cost: 0.0001 ips: 2.6256 images/s
[05/06 21:52:06] ppdet.engine INFO: Epoch: [0] [100/400] learning_rate: 0.000500 loss_ins: 0.056761 loss_cate: 0.354100 loss: 0.427221 eta: 3:10:29 batch_cost: 0.7856 data_cost: 0.0002 ips: 2.5459 images/s
[05/06 21:52:23] ppdet.engine INFO: Epoch: [0] [120/400] learning_rate: 0.000600 loss_ins: 0.051542 loss_cate: 0.283493 loss: 0.336922 eta: 3:10:23 batch_cost: 0.8037 data_cost: 0.0002 ips: 2.4886 images/s
[05/06 21:52:40] ppdet.engine INFO: Epoch: [0] [140/400] learning_rate: 0.000700 loss_ins: 0.040318 loss_cate: 0.181330 loss: 0.229313 eta: 3:09:52 batch_cost: 0.7926 data_cost: 0.0001 ips: 2.5234 images/s
[05/06 21:52:56] ppdet.engine INFO: Epoch: [0] [160/400] learning_rate: 0.000800 loss_ins: 0.036349 loss_cate: 0.237305 loss: 0.281707 eta: 3:08:44 batch_cost: 0.7696 data_cost: 0.0001 ips: 2.5988 images/s
[05/06 21:53:12] ppdet.engine INFO: Epoch: [0] [180/400] learning_rate: 0.000900 loss_ins: 0.039457 loss_cate: 0.254705 loss: 0.297191 eta: 3:07:54 batch_cost: 0.7734 data_cost: 0.0001 ips: 2.5859 images/s
[05/06 21:53:29] ppdet.engine INFO: Epoch: [0] [200/400] learning_rate: 0.001000 loss_ins: 0.040039 loss_cate: 0.204073 loss: 0.252577 eta: 3:07:32 batch_cost: 0.7884 data_cost: 0.0001 ips: 2.5367 images/s
[05/06 21:53:46] ppdet.engine INFO: Epoch: [0] [220/400] learning_rate: 0.001100 loss_ins: 0.033969 loss_cate: 0.182664 loss: 0.209822 eta: 3:07:11 batch_cost: 0.7887 data_cost: 0.0001 ips: 2.5357 images/s
[05/06 21:54:02] ppdet.engine INFO: Epoch: [0] [240/400] learning_rate: 0.001200 loss_ins: 0.029029 loss_cate: 0.247056 loss: 0.274311 eta: 3:06:37 batch_cost: 0.7764 data_cost: 0.0001 ips: 2.5759 images/s
[05/06 21:54:19] ppdet.engine INFO: Epoch: [0] [260/400] learning_rate: 0.001300 loss_ins: 0.030929 loss_cate: 0.169740 loss: 0.199488 eta: 3:06:08 batch_cost: 0.7784 data_cost: 0.0001 ips: 2.5695 images/s
[05/06 21:54:35] ppdet.engine INFO: Epoch: [0] [280/400] learning_rate: 0.001400 loss_ins: 0.026570 loss_cate: 0.232757 loss: 0.256096 eta: 3:05:13 batch_cost: 0.7513 data_cost: 0.0001 ips: 2.6621 images/s
[05/06 21:54:52] ppdet.engine INFO: Epoch: [0] [300/400] learning_rate: 0.001500 loss_ins: 0.029481 loss_cate: 0.212557 loss: 0.238631 eta: 3:05:17 batch_cost: 0.8079 data_cost: 0.0001 ips: 2.4756 images/s
[05/06 21:55:09] ppdet.engine INFO: Epoch: [0] [320/400] learning_rate: 0.001600 loss_ins: 0.027137 loss_cate: 0.197767 loss: 0.229214 eta: 3:05:13 batch_cost: 0.8024 data_cost: 0.0001 ips: 2.4925 images/s
[05/06 21:55:26] ppdet.engine INFO: Epoch: [0] [340/400] learning_rate: 0.001700 loss_ins: 0.025123 loss_cate: 0.195107 loss: 0.221325 eta: 3:04:55 batch_cost: 0.7865 data_cost: 0.0001 ips: 2.5429 images/s
[05/06 21:55:42] ppdet.engine INFO: Epoch: [0] [360/400] learning_rate: 0.001800 loss_ins: 0.024899 loss_cate: 0.194250 loss: 0.216956 eta: 3:04:43 batch_cost: 0.7931 data_cost: 0.0001 ips: 2.5219 images/s
[05/06 21:55:59] ppdet.engine INFO: Epoch: [0] [380/400] learning_rate: 0.001900 loss_ins: 0.026392 loss_cate: 0.191227 loss: 0.224156 eta: 3:04:20 batch_cost: 0.7800 data_cost: 0.0001 ips: 2.5641 images/s
[05/06 21:56:17] ppdet.utils.checkpoint INFO: Save checkpoint: output/solov2_r101_vd_fpn_3x_coco
loading annotations into memory...
Done (t=0.01s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
Traceback (most recent call last):
  File "tools/train.py", line 177, in <module>
    main()
  File "tools/train.py", line 173, in main
    run(FLAGS, cfg)
  File "tools/train.py", line 127, in run
    trainer.train(FLAGS.eval)
  File "/home/xfz/PaddleDetection/ppdet/engine/trainer.py", line 501, in train
    self._eval_with_loader(self._eval_loader)
  File "/home/xfz/PaddleDetection/ppdet/engine/trainer.py", line 524, in _eval_with_loader
    outs = self.model(data)
  File "/home/xfz/anaconda3/envs/paddledetection/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/home/xfz/anaconda3/envs/paddledetection/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/xfz/PaddleDetection/ppdet/modeling/architectures/meta_arch.py", line 75, in forward
    outs.append(self.get_pred())
  File "/home/xfz/PaddleDetection/ppdet/modeling/architectures/solov2.py", line 101, in get_pred
    seg_masks, cate_labels, cate_scores, bbox_num = self.solov2_head.get_prediction(
  File "/home/xfz/PaddleDetection/ppdet/modeling/heads/solov2_head.py", line 449, in get_prediction
    seg_masks, cate_labels, cate_scores = self.get_seg_single(
  File "/home/xfz/PaddleDetection/ppdet/modeling/heads/solov2_head.py", line 511, in get_seg_single
    keep = paddle.where(sum_masks > strides, sum_masks, y)
  File "/home/xfz/anaconda3/envs/paddledetection/lib/python3.8/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 264, in __impl__
    return math_op(self, other_var, 'axis', axis)
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [2, 200] and the shape of Y = [32]. Received [200] in X is not equal to [32] in Y at i:1.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:240)
  [operator < greater_than > error]
```

1. 使用的命令是

```
 python tools/train.py -c configs/solov2/solov2_r101_vd_fpn_3x_coco.yml --eval
```

3. 训练前修改的solov2中的solov2_reader.yml和datasets中的coco_instance.yml

solov2_reader.yml：

```
worker_num: 0
TrainReader:
  sample_transforms:
  - Decode: {}
  - Poly2Mask: {}
  - Resize: {interp: 1, target_size: [800, 1333], keep_ratio: True}
  - RandomFlip: {}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  - Gt2Solov2Target: {num_grids: [40, 36, 24, 16, 12],
                        scale_ranges: [[1, 96], [48, 192], [96, 384], [192, 768], [384, 2048]],
                        coord_sigma: 0.2}
  batch_size: 2
  shuffle: true
  drop_last: true


EvalReader:
  sample_transforms:
  - Decode: {}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Resize: {interp: 1, target_size: [800, 1333], keep_ratio: True}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  batch_size: 2
  shuffle: false
  drop_last: false


TestReader:
  sample_transforms:
  - Decode: {}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Resize: {interp: 1, target_size: [800, 1333], keep_ratio: True}
  - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  batch_size: 2
  shuffle: false
  drop_last: false

```
coco_instance.yml
```
metric: COCO
num_classes: 4

TrainDataset:
  !COCODataSet
    image_dir: train
    anno_path: annotations/instance_train.json
    dataset_dir: cocome
    data_fields: ['image', 'gt_bbox', 'gt_class', 'gt_poly', 'is_crowd']

EvalDataset:
  !COCODataSet
    image_dir: val
    anno_path: annotations/instance_val.json
    dataset_dir: cocome

TestDataset:
  !ImageFolder
    anno_path: annotations/instance_val.json # also support txt (like VOC's label_list.txt)
    dataset_dir: cocome # if set, anno_path will be 'dataset_dir/anno_path'

```

5. 使用的数据集是使用labelme标注通过x2coco.py转化为coco格式的数据集：
文件分布：
![图片](https://user-images.githubusercontent.com/81721256/167151417-6944c807-2bc1-43c5-ac8a-006e8883482f.png)
json文件内部：
![图片](https://user-images.githubusercontent.com/81721256/167151653-b4e70492-0558-40b0-a641-96eacd37f081.png)

## 环境/Environment
1. 使用的是环境是：
paddlepaddle-gpu ：2.2.2
paddledet : 2.4.0
2. linux :18.04
3. python:3.8
4.cuda:11.2
