### ISSUE TITLE
关于Faster Rcnn 使用VOC数据集配置文件的修改

### ISSUE THREAD

**Issue by AN-ZE** [PaddlePaddle/PaddleDetection#606]
如题。有没有参考配置文件。

**Comment by AN-ZE** [comment]
把代码改下了 符合自己的voc结构了

**Comment by still-wait** [comment]
@AN-ZE 将TrainReader的dataset设置成:
```yaml
dataset:
    !VOCDataSet
    dataset_dir: dataset/voc
    anno_path: test.txt
```
进行训练即可。
