### ISSUE TITLE
Why "pphuman" can detect only 100 objects?

### ISSUE THREAD

**Issue by nomurakeiya** [PaddlePaddle/PaddleDetection#6712]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

When I use "pphuman"  model, it can detect only 100 objects.
I mean only a maximum of 100 objects can be detected.

I want to detect over 100 objects.
Could you tell me how to do ?

* When I use "visdrone" model, it can detect over 100 objects.

**Comment by nemonameless** [comment]
Before exporting the model(model_final.pdparams), you should set the NMS parameters in config yml like this:
```
  nms:
    name: MultiClassNMS
    nms_top_k: 5000
    keep_top_k: 500 # modify this line
    score_threshold: 0.01
    nms_threshold: 0.6
```
see https://github.com/PaddlePaddle/PaddleDetection/blob/develop/configs/visdrone/ppyoloe_crn_l_80e_visdrone.yml#L39

and then export the model to use in pphuman project.
