### ISSUE TITLE
paddle-lite deploy mot_ppyoloe_s_36e_ppvehicle CheckShape failed

### ISSUE THREAD

**Issue by hbo-lambda** [PaddlePaddle/PaddleDetection#7327]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

环境：
  aarch64
  paddle-lite

使用模型”车辆检测/跟踪“，下载地址https://bj.bcebos.com/v1/paddledet/models/pipeline/mot_ppyoloe_s_36e_ppvehicle.zip

执行以下命令预测时，没问题，能够正常识别
```
python deploy/pipeline/pipeline.py --config deploy/pipeline/config/infer_cfg_ppvehicle.yml \
                                                   --image_file=test_image.jpg \
                                                   --device=gpu
```

模型经过paddle-lite opt工具转换成 .nb文件
修改了Paddle-Lite-Demo/PaddleLite-armlinux-demo/object_detection_demo/object_detection_demo.cc中的const std::vector<int64_t> INPUT_SHAPE = {1, 3, 300, 300}
![Snip20221114_1](https://user-images.githubusercontent.com/7626261/201632512-64ffe8b0-4c33-4b3a-bcb3-6e5b85ba5b50.png)
执行 ./run.sh，报错
![Snip20221114_2](https://user-images.githubusercontent.com/7626261/201632793-488afc7b-411e-4862-a08c-d9370037482f.png)
是尺寸没对上吗？我改回300,300也不对

**Comment by XYZ-916** [comment]
模型要求输入的图像大小是（640，640）吧。

**Comment by hbo-lambda** [comment]
> 模型要求输入的图像大小是（640，640）吧。
mot_ppyoloe_s_36e_ppvehicle.zip这个包里有个配置文件
```
[root@bogon mot_ppyoloe_s_36e_ppvehicle]# cat infer_cfg.yml
mode: paddle
draw_threshold: 0.5
metric: COCO
use_dynamic_shape: false
arch: YOLO
min_subgraph_size: 3
Preprocess:
- interp: 2
  keep_ratio: false
  target_size:
  - 640
  - 640
  type: Resize
- type: Permute
label_list:
- vehicle
```
这里的target是640,640，但是object_detection_demo.cc的INPUT_SHAPE改成640,640会报这个错
```
[F 11/15  0:29:15.480 ...c/Paddle-Lite/lite/operators/split_op.cc:28 CheckShape] Check failed: (param_.axis < static_cast<int>(x_rank)): 1!<0
terminate called after throwing an instance of 'paddle::lite::PaddleLiteException'
  what():  Paddle-Lite C++ Exception:
[F 11/15  0:29:15.480 ...c/Paddle-Lite/lite/operators/split_op.cc:28 CheckShape] Check failed: (param_.axis < static_cast<int>(x_rank)): 1!<0

```
