### ISSUE TITLE
使用faster_rcnn_swin_reader.yml这个配置进行推理时结果框出现偏移

### ISSUE THREAD

**Issue by FroyoZzz** [PaddlePaddle/PaddleDetection#7595]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

训练自己的数据集，推理时结果框有偏移，不知道是不是配置的原因导致
使用的读取配置如下：
```
TestReader:
  sample_transforms:
  - Decode: {}
  - LetterBoxResize: {target_size: [2048, 640]}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_size: 1
  shuffle: false
  drop_last: false
```

推理命令行：
`python tools/infer.py  -c ./configs/faster_rcnn/faster_rcnn_swin_tiny_fpn_3x_coco.yml -o weights=./output/faster_rcnn_swin_tiny_fpn_3x_coco/best_model.pdparams --infer_dir=./test_imgs/ --output_dir=./test_output --draw_threshold=0.1`

推理结果框有偏移：

![image](https://user-images.githubusercontent.com/35131402/210923850-6aa5ad63-5cfc-4961-8afd-b65c71f35bbc.png)
