### ISSUE TITLE
configs多尺度测试EvalReader里的num_scales:18是什么意思，num_scales表示什么

### ISSUE THREAD

**Issue by dota123-star** [PaddlePaddle/PaddleDetection#761]
```
EvalReader:
  batch_size: 1
  inputs_def:
    fields: ['image', 'im_info', 'im_id', 'im_shape']
    multi_scale: true
    num_scales: 18
    use_flip: true
  dataset:
    !COCODataSet
    dataset_dir: dataset/coco
    anno_path: annotations/instances_val2017.json
    image_dir: val2017
  sample_transforms:
  - !DecodeImage
    to_rgb: true
  - !NormalizeImage
    is_channel_first: false
    is_scale: true
    mean:
    - 0.485
    - 0.456
    - 0.406
    std:
    - 0.229
    - 0.224
    - 0.225
  - !MultiscaleTestResize
    origin_target_size: 800
    origin_max_size: 1333
    target_size:
    - 400
    - 500
    - 600
    - 700
    - 900
    - 1000
    - 1100
    - 1200
    max_size: 2000
    use_flip: true
  - !Permute
    channel_first: true
    to_bgr: false
  - !PadMultiScaleTest
    pad_to_stride: 32
  worker_num: 2
```
