### ISSUE TITLE
pptracking segmentation fault

### ISSUE THREAD

**Issue by hbo-lambda** [PaddlePaddle/PaddleDetection#7988]
paddlepaddle-gpu== 2.3.0
硬件配置
![Snip20230323_1](https://user-images.githubusercontent.com/7626261/227134273-bd3b1793-7963-4b03-a776-dd09a07fb42d.png)

想通过拉取视频流来跟踪车辆， 我在deploy/pipeline/pipeline.py 文件中写死了视频流地址(因为这个url里有个&符，编码url或者在rtsp参数上加引号有其他问题出现，为了方便直接写死)
```
FLAGS.rtsp = 'rtsp://test:test@192.168.1.110:554/cam/realmonitor?channel=1&subtype=0
```

执行
```
(paddle) [root@localhost PaddleDetection]# python deploy/pipeline/pipeline.py --config deploy/pipeline/config/infer_cfg_ppvehicle.yml --device=gpu
-----------  Running Arguments -----------
DET:
  batch_size: 1
  model_dir: pretrain_models/pptracking/mot_ppyoloe_l_36e_ppvehicle
LANE_SEG:
  lane_seg_config: deploy/pipeline/config/lane_seg_config.yml
  model_dir: pretrain_models/ppvehicle/pp_lite_stdc2_bdd100k
MOT:
  batch_size: 1
  enable: true
  model_dir: pretrain_models/pptracking/mot_ppyoloe_l_36e_ppvehicle
  skip_frame_num: 2
  tracker_config: deploy/pipeline/config/tracker_config.yml
VEHICLE_ATTR:
  batch_size: 8
  color_threshold: 0.5
  enable: false
  model_dir: pretrain_models/ppvehicle/vehicle_attribute_model
  type_threshold: 0.5
VEHICLE_PLATE:
  det_limit_side_len: 736
  det_limit_type: min
  det_model_dir: pretrain_models/ppvehicle/ch_PP-OCRv3_det_infer
  enable: false
  rec_batch_num: 6
  rec_image_shape:
  - 3
  - 48
  - 320
  rec_model_dir: pretrain_models/ppvehicle/ch_PP-OCRv3_rec_infer
  word_dict_path: deploy/pipeline/ppvehicle/rec_word_dict.txt
VEHICLE_PRESSING:
  enable: false
VEHICLE_RETROGRADE:
  deviation: 23
  enable: false
  fence_line: []
  filter_horizontal_flag: true
  frame_len: 8
  keep_right_flag: true
  move_scale: 0.01
  sample_freq: 7
crop_thresh: 0.5
visual: true
warmup_frame: 50

------------------------------------------
Multi-Object Tracking enabled
DET  model dir:  pretrain_models/pptracking/mot_ppyoloe_l_36e_ppvehicle
MOT  model dir:  pretrain_models/pptracking/mot_ppyoloe_l_36e_ppvehicle
LANE_SEG  model dir:  pretrain_models/ppvehicle/pp_lite_stdc2_bdd100k
-----------  Model Configuration -----------
Model Arch: YOLO
Transform Order:
--transform op: Resize
--transform op: Permute
--------------------------------------------
video fps: 25, frame_count: -2562047788015215
----------------------------------------
Thread: 0; frame id: 0


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1679556762 (unix time) try "date -d @1679556762" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 3489 (TID 0x7f47d9e6f740) from PID 0 ***]

段错误(吐核)
```

这是配置文件内容
```
(paddle) [root@localhost PaddleDetection]# cat deploy/pipeline/config/infer_cfg_ppvehicle.yml
crop_thresh: 0.5
visual: True
warmup_frame: 50

DET:
  model_dir: pretrain_models/pptracking/mot_ppyoloe_l_36e_ppvehicle
  batch_size: 1

MOT:
  model_dir: pretrain_models/pptracking/mot_ppyoloe_l_36e_ppvehicle
  batch_size: 1
  tracker_config: deploy/pipeline/config/tracker_config.yml
  batch_size: 1
  skip_frame_num: 2 # preferably no more than 3
  enable: True

VEHICLE_PLATE:
  det_model_dir: pretrain_models/ppvehicle/ch_PP-OCRv3_det_infer
  det_limit_side_len: 736
  det_limit_type: "min"
  rec_model_dir: pretrain_models/ppvehicle/ch_PP-OCRv3_rec_infer
  rec_image_shape: [3, 48, 320]
  rec_batch_num: 6
  word_dict_path: deploy/pipeline/ppvehicle/rec_word_dict.txt
  enable: False

VEHICLE_ATTR:
  model_dir: pretrain_models/ppvehicle/vehicle_attribute_model
  batch_size: 8
  color_threshold: 0.5
  type_threshold: 0.5
  enable: False

LANE_SEG:
  lane_seg_config: deploy/pipeline/config/lane_seg_config.yml
  model_dir: pretrain_models/ppvehicle/pp_lite_stdc2_bdd100k

VEHICLE_PRESSING:
  enable: False

VEHICLE_RETROGRADE:
  frame_len: 8
  sample_freq: 7
  enable: False
  filter_horizontal_flag: True
  keep_right_flag: True
  deviation: 23
  move_scale: 0.01
  fence_line: []   #[x1,y1,x2,y2] y2>y1.
```
模型文件
![Snip20230323_2](https://user-images.githubusercontent.com/7626261/227134652-c2dba3f5-bf23-4e0c-8978-14651eb5d69f.png)

逐步排查后确定是在SDE_Detector这个类的predict报的错
看到有人说加run_mode=paddle参数检查运行，可我加参数后依然报错
