### ISSUE TITLE
如何训练自己的数据集

### ISSUE THREAD

**Issue by lxk767363331** [PaddlePaddle/PaddleDetection#808]

**Comment by qingqing01** [comment]
当前文档有如何使用自己数据集(肯能看起来有点复杂)、以及迁移学习文档。 我们借下来专门写一篇【如何训练自己数据集】的文档吧。 这里先回答您几点:

1. 如果数据符合COCO或VOC格式，可以直接进入2，否则需要  a.  转换数据至COCO格式或VOC格式，提供了ppdet/data/tools/x2coco.py转换labelme标注的脚本。b. 在ppdet/data/source中添加源码方式。参考数据集文档

2. 选择模型:  依据部署算力选择模型，移动端模型、还是服务器端模型，小物体检测等。 选择好模型对应的配置文件， 可以选择使用COCO预训练做迁移学习。

3. 修改参数配置: 
   -  数据路径配置: YML配置中，依据1中准备好数据的路径，配置TrainReader/EvalReader/TestReader的路径。
     ```yaml
       dataset:
          !COCODataSet  # 如果是VOC，则是 !VOCDataSet
          image_dir: val2017
          anno_path: annotations/instances_val2017.json
          dataset_dir: dataset/coco
     ```
   -  类别数修改: 自己数据集一般类别数和COCO/VOC的类别数不同， 需修改YML中类别数，num_class
   -  看需修改LearningRate相关参数
       - 如果GPU卡数变化，依据lr，batch-size关系调整lr: https://github.com/PaddlePaddle/PaddleDetection/blob/release/0.3/docs/FAQ.md#faq%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
        - 自己数据总数样本数和COCO不同，依据batch_size， 总共的样本数，换算`LearningRate`中的`milestones`。
    - 训练模型`pretrain_weights`配置: 可配置COCO预训练，做迁移学习。

4. 启动训练。
