### ISSUE TITLE
pp-vehicle 实现多类别多目标跟踪。

### ISSUE THREAD

**Issue by Atlantisming** [PaddlePaddle/PaddleDetection#8227]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

您好，我在尝试使用pp-vehicle实现多类别多目标跟踪，通过`pipeline.py` 函数只能实现单类别的多目标跟踪。
使用的模型为`PP-YOLOE+_largesize-l`在VisDrone-DET训练的十类检测模型。
`python tools/export_model.py -c configs/smalldet/visdrone/ppyoloe_plus_sod_crn_l_largesize_80e_visdrone.yml -o weights=https://paddledet.bj.bcebos.com/models/ppyoloe_plus_sod_crn_l_largesize_80e_visdrone.pdparams
`
在推理图片时，
`
python deploy/pipeline/pipeline.py --config deploy/pipeline/config/infer_cfg_ppvehicle_largesize.yml \
                                                   --image_file=/home/aistudio/data/data176741/visdrone/VisDrone2019-DET-test_dev/images/0000320_00900_d_0000008.jpg \
                                                   --device=gpu
`
出现了如下错误：
`
Traceback (most recent call last):
  File "deploy/pipeline/pipeline.py", line 1322, in <module>
    main()
  File "deploy/pipeline/pipeline.py", line 1309, in main
    pipeline.run_multithreads()
  File "deploy/pipeline/pipeline.py", line 179, in run_multithreads
    self.predictor.run(self.input)
  File "deploy/pipeline/pipeline.py", line 535, in run
    self.predict_image(input)
  File "deploy/pipeline/pipeline.py", line 638, in predict_image
    self.visualize_image(batch_file, batch_input, self.pipeline_res)
  File "deploy/pipeline/pipeline.py", line 1267, in visualize_image
    threshold=self.cfg['crop_thresh'])
  File "/home/aistudio/work/PaddleDetection/deploy/python/visualize.py", line 46, in visualize_box_mask
    im = draw_box(im, results['boxes'], labels, threshold=threshold)
  File "/home/aistudio/work/PaddleDetection/deploy/python/visualize.py", line 137, in draw_box
    clsid2color[clsid] = color_list[clsid]
IndexError: list index out of range
`
发现在`pipeline.py line 1263`的函数只显示单类target
![image](https://github.com/PaddlePaddle/PaddleDetection/assets/35071129/6a73bcba-9f1b-4229-82c4-83087612552b)
改成检测器的类别则可以正常运行。

在推理视频时，
`
python deploy/pipeline/pipeline.py --config deploy/pipeline/config/infer_cfg_ppvehicle_largesize.yml \
                                                   --video_file=/home/aistudio/work/PaddleDetection/bdd100k_demo.mp4 \
                                                   --device=gpu
`
发现其只能检测单类。后查找到了该issue: https://github.com/PaddlePaddle/PaddleDetection/issues/6853#issue-1360789785
经过修改之后并未正常检测多类别目标。

配置文件如下：1.`deploy/pipeline/config/infer_cfg_ppvehicle_largesize.yml`:
`
MOT:
  model_dir: /home/aistudio/work/PaddleDetection/output_inference/ppyoloe_plus_sod_crn_l_largesize_80e_visdrone
  tracker_config: deploy/pipeline/config/tracker_config.yml
  batch_size: 1
  skip_frame_num: 2 # preferably no more than 3
  enable: True
`
2.`/home/aistudio/work/PaddleDetection/output_inference/ppyoloe_plus_sod_crn_l_largesize_80e_visdrone/infer_cfg.yml`
```
mode: paddle
draw_threshold: 0.5
metric: COCO
use_dynamic_shape: false
arch: YOLO
min_subgraph_size: 3
Preprocess:
- interp: 2
  keep_ratio: false
  target_size:
  - 1920
  - 1920
  type: Resize
- type: Permute
label_list:
- pedestrian
- people
- bicycle
- car
- van
- truck
- tricycle
- awning-tricycle
- bus
- motor
```
3.`deploy/pipeline/config/tracker_config.yml`:
```
type: JDETracker 

JDETracker:
  use_byte: True
  num_classes: 10
  det_thresh: 0.3
  conf_thres: 0.6
  low_conf_thres: 0.1
  match_thres: 0.9
  min_box_area: 0
  vertical_ratio: 0 
```

但直接使用
`
python deploy/pptracking/python/mot_sde_infer.py --model_dir /home/aistudio/work/PaddleDetection/output_inference/ppyoloe_plus_sod_crn_l_largesize_80e_visdrone \
                                                   --tracker_config deploy/pipeline/config/tracker_config.yml \
                                                   --video_file=/home/aistudio/work/bdd100k_demo.mp4 \
                                                   --device=gpu \
                                                   --do_entrance_counting \
`
可以正常实现多类别跟踪。
想请问在使用pp-vehicle时是否缺少了某个步骤？
