### ISSUE TITLE
使用SSD怎么修改backbone呢？

### ISSUE THREAD

**Issue by legendxty** [PaddlePaddle/PaddleDetection#847]
如题，想要修改backbone为resnet，该怎么配置呢？

**Comment by still-wait** [comment]
@legendxty 
1.请修改config文件：
```yaml
SSD:
  backbone: ResNet
  multi_box_head: SSDLiteMultiBoxHead
  ...

ResNet:
  depth: 50
  feature_maps: [3, 4, 5]
  freeze_at: 2
  norm_type: bn
```
2.backbone设计：由于SSD模型通常需要6个feature map作为检测头的输入，ResNet输出stage3-5的特征图，之后剩余的3个特征图需要增加附加层，详情可以参考[mobilenetv3的extra_block实现](https://github.com/PaddlePaddle/PaddleDetection/blob/release%2F0.3/ppdet/modeling/backbones/mobilenet_v3.py#L311)，最后拼装成list或dict输出。
3.启动训练。
