### ISSUE TITLE
关于使用detection对已经训练好的模型再进行训练的loss疑惑

### ISSUE THREAD

**Issue by WeiYuFei0217** [PaddlePaddle/PaddleDetection#888]
使用yolov3的模型，在一次160000的训练之后loss降到了3.2左右，然后再把预训练模型设置成model_final，无论是改学习率到之前的阶梯（对我上次训练的模型就是0.001*0.008是最后结束的时候的学习率），还是像老师说的啥参数都不调，他会自动继承之前的学习率，再次训练（还是原来训练集的一部分）就发现loss迟迟降不下来，4000之后还4.8以上，想问一下怎么设置才能有效的继续学习呢？哪些参数做修改不会影响到之前训练好的模型的loss呢？（backbone、head什么的；学习率、batch_size、buf_size什么的；对voc格式数据集的train.txt\val.txt什么的......）

**Comment by qingqing01** [comment]
1.  如果是恢复训练，通过`-r`加载checkpoint恢复训练，loss和之前的会保持一样，以及如果使用了mixup，已经过了mixup的epoch时，可关闭mixup，即reader配置中设置mixup_epoch为-1。

2. 也可以评估下mAP看下结果如何， loss不降低也可能是已经收敛。


另外: 
  
COCO配置默认是按照COCO数据量计算的衰减步数，COCO数据总共118287，8GPU训练总共batch-size=64，max_iters=500000，总共训练271个epoch。 分别在40w, 45w的step时调整学习率。 您适配到自己数据时，依据总共的数据量，以及总共的batch_size，可以适当的调整这些参数。

```
LearningRate:
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones:
    - 400000
    - 450000
  - !LinearWarmup
    start_factor: 0.
    steps: 4000
```
