### ISSUE TITLE
跨鏡追蹤如何使用自有資料集訓練

### ISSUE THREAD

**Issue by bernice1357** [PaddlePaddle/PaddleDetection#9043]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我想使用自己的資料集訓練跨鏡追蹤功能，我跟著https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.7/docs/advanced_tutorials/customization/pphuman_mtmct.md
這個文件執行，結果在執行程式時發現以下報錯:

```
Traceback (most recent call last):
  File "D:\ai_contest\PaddleClas\tools\train.py", line 31, in <module>
    engine = Engine(config, mode="train")
  File "D:\ai_contest\PaddleClas\ppcls\engine\engine.py", line 131, in __init__
    self.train_dataloader = build_dataloader(
  File "D:\ai_contest\PaddleClas\ppcls\data\__init__.py", line 116, in build_dataloader
    dataset = eval(dataset_name)(**config_dataset)
  File "D:\ai_contest\PaddleClas\ppcls\data\dataloader\person_dataset.py", line 55, in __init__
    self._check_before_run()
  File "D:\ai_contest\PaddleClas\ppcls\data\dataloader\person_dataset.py", line 65, in _check_before_run
    raise RuntimeError("'{}' is not available".format(
RuntimeError: './pic/output_images\market1501/Market-1501-v15.09.15\bounding_box_train' is not available
```

這邊是我的`PaddleClas\ppcls\configs\reid\strong_baseline\softmax_triplet_with_center.yaml`，我照著文件修改了DataLoader和Eval的image_root

```
# global configs
Global:
  checkpoints: null
  pretrained_model: null
  output_dir: "./output/"
  device: "gpu"
  save_interval: 40
  eval_during_train: True
  eval_interval: 10
  epochs: 120
  print_batch_step: 20
  use_visualdl: False
  eval_mode: "retrieval"
  retrieval_feature_from: "features" # 'backbone' or 'features'
  re_ranking: False
  # used for static mode and model export
  image_shape: [3, 256, 128]
  save_inference_dir: "./inference"

# model architecture
Arch:
  name: "RecModel"
  infer_output_key: "features"
  infer_add_softmax: False
  Backbone:
    name: "ResNet50_last_stage_stride1"
    pretrained: https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/others/resnet50-19c8e357_torch2paddle.pdparams
    stem_act: null
  BackboneStopLayer:
    name: "flatten"
  Neck:
    name: BNNeck
    num_features: &feat_dim 2048
    weight_attr:
      initializer:
        name: Constant
        value: 1.0
    bias_attr:
      initializer:
        name: Constant
        value: 0.0
      learning_rate: 1.0e-20 # NOTE: Temporarily set lr small enough to freeze the bias to zero
  Head:
    name: "FC"
    embedding_size: *feat_dim
    class_num: &class_num 4
    weight_attr:
      initializer:
        name: Normal
        std: 0.001
    bias_attr: False

# loss function config for traing/eval process
Loss:
  Train:
    - CELoss:
        weight: 1.0
        epsilon: 0.1
    - TripletLossV2:
        weight: 1.0
        margin: 0.3
        normalize_feature: False
        feature_from: "backbone"
    - CenterLoss:
        weight: 0.0005
        num_classes: *class_num
        feat_dim: *feat_dim
        feature_from: "backbone"
  Eval:
    - CELoss:
        weight: 1.0

Optimizer:
  - Adam:
      scope: RecModel
      lr:
        name: Piecewise
        decay_epochs: [30, 60]
        values: [0.00035, 0.000035, 0.0000035]
        warmup_epoch: 10
        warmup_start_lr: 0.0000035
        by_epoch: True
        last_epoch: 0
      regularizer:
        name: "L2"
        coeff: 0.0005
  - SGD:
      scope: CenterLoss
      lr:
        name: ConstLR
        learning_rate: 1000.0 # NOTE: set to ori_lr*(1/centerloss_weight) to avoid manually scaling centers' gradidents.

# data loader for train and eval
DataLoader:
  Train:
    dataset:
      name: "Market1501"
      image_root: "./pic/output_images"
      cls_label_path: "bounding_box_train"
      backend: "pil"
      transform_ops:
        - ResizeImage:
            size: [128, 256]
            return_numpy: False
            interpolation: "bilinear"
            backend: "pil"
        - RandFlipImage:
            flip_code: 1
        - Pad:
            padding: 10
        - RandCropImageV2:
            size: [128, 256]
        - ToTensor:
        - Normalize:
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
        - RandomErasing:
            EPSILON: 0.5
            sl: 0.02
            sh: 0.4
            r1: 0.3
            mean: [0.485, 0.456, 0.406]
    sampler:
      name: DistributedRandomIdentitySampler
      batch_size: 64
      num_instances: 4
      drop_last: False
      shuffle: True
    loader:
      num_workers: 4
      use_shared_memory: True
  Eval:
    Query:
      dataset:
        name: "Market1501"
        image_root: "./pic/eval_images"
        cls_label_path: "bounding_box_train"
        backend: "pil"
        transform_ops:
          - ResizeImage:
              size: [128, 256]
              return_numpy: False
              interpolation: "bilinear"
              backend: "pil"
          - ToTensor:
          - Normalize:
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]
      sampler:
        name: DistributedBatchSampler
        batch_size: 128
        drop_last: False
        shuffle: False
      loader:
        num_workers: 4
        use_shared_memory: True

    Gallery:
      dataset:
        name: "Market1501"
        image_root: "./dataset/"
        cls_label_path: "bounding_box_test"
        backend: "pil"
        transform_ops:
          - ResizeImage:
              size: [128, 256]
              return_numpy: False
              interpolation: "bilinear"
              backend: "pil"
          - ToTensor:
          - Normalize:
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]
      sampler:
        name: DistributedBatchSampler
        batch_size: 128
        drop_last: False
        shuffle: False
      loader:
        num_workers: 4
        use_shared_memory: True

Metric:
  Eval:
    - Recallk:
        topk: [1, 5]
    - mAP: {}
```
想請問有什麼方法可以解決嗎?
