### ISSUE TITLE
关于ppyoloer训练目标框体旋转角度近似0度时的框体时角度拟合程度很差的问题

### ISSUE THREAD

**Issue by hxuaj** [PaddlePaddle/PaddleDetection#9086]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我在使用ppyoloer训练旋转框目标检测模型时发现目标框体旋转角度近似0度时的框体角度拟合程度很差。相比较有一定角度的目标框拟合却没什么问题。TrainerReader中的配置如下：
```yaml
TrainReader:
  sample_transforms:
    - Decode: {}
    - Poly2Array: {}
    - RandomRFlip: {}
    - RandomRRotate: {angle_mode: 'value', angle: [0, 90, 180, -90]}
    - RandomRRotate: {angle_mode: 'value', angle: [30, 60], rotate_prob: 0.5}
    - RResize: {target_size: *image_size, keep_ratio: True, interp: 2}
    - Poly2RBox: {filter_threshold: 2, filter_mode: 'edge', rbox_type: 'oc'}
```
排除了后处理过程中的rbox2poly和dl_loss计算的问题。是因为目标0度时的loss过小导致的吗？不太确定是bug还是模型本身缺陷。请问有什么修改或者优化的空间？
