### ISSUE TITLE
快速体验中 infer.py 报错，缺少json文件

### ISSUE THREAD

**Issue by EvW1998** [PaddlePaddle/PaddleDetection#9192]
### 问题确认 Search before asking

- [X] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

我在运行[快速体验](https://github.com/PaddlePaddle/PaddleDetection/blob/develop/docs/tutorials/QUICK_STARTED_cn.md)中的推理代码 `python tools/infer.py -c configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml -o use_gpu=true weights=https://paddledet.bj.bcebos.com/models/ppyolo_r50vd_dcn_1x_coco.pdparams --infer_img=demo/000000014439.jpg` 时发生了错误。

提示`No such file or directory: 'dataset/coco/annotations/instances_val2017.json'`

为什么推理还需要下载标注文件呢？

**Comment by masiqi** [comment]
我也遇到了同样的问题，然后自己下载一个json文件放在那里就好了，官方文档确实不太友好

**Comment by Metavers1** [comment]
而且，TMD，直接运行train 也不行，需要自己手动下载dota 或者coco数据集放在那里，我都无法快速验证配的环境能不能训练和导出

**Comment by zhang-prog** [comment]
可以参考 masiqi 的解决方法，也可以尝试使用[PaddleX](https://github.com/paddlepaddle/paddlex)进行单图推理，相关的使用说明在这里～[目标检测模型](https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta1/docs/module_usage/tutorials/cv_modules/object_detection.md)，[目标检测产线](https://github.com/PaddlePaddle/PaddleX/blob/release/3.0-beta1/docs/pipeline_usage/tutorials/cv_pipelines/object_detection.md)

**Comment by DazzlingGalaxy** [comment]
> 我也遇到了同样的问题，然后自己下载一个json文件放在那里就好了，官方文档确实不太友好

请问下载链接是什么？在哪能看到？

**Comment by masiqi** [comment]
> > 我也遇到了同样的问题，然后自己下载一个json文件放在那里就好了，官方文档确实不太友好
> 
> 请问下载链接是什么？在哪能看到？

[instances_val2017.json](https://github.com/user-attachments/files/17634583/instances_val2017.json)
应该是这个，你随便跟网上的开源数据集平台上找也能找到的

**Comment by DazzlingGalaxy** [comment]
> > > 我也遇到了同样的问题，然后自己下载一个json文件放在那里就好了，官方文档确实不太友好
> > 
> > 
> > 请问下载链接是什么？在哪能看到？
> 
> [instances_val2017.json](https://github.com/user-attachments/files/17634583/instances_val2017.json) 应该是这个，你随便跟网上的开源数据集平台上找也能找到的

谢谢，可以了。
我在`configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml`看到
```
_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  './_base_/ppyolo_r50vd_dcn.yml',
  './_base_/optimizer_1x.yml',
  './_base_/ppyolo_reader.yml',
]

snapshot_epoch: 16
weights: output/ppyolo_r50vd_dcn_1x_coco/model_final
```
然后去`../datasets/coco_detection.yml`中看到
```
metric: COCO
num_classes: 80

TrainDataset:
  name: COCODataSet
  image_dir: train2017
  anno_path: annotations/instances_train2017.json
  dataset_dir: dataset/coco
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: COCODataSet
  image_dir: val2017
  anno_path: annotations/instances_val2017.json
  dataset_dir: dataset/coco
  allow_empty: true

TestDataset:
  name: ImageFolder
  anno_path: annotations/instances_val2017.json # also support txt (like VOC's label_list.txt)
  dataset_dir: dataset/coco # if set, anno_path will be 'dataset_dir/anno_path'
```
原来是在这里用了`instances_train2017.json`，你说可以在开源数据集平台上能找到，是Hugging Face或魔搭吗(我是新手，只知道这两个，还是说还有其他的)？我在[这里](https://huggingface.co/amd/yolox-s/blob/main/README.md)看到了[annotations_trainval2017.zip](http://images.cocodataset.org/annotations/annotations_trainval2017.zip)，下载后里面有`instances_train2017.json`，也可以用，但比你的大得多，有什么区别？
