### ISSUE TITLE
预测部署导出模型后使用deploy/python/infer.py 报RuntimeError: (PreconditionNotMet) op [] kernel output args (0) defs should equal op outputs (1)

### ISSUE THREAD

**Issue by cstcood** [PaddlePaddle/PaddleDetection#9288]
### 问题确认 Search before asking

- [x] 我已经搜索过问题，但是没有找到解答。I have searched the question and found no related answer.

### 请提出你的问题 Please ask your question

相关敏感绝对路径已用相对路径替换，不影响阅读

使用自定义的数据集转换为coco格式，在rtdetr_r50vd_6x_coco上 使用train进行训练 命令如下

 ```python tools/train.py -c configs/rtdetr/rtdetr_r50vd_6x_coco.yml --eval```

修改coco_detection.yml如下：
```
metric: COCO
num_classes: 1

TrainDataset:
  name: COCODataSet
  image_dir: train
  anno_path: annotations/instances_train.json
  dataset_dir: dataset/mobile_coco
  data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

EvalDataset:
  name: COCODataSet
  image_dir: val
  anno_path: annotations/instances_val.json
  dataset_dir: dataset/mobile_coco
  allow_empty: true

TestDataset:
  name: ImageFolder
  anno_path: annotations/instances_val.json # also support txt (like VOC's label_list.txt)
  dataset_dir: dataset/mobile_coco # if set, anno_path will be 'dataset_dir/anno_path'

```
训练完成后可以正常使用

```
python tools/infer.py -c configs/rtdetr/rtdetr_r50vd_6x_coco.yml  -o weights=xxxxx\best_model.pdparams --output_dir=output --infer_img=dataset/mobile_coco/test.png
```
进行预测

但是当我想用端部署时候使用
```
python tools/export_model.py -c configs/rtdetr/rtdetr_r50vd_6x_coco.yml  -o weights=.\output\best_model\best_model.pdparams --output_dir=.\output\best_model\export
```
正常输出
```
信息: 用提供的模式无法找到文件。
[01/20 17:00:34] ppdet.engine INFO: Model Params : 42.782020568847656 M.
[01/20 17:00:34] ppdet.utils.checkpoint INFO: Finish loading model weights: 
.\output\best_model\best_model.pdparams
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
[01/20 17:00:35] ppdet.engine INFO: Export inference config file to .\output\best_model\export\rtdetr_r50vd_6x_coco\infer_cfg.yml
[01/20 17:00:45] ppdet.engine INFO: Export model and saved in  .\output\best_model\export\rtdetr_r50vd_6x_coco
```
生成文件如下：
infer_cfg.yml model.json model.pdiparams

此时使用以下命令运行时报错
 ```python deploy/python/infer.py --model_dir=.\output\best_model\export\rtdetr_r50vd_6x_coco --image_file=.\dataset\mobile_coco\test.png ```

输出以下信息：
```
信息: 用提供的模式无法找到文件。
xxxx\anaconda3\envs\paddle_detect\lib\site-packages\paddle\utils\cpp_extension\extension_utils.py:711: UserWarning: No ccache found. Please be aware that recompiling all source files may be required. You can download and install ccache from: https://github.com/ccache/ccache/blob/master/doc/INSTALL.md
  warnings.warn(warning_message)
-----------  Running Arguments -----------
action_file: None
batch_size: 1
camera_id: -1
collect_trt_shape_info: False
combine_method: nms
cpu_threads: 1
device: cpu
enable_mkldnn: False
enable_mkldnn_bfloat16: False
image_dir: None
image_file: .\dataset\mobile_coco\test.png
match_metric: ios
match_threshold: 0.6
model_dir: .\output\best_model\export\rtdetr_r50vd_6x_coco
output_dir: output
overlap_ratio: [0.25, 0.25]
random_pad: False
reid_batch_size: 50
reid_model_dir: None
run_benchmark: False
run_mode: paddle
save_images: True
save_mot_txt_per_img: False
save_mot_txts: False
save_results: False
scaled: False
slice_infer: False
slice_size: [640, 640]
task_type: Detection
threshold: 0.5
tracker_config: None
trt_calib_mode: False
trt_max_shape: 1280
trt_min_shape: 1
trt_opt_shape: 640
tuned_trt_shape_file: shape_range_info.pbtxt
use_coco_category: True
use_dark: True
use_fd_format: False
use_gpu: False
video_file: None
window_size: 50
------------------------------------------
-----------  Model Configuration -----------
Model Arch: DETR
Transform Order:
--transform op: Resize
--transform op: NormalizeImage
--transform op: Permute
--------------------------------------------
Traceback (most recent call last):
  File "E.\deploy\python\infer.py", line 1266, in <module>
    main()
  File ".\deploy\python\infer.py", line 1199, in main
    detector = eval(detector_func)(
  File ".\deploy\python\infer.py", line 108, in __init__
    self.predictor, self.config = load_predictor(
  File ".\deploy\python\infer.py", line 1098, in load_predictor
    predictor = create_predictor(config)
RuntimeError: (PreconditionNotMet) op [] kernel output args (0) defs should equal op outputs (1)
  [Hint: Expected op_item->num_results() == output_defs.size(), but received op_item->num_results():1 != output_defs.size():0.] (at C:\home\workspace\Paddle\paddle\fluid\pir\transforms\pd_op_to_kernel_pass.cc:2477)
```
请问如何解决。
